### ISSUE TITLE
Not using JDBC because of exception while matching parts of JDBC url: No group with name <protocol>

### ISSUE THREAD

**Issue by mibby** [DiscordSRV/DiscordSRV#1015]
DiscordSRV-Build-1.22.0-SNAPSHOT-1612782592

Breaking commit? https://github.com/DiscordSRV/DiscordSRV/commit/6d7624f940d63a2a3b844090aeca4d1d880da9c7 or https://github.com/DiscordSRV/DiscordSRV/commit/6b612369d594ec98c3a0888cb8e8c4334a088ad7

For reference, I do use jdbc.
```
Experiment_JdbcAccountLinkBackend: "jdbc:mysql://localhost:3306/discordsrv?autoReconnect=true&useSSL=false"
Experiment_JdbcTablePrefix: "discordsrv"
Experiment_JdbcUsername: "censored"
Experiment_JdbcPassword: "censored"
```

```
[03:51:48] [DiscordSRV - Initialization/INFO]: [DiscordSRV] Console channel ID was invalid, not forwarding console output
[03:51:48] [DiscordSRV - Initialization/ERROR]: [DiscordSRV] Not using JDBC because of exception while matching parts of JDBC url: No group with name <protocol>
java.lang.IllegalArgumentException: No group with name <protocol>
	at java.base/java.util.regex.Matcher.getMatchedGroupIndex(Matcher.java:1803)
	at java.base/java.util.regex.Matcher.group(Matcher.java:681)
	at github.scarsz.discordsrv.objects.managers.link.JdbcAccountLinkManager.shouldUseJdbc(JdbcAccountLinkManager.java:90)
	at github.scarsz.discordsrv.objects.managers.link.JdbcAccountLinkManager.shouldUseJdbc(JdbcAccountLinkManager.java:75)
	at github.scarsz.discordsrv.DiscordSRV.init(DiscordSRV.java:1003)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

Edit: Caused by the regex change being improper.

**Comment by Scarsz** [comment]
Fixed, thanks
