### ISSUE TITLE
Cannot invoke "org.bukkit.entity.Player.getName()" because "player" is null

### ISSUE THREAD

**Issue by CloudMc-server** [DiscordSRV/DiscordSRV#1022]
# **Welcome,**
## I setted up a Non-premium Minecraft server and I added DiscordSRV to it. But when a player joined, the avatar image showed classic Alex Skin (even though that player had a skin). In the console, it's showing something like this:

```[10:30:26 WARN]: [DiscordSRV] Plugin DiscordSRV v1.21.3 generated an exception while executing task 116339
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getName()" because "player" is null
at nl.svenar.PowerRanks.api.PowerRanksAPI.getSubranks(PowerRanksAPI.java:158) ~[?:?]
at nl.svenar.PowerRanks.PowerRanksVaultPermission.playerInGroup(PowerRanksVaultPermission.java:182) ~[?:?]
at github.scarsz.discordsrv.objects.managers.GroupSynchronizationManager.resync(GroupSynchronizationManager.java:263) ~[?:?]
at github.scarsz.discordsrv.objects.managers.GroupSynchronizationManager.resync(GroupSynchronizationManager.java:151) ~[?:?]
at github.scarsz.discordsrv.objects.managers.GroupSynchronizationManager.lambda$resync$2(GroupSynchronizationManager.java:129) ~[?:?]
at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
at github.scarsz.discordsrv.objects.managers.GroupSynchronizationManager.resync(GroupSynchronizationManager.java:129) ~[?:?]
at github.scarsz.discordsrv.DiscordSRV.lambda$init$28(DiscordSRV.java:1187) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Paper-457]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-457]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-457]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
at java.lang.Thread.run(Thread.java:832) [?:?]
```

This error isn't annoying, annoying are players that ask "ADMIN, WHY IS MY SKIN NOT SHOWING?"
I use pufferpanel 2.0, can someone help me? Whole server will be very grateful.

**Comment by Vankka** [comment]
getting skins to work is a matter of setting the `AvatarUrl` in the config.yml to `https://minotar.net/helm/{username}/{size}.png#{texture}`. The error I can't read because it isn't properly formatted, please send your log

**Comment by Scarsz** [comment]
Not a DiscordSRV issue

If you're using SkinRestorer, see https://github.com/DiscordSRV/DiscordSRV/issues/996

**Comment by CloudMc-server** [comment]
ooookay, so if i understand correctly, DiscordSRV can't show offline players skulls, because they are offline and their skins are just a alliance overlay. Yes, i use skinRestorer. but i don't know, why skulls of players that HAVE online minecraft, don't show. Is it a problem with SR? If i don't think correctly, i'm sorry im new to this solution.

**Comment by Scarsz** [comment]
It doesn't matter if the person has a premium account. If the server is in offline mode, all player UUIDs will be offline mode UUIDs.

Do what Vankka said about changing your avatar url to use usernames instead of UUIDs.

**Comment by CloudMc-server** [comment]
It's partially working! In most cases, avatars show as skins of people.
