### ISSUE TITLE
Issue on KCauldron/Thermos 1.7.10 after player disconnect

### ISSUE THREAD

**Issue by ChefMC** [DiscordSRV/DiscordSRV#1027]
```
[20:13:03 WARN]: java.lang.NullPointerException
[20:13:03 WARN]:        at github.scarsz.discordsrv.util.NMSUtil.getHandle(NMSUtil.java:100)
[20:13:03 WARN]:        at github.scarsz.discordsrv.util.NMSUtil.getGameProfile(NMSUtil.java:108)
[20:13:03 WARN]:        at github.scarsz.discordsrv.util.NMSUtil.getTexture(NMSUtil.java:137)
[20:13:03 WARN]:        at github.scarsz.discordsrv.DiscordSRV.getAvatarUrl(DiscordSRV.java:1897)
[20:13:03 WARN]:        at github.scarsz.discordsrv.DiscordSRV.sendLeaveMessage(DiscordSRV.java:1697)
[20:13:03 WARN]:        at github.scarsz.discordsrv.listeners.PlayerJoinLeaveListener.lambda$PlayerQuitEvent$3(PlayerJoinLeaveListener.java:133)
[20:13:03 WARN]:        at github.scarsz.discordsrv.listeners.PlayerJoinLeaveListener$$Lambda$311/1698185563.run(Unknown Source)
[20:13:03 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
[20:13:03 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[20:13:03 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[20:13:03 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[20:13:03 WARN]:        at java.lang.Thread.run(Unknown Source)
[20:13:03 WARN]: java.lang.NullPointerException
[20:13:03 WARN]:        at github.scarsz.discordsrv.util.NMSUtil.getTexture(NMSUtil.java:138)
[20:13:03 WARN]:        at github.scarsz.discordsrv.DiscordSRV.getAvatarUrl(DiscordSRV.java:1897)
[20:13:03 WARN]:        at github.scarsz.discordsrv.DiscordSRV.sendLeaveMessage(DiscordSRV.java:1697)
[20:13:03 WARN]:        at github.scarsz.discordsrv.listeners.PlayerJoinLeaveListener.lambda$PlayerQuitEvent$3(PlayerJoinLeaveListener.java:133)
[20:13:03 WARN]:        at github.scarsz.discordsrv.listeners.PlayerJoinLeaveListener$$Lambda$311/1698185563.run(Unknown Source)
[20:13:03 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
[20:13:03 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[20:13:03 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[20:13:03 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[20:13:03 WARN]:        at java.lang.Thread.run(Unknown Source)
```

**Comment by Scarsz** [comment]
Test using snapshots https://snapshot.discordsrv.com

**Comment by iBars** [comment]
After updating crash on leaving server not expecting. I founded some another crashes:

On enable server:
```
[01:20:58] [DiscordSRV - Initialization/INFO]: [DiscordSRV] [JDA] Login Successful!
[01:20:59] [JDA MainWS-WriteThread/INFO]: [DiscordSRV] [JDA] Connected to WebSocket
[01:21:02] [JDA MainWS-ReadThread/INFO]: [DiscordSRV] [JDA] Finished Loading!
[01:21:02] [DiscordSRV - Initialization/INFO]: [DiscordSRV] Console channel ID was invalid, not forwarding console output
[01:21:04] [DiscordSRV - Initialization/ERROR]: [DiscordSRV] Not using JDBC because the JDBC connection string is invalid!
[01:21:04] [DiscordSRV - Initialization/INFO]: [DiscordSRV] Enabling Essentials hook
[01:21:05] [DiscordSRV - Initialization/INFO]: [DiscordSRV] No chat plugin hooks enabled
[01:21:05] [Server thread/WARN]: [DiscordSRV] Task #35 for DiscordSRV v1.22.0-SNAPSHOT generated an exception
java.lang.IllegalStateException: Cannot build a Message with no content. (You never added any content to the message)
	at github.scarsz.discordsrv.dependencies.jda.api.MessageBuilder.build(MessageBuilder.java:1174) ~[?:?]
	at github.scarsz.discordsrv.util.DiscordUtil.queueMessage(DiscordUtil.java:421) ~[?:?]
	at github.scarsz.discordsrv.DiscordSRV.lambda$init$22(DiscordSRV.java:990) ~[?:?]
	at github.scarsz.discordsrv.DiscordSRV$$Lambda$225/1975380094.run(Unknown Source) ~[?:?]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[CraftTask.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346) [CraftScheduler.class:1.7.10-R0.1-SNAPSHOT]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:873) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
```

On disable server:
```
[01:44:40] [DiscordSRV - JDA Rate Limit/ERROR]: [DiscordSRV] [JDA] There was an unexpected error while executing a REST request
java.util.concurrent.RejectedExecutionException
	at java.util.concurrent.ForkJoinPool.externalSubmit(Unknown Source)
	at java.util.concurrent.ForkJoinPool.externalPush(Unknown Source)
	at java.util.concurrent.ForkJoinPool.execute(Unknown Source)
	at github.scarsz.discordsrv.dependencies.jda.api.requests.Request.onSuccess(Request.java:90)
	at github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.handleSuccess(RestActionImpl.java:276)
	at github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.handleResponse(RestActionImpl.java:268)
	at github.scarsz.discordsrv.dependencies.jda.api.requests.Request.handleResponse(Request.java:259)
	at github.scarsz.discordsrv.dependencies.jda.internal.requests.Requester.execute(Requester.java:236)
	at github.scarsz.discordsrv.dependencies.jda.internal.requests.Requester.execute(Requester.java:140)
	at github.scarsz.discordsrv.dependencies.jda.internal.requests.Requester.execute(Requester.java:123)
	at github.scarsz.discordsrv.dependencies.jda.internal.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:468)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

[01:44:40] [Server thread/INFO]: [WorldGuard] Disabling WorldGuard v6.0.0-beta-02
[01:44:40] [Server thread/INFO]: [WorldGuard] Shutting down executor and waiting for any pending tasks...
[01:44:40] [DiscordSRV - JDA Rate Limit/ERROR]: [DiscordSRV] [JDA] Encountered exception trying to execute request
java.lang.IllegalStateException: An error occurred while parsing the response for a RestAction
	at github.scarsz.discordsrv.dependencies.jda.api.requests.Response.<init>(Response.java:76)
	at github.scarsz.discordsrv.dependencies.jda.api.requests.Response.<init>(Response.java:52)
	at github.scarsz.discordsrv.dependencies.jda.internal.requests.Requester.execute(Requester.java:259)
	at github.scarsz.discordsrv.dependencies.jda.internal.requests.Requester.execute(Requester.java:140)
	at github.scarsz.discordsrv.dependencies.jda.internal.requests.Requester.execute(Requester.java:123)
	at github.scarsz.discordsrv.dependencies.jda.internal.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:468)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.InterruptedIOException: interrupted
	at github.scarsz.discordsrv.dependencies.okio.Timeout.throwIfReached(Timeout.java:146)
	at github.scarsz.discordsrv.dependencies.okio.Okio$2.read(Okio.java:137)
	at github.scarsz.discordsrv.dependencies.okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	at github.scarsz.discordsrv.dependencies.okio.RealBufferedSource.read(RealBufferedSource.java:51)
	at github.scarsz.discordsrv.dependencies.okhttp3.internal.http1.Http1Codec$AbstractSource.read(Http1Codec.java:374)
	at github.scarsz.discordsrv.dependencies.okhttp3.internal.http1.Http1Codec$ChunkedSource.read(Http1Codec.java:464)
	at github.scarsz.discordsrv.dependencies.okio.RealBufferedSource$1.read(RealBufferedSource.java:447)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.util.zip.CheckedInputStream.read(Unknown Source)
	at java.util.zip.GZIPInputStream.readUByte(Unknown Source)
	at java.util.zip.GZIPInputStream.readUShort(Unknown Source)
	at java.util.zip.GZIPInputStream.readHeader(Unknown Source)
	at java.util.zip.GZIPInputStream.<init>(Unknown Source)
	at java.util.zip.GZIPInputStream.<init>(Unknown Source)
	at github.scarsz.discordsrv.dependencies.jda.internal.utils.IOUtil.getBody(IOUtil.java:243)
	at github.scarsz.discordsrv.dependencies.jda.api.requests.Response.<init>(Response.java:72)
	... 12 more
```

**Comment by Scarsz** [comment]
> After updating crash on leaving server not expecting. I founded some another crashes:
> 
> On enable server:
> 
> ```
> [01:20:58] [DiscordSRV - Initialization/INFO]: [DiscordSRV] [JDA] Login Successful!
> [01:20:59] [JDA MainWS-WriteThread/INFO]: [DiscordSRV] [JDA] Connected to WebSocket
> [01:21:02] [JDA MainWS-ReadThread/INFO]: [DiscordSRV] [JDA] Finished Loading!
> [01:21:02] [DiscordSRV - Initialization/INFO]: [DiscordSRV] Console channel ID was invalid, not forwarding console output
> [01:21:04] [DiscordSRV - Initialization/ERROR]: [DiscordSRV] Not using JDBC because the JDBC connection string is invalid!
> [01:21:04] [DiscordSRV - Initialization/INFO]: [DiscordSRV] Enabling Essentials hook
> [01:21:05] [DiscordSRV - Initialization/INFO]: [DiscordSRV] No chat plugin hooks enabled
> [01:21:05] [Server thread/WARN]: [DiscordSRV] Task #35 for DiscordSRV v1.22.0-SNAPSHOT generated an exception
> java.lang.IllegalStateException: Cannot build a Message with no content. (You never added any content to the message)
> 	at github.scarsz.discordsrv.dependencies.jda.api.MessageBuilder.build(MessageBuilder.java:1174) ~[?:?]
> 	at github.scarsz.discordsrv.util.DiscordUtil.queueMessage(DiscordUtil.java:421) ~[?:?]
> 	at github.scarsz.discordsrv.DiscordSRV.lambda$init$22(DiscordSRV.java:990) ~[?:?]
> 	at github.scarsz.discordsrv.DiscordSRV$$Lambda$225/1975380094.run(Unknown Source) ~[?:?]
> 	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[CraftTask.class:1.7.10-R0.1-SNAPSHOT]
> 	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346) [CraftScheduler.class:1.7.10-R0.1-SNAPSHOT]
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:873) [MinecraftServer.class:?]
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
> 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
> ```
> 
> On disable server:
> 
> ```
> [01:44:40] [DiscordSRV - JDA Rate Limit/ERROR]: [DiscordSRV] [JDA] There was an unexpected error while executing a REST request
> java.util.concurrent.RejectedExecutionException
> 	at java.util.concurrent.ForkJoinPool.externalSubmit(Unknown Source)
> 	at java.util.concurrent.ForkJoinPool.externalPush(Unknown Source)
> 	at java.util.concurrent.ForkJoinPool.execute(Unknown Source)
> 	at github.scarsz.discordsrv.dependencies.jda.api.requests.Request.onSuccess(Request.java:90)
> 	at github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.handleSuccess(RestActionImpl.java:276)
> 	at github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.handleResponse(RestActionImpl.java:268)
> 	at github.scarsz.discordsrv.dependencies.jda.api.requests.Request.handleResponse(Request.java:259)
> 	at github.scarsz.discordsrv.dependencies.jda.internal.requests.Requester.execute(Requester.java:236)
> 	at github.scarsz.discordsrv.dependencies.jda.internal.requests.Requester.execute(Requester.java:140)
> 	at github.scarsz.discordsrv.dependencies.jda.internal.requests.Requester.execute(Requester.java:123)
> 	at github.scarsz.discordsrv.dependencies.jda.internal.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:468)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
> 	at java.util.concurrent.FutureTask.run(Unknown Source)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at java.lang.Thread.run(Unknown Source)
> 
> [01:44:40] [Server thread/INFO]: [WorldGuard] Disabling WorldGuard v6.0.0-beta-02
> [01:44:40] [Server thread/INFO]: [WorldGuard] Shutting down executor and waiting for any pending tasks...
> [01:44:40] [DiscordSRV - JDA Rate Limit/ERROR]: [DiscordSRV] [JDA] Encountered exception trying to execute request
> java.lang.IllegalStateException: An error occurred while parsing the response for a RestAction
> 	at github.scarsz.discordsrv.dependencies.jda.api.requests.Response.<init>(Response.java:76)
> 	at github.scarsz.discordsrv.dependencies.jda.api.requests.Response.<init>(Response.java:52)
> 	at github.scarsz.discordsrv.dependencies.jda.internal.requests.Requester.execute(Requester.java:259)
> 	at github.scarsz.discordsrv.dependencies.jda.internal.requests.Requester.execute(Requester.java:140)
> 	at github.scarsz.discordsrv.dependencies.jda.internal.requests.Requester.execute(Requester.java:123)
> 	at github.scarsz.discordsrv.dependencies.jda.internal.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:468)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
> 	at java.util.concurrent.FutureTask.run(Unknown Source)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at java.lang.Thread.run(Unknown Source)
> Caused by: java.io.InterruptedIOException: interrupted
> 	at github.scarsz.discordsrv.dependencies.okio.Timeout.throwIfReached(Timeout.java:146)
> 	at github.scarsz.discordsrv.dependencies.okio.Okio$2.read(Okio.java:137)
> 	at github.scarsz.discordsrv.dependencies.okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
> 	at github.scarsz.discordsrv.dependencies.okio.RealBufferedSource.read(RealBufferedSource.java:51)
> 	at github.scarsz.discordsrv.dependencies.okhttp3.internal.http1.Http1Codec$AbstractSource.read(Http1Codec.java:374)
> 	at github.scarsz.discordsrv.dependencies.okhttp3.internal.http1.Http1Codec$ChunkedSource.read(Http1Codec.java:464)
> 	at github.scarsz.discordsrv.dependencies.okio.RealBufferedSource$1.read(RealBufferedSource.java:447)
> 	at java.io.BufferedInputStream.fill(Unknown Source)
> 	at java.io.BufferedInputStream.read(Unknown Source)
> 	at java.util.zip.CheckedInputStream.read(Unknown Source)
> 	at java.util.zip.GZIPInputStream.readUByte(Unknown Source)
> 	at java.util.zip.GZIPInputStream.readUShort(Unknown Source)
> 	at java.util.zip.GZIPInputStream.readHeader(Unknown Source)
> 	at java.util.zip.GZIPInputStream.<init>(Unknown Source)
> 	at java.util.zip.GZIPInputStream.<init>(Unknown Source)
> 	at github.scarsz.discordsrv.dependencies.jda.internal.utils.IOUtil.getBody(IOUtil.java:243)
> 	at github.scarsz.discordsrv.dependencies.jda.api.requests.Response.<init>(Response.java:72)
> 	... 12 more
> ```

First error should be fixed, second is normal albeit a bit unsightly
