### ISSUE TITLE
PremiumVanish PostPlayerHideEvent NullPointerException

### ISSUE THREAD

**Issue by auremarc** [DiscordSRV/DiscordSRV#1032]
>.... [02:48:36 ERROR]: Could not pass event PostPlayerHideEvent to DiscordSRV v1.21.3
java.lang.NullPointerException: null
at github.scarsz.discordsrv.DiscordSRV.translateMessage(DiscordSRV.java:1845) ~[?:?]
at github.scarsz.discordsrv.DiscordSRV.sendLeaveMessage(DiscordSRV.java:1718) ~[?:?]
at de.myzelyam.premiumvanish.bukkit.hooks.DiscordSRVHook.onVanish(DiscordSRVHook.java:24) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor320.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-468]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-468]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-468]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-468]
at de.myzelyam.premiumvanish.bukkit.visibility.VisibilityChanger.hidePlayer(VisibilityChanger.java:157) ~[?:?]
at de.myzelyam.premiumvanish.bukkit.visibility.VisibilityChanger.hidePlayer(VisibilityChanger.java:53) ~[?:?]
at de.myzelyam.premiumvanish.bukkit.visibility.VisibilityChanger.hidePlayer(VisibilityChanger.java:36) ~[?:?]
at de.myzelyam.premiumvanish.bukkit.commands.SubCommand.hidePlayer(SubCommand.java:33) ~[?:?]
at de.myzelyam.premiumvanish.bukkit.commands.subcommands.VanishSelf.execute(VanishSelf.java:25) ~[?:?]
at de.myzelyam.premiumvanish.bukkit.commands.SubCommandMgr.execute(SubCommandMgr.java:79) ~[?:?]
at de.myzelyam.premiumvanish.bukkit.commands.FlexibleCommand.execute(FlexibleCommand.java:63) ~[?:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-468]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:806) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2021) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1832) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1785) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1200) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-468]
at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by Vankka** [comment]
Fixed in development builds - https://snapshot.discordsrv.com
