### ISSUE TITLE
DiscordSRV unable to start after restart of server

### ISSUE THREAD

**Issue by Darlokt** [DiscordSRV/DiscordSRV#1058]
```
[20:22:29 ERROR]: [DiscordSRV] Failed to fetch URL https://raw.githubusercontent.com/DiscordSRV/DiscordSRV/randomaccessfiles/minimumbuild: java.net.SocketException: Network is unreachable
[20:22:29 WARN]: [DiscordSRV] Failed to check against minimum version of DiscordSRV: received minimum build was not 40 characters long & thus not a commit hash
[20:22:29 ERROR]: [DiscordSRV] Failed to fetch URL https://api.github.com/repos/DiscordSRV/DiscordSRV/git/refs/heads/master: java.net.SocketException: Network is unreachable
[20:22:29 INFO]: Running delayed init tasks
[20:22:29 INFO]: Done (10.582s)! For help, type "help"
[20:22:29 INFO]: Timings Reset
[20:22:29 ERROR]: [DiscordSRV] [JDA] There was an I/O error while executing a REST request: Network is unreachable
[20:22:29 ERROR]: [DiscordSRV] An unknown error occurred building JDA...
[20:22:29 ERROR]: [DiscordSRV] github.scarsz.discordsrv.dependencies.jda.api.exceptions.ErrorResponseException: -1: java.net.SocketException
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:227)
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.jda.api.requests.RestAction.complete(RestAction.java:623)
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.jda.api.utils.SessionControllerAdapter.getGateway(SessionControllerAdapter.java:86)
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.jda.internal.JDAImpl.getGateway(JDAImpl.java:298)
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.jda.internal.JDAImpl.login(JDAImpl.java:256)
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.jda.internal.JDAImpl.login(JDAImpl.java:248)
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.jda.api.JDABuilder.build(JDABuilder.java:1929)
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.DiscordSRV.init(DiscordSRV.java:908)
[20:22:29 ERROR]: [DiscordSRV] 	at java.base/java.lang.Thread.run(Thread.java:832)
[20:22:29 ERROR]: [DiscordSRV] Caused by: java.net.SocketException: Network is unreachable
[20:22:29 ERROR]: [DiscordSRV] 	at java.base/sun.nio.ch.Net.connect0(Native Method)
[20:22:29 ERROR]: [DiscordSRV] 	at java.base/sun.nio.ch.Net.connect(Net.java:503)
[20:22:29 ERROR]: [DiscordSRV] 	at java.base/sun.nio.ch.Net.connect(Net.java:492)
[20:22:29 ERROR]: [DiscordSRV] 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
[20:22:29 ERROR]: [DiscordSRV] 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
[20:22:29 ERROR]: [DiscordSRV] 	at java.base/java.net.Socket.connect(Socket.java:648)
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.okhttp3.internal.platform.Platform.connectSocket(Platform.java:128)
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:247)
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.okhttp3.internal.connection.RealConnection.connect(RealConnection.java:167)
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264)
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.okhttp3.RealCall.execute(RealCall.java:93)
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.jda.internal.requests.Requester.execute(Requester.java:200)
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.jda.internal.requests.Requester.execute(Requester.java:251)
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.jda.internal.requests.Requester.execute(Requester.java:140)
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.jda.internal.requests.Requester.execute(Requester.java:123)
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.jda.internal.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:468)
[20:22:29 ERROR]: [DiscordSRV] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[20:22:29 ERROR]: [DiscordSRV] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[20:22:29 ERROR]: [DiscordSRV] 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[20:22:29 ERROR]: [DiscordSRV] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[20:22:29 ERROR]: [DiscordSRV] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[20:22:29 ERROR]: [DiscordSRV] 	... 1 more
[20:22:29 ERROR]: [DiscordSRV] Caused by: github.scarsz.discordsrv.dependencies.jda.api.exceptions.ContextException
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.jda.api.exceptions.ContextException.here(ContextException.java:54)
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.jda.api.requests.Request.<init>(Request.java:71)
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.jda.api.requests.RestFuture.<init>(RestFuture.java:36)
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.submit(RestActionImpl.java:209)
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:219)
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.jda.api.requests.RestAction.complete(RestAction.java:623)
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.jda.api.utils.SessionControllerAdapter.getGateway(SessionControllerAdapter.java:86)
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.jda.internal.JDAImpl.getGateway(JDAImpl.java:298)
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.jda.internal.JDAImpl.login(JDAImpl.java:256)
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.jda.internal.JDAImpl.login(JDAImpl.java:248)
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.jda.api.JDABuilder.build(JDABuilder.java:1929)
[20:22:29 ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.DiscordSRV.init(DiscordSRV.java:908)
[20:22:29 ERROR]: [DiscordSRV] 	... 1 more
```

**Comment by Scarsz** [comment]
Server's internet is failing, not a problem with DiscordSRV
