### ISSUE TITLE
Username with space causing DiscordSrv exceptions

### ISSUE THREAD

**Issue by pwlgrzs** [DiscordSRV/DiscordSRV#1062]
Some launchers allow nicknames with spaces (like TLauncher). Space is causing following exception on any Discord related task:

[17:24:06] [Craft Scheduler Thread - 49/WARN]: [DiscordSRV] Plugin DiscordSRV v1.21.3 generated an exception while executing task 37533
java.lang.IllegalArgumentException: URL must be a valid http(s) or attachment url.
	at github.scarsz.discordsrv.dependencies.jda.internal.utils.Checks.check(Checks.java:43) ~[?:?]
	at github.scarsz.discordsrv.dependencies.jda.api.EmbedBuilder.urlCheck(EmbedBuilder.java:832) ~[?:?]
	at github.scarsz.discordsrv.dependencies.jda.api.EmbedBuilder.setAuthor(EmbedBuilder.java:654) ~[?:?]
	at github.scarsz.discordsrv.DiscordSRV.translateMessage(DiscordSRV.java:1849) ~[?:?]
	at github.scarsz.discordsrv.DiscordSRV.sendJoinMessage(DiscordSRV.java:1661) ~[?:?]
	at github.scarsz.discordsrv.listeners.PlayerJoinLeaveListener.lambda$onPlayerJoin$1(PlayerJoinLeaveListener.java:97) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-570]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-570]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-570]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]

Is there anyworkaround possible?

**Comment by Vankka** [comment]
Fixed in latest development build - https://snapshot.discordsrv.com
