### ISSUE TITLE
[bug] java.lang.NoSuchMethodError: us.myles.ViaVersion.api.data.UserConnection.getProtocolInfo()

### ISSUE THREAD

**Issue by noahmanscher** [DiscordSRV/DiscordSRV#1091]
Just updated to v1.22.0. Getting this error on player join:

```
java.lang.NoSuchMethodError: us.myles.ViaVersion.api.data.UserConnection.getProtocolInfo()Lus/myles/ViaVersion/protocols/base/ProtocolInfo;
        at github.scarsz.discordsrv.dependencies.kyori.adventure.platform.viaversion.ViaFacet.findProtocol(ViaFacet.java:102) ~[?:?]
        at github.scarsz.discordsrv.dependencies.kyori.adventure.platform.viaversion.ViaFacet.isApplicable(ViaFacet.java:92) ~[?:?]
        at github.scarsz.discordsrv.dependencies.kyori.adventure.platform.facet.Facet.of(Facet.java:100) ~[?:?]
        at github.scarsz.discordsrv.dependencies.kyori.adventure.platform.facet.FacetAudience.<init>(FacetAudience.java:109) ~[?:?]
        at github.scarsz.discordsrv.dependencies.kyori.adventure.platform.bukkit.BukkitAudience.<init>(BukkitAudience.java:85) ~[?:?]
        at github.scarsz.discordsrv.dependencies.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.createAudience(BukkitAudiencesImpl.java:162) ~[?:?]
        at github.scarsz.discordsrv.dependencies.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.createAudience(BukkitAudiencesImpl.java:71) ~[?:?]
        at github.scarsz.discordsrv.dependencies.kyori.adventure.platform.facet.FacetAudienceProvider.lambda$addViewer$0(FacetAudienceProvider.java:89) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[?:1.8.0_282]
        at github.scarsz.discordsrv.dependencies.kyori.adventure.platform.facet.FacetAudienceProvider.addViewer(FacetAudienceProvider.java:88) ~[?:?]
        at github.scarsz.discordsrv.dependencies.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.lambda$new$3(BukkitAudiencesImpl.java:101) ~[?:?]
        at github.scarsz.discordsrv.dependencies.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.lambda$registerEvent$5(BukkitAudiencesImpl.java:215) ~[?:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[server.jar:git-TacoSpigot-04511af6]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-TacoSpigot-04511af6]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:508) [server.jar:git-TacoSpigot-04511af6]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:493) [server.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:318) [server.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:176) [server.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) [server.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [server.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:232) [server.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [server.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:1101) [server.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:891) [server.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:785) [server.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:684) [server.jar:git-TacoSpigot-04511af6]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
```

If the solution is "Update ViaVersion", I can't do that. We're using a custom version to patch a Spigot block placement block. In this case, could there just be added a try block or something like that?

**Comment by Vankka** [comment]
The solution indeed is updating ViaVersion, you should probably look into getting that patch made for a newer version of ViaVersion. This will happen when DiscordSRV is sending any message to a in-game player, not something to just be try catched.
