### ISSUE TITLE
One of the EventListeners had an uncaught exception java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by mrfloris** [DiscordSRV/DiscordSRV#1133]
did a /stop, then Updated from snapshot just now, and updated paper jar, noticed on starting the server there was an error, thought i'd report it
```
> broadcast Maintenance mode is enabled
[21:02:52 INFO]: [Broadcast] Maintenance mode is enabled
[21:03:08 ERROR]: [DiscordSRV] [JDA] One of the EventListeners had an uncaught exception
java.lang.UnsupportedOperationException
        at java.base/java.util.Collections$1.remove(Collections.java:4787)
        at java.base/java.util.AbstractCollection.remove(AbstractCollection.java:283)
        at github.scarsz.discordsrv.dependencies.mcdiscordreserializer.renderer.MinecraftRenderer.render(MinecraftRenderer.java:69)
        at github.scarsz.discordsrv.dependencies.mcdiscordreserializer.minecraft.MinecraftSerializer.addChild(MinecraftSerializer.java:125)
        at github.scarsz.discordsrv.dependencies.mcdiscordreserializer.minecraft.MinecraftSerializer.serialize(MinecraftSerializer.java:112)
        at github.scarsz.discordsrv.dependencies.mcdiscordreserializer.minecraft.MinecraftSerializer.serialize(MinecraftSerializer.java:94)
        at github.scarsz.discordsrv.util.MessageUtil.reserializeToMinecraft(MessageUtil.java:211)
        at github.scarsz.discordsrv.util.MessageUtil.reserializeToMinecraftBasedOnConfig(MessageUtil.java:196)
        at github.scarsz.discordsrv.listeners.DiscordChatListener.onGuildMessageReceived(DiscordChatListener.java:183)
        at github.scarsz.discordsrv.dependencies.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:445)
        at github.scarsz.discordsrv.dependencies.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
        at github.scarsz.discordsrv.dependencies.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
        at github.scarsz.discordsrv.dependencies.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
        at github.scarsz.discordsrv.dependencies.jda.internal.JDAImpl.handleEvent(JDAImpl.java:151)
        at github.scarsz.discordsrv.dependencies.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:97)
        at github.scarsz.discordsrv.dependencies.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
        at github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952)
        at github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839)
        at github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817)
        at github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:990)
        at github.scarsz.discordsrv.dependencies.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
        at github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
        at github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
        at github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
        at github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.main(ReadingThread.java:108)
        at github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.runMain(ReadingThread.java:64)
        at github.scarsz.discordsrv.dependencies.ws.client.WebSocketThread.run(WebSocketThread.java:45)

> ver DiscordSRV
[21:03:57 INFO]: DiscordSRV version 1.23.0-SNAPSHOT
[21:03:57 INFO]: The most powerful, configurable, open-source Discord bridge plugin out there.
[21:03:57 INFO]: Website: https://github.com/DiscordSRV/DiscordSRV
[21:03:57 INFO]: Authors: Scarsz, Androkai and Vankka
> ver
[21:03:58 INFO]: Checking version, please wait...
[21:03:58 INFO]: This server is running Paper version git-Paper-720 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-715 (MC: 1.16.5)
>
```

**Comment by Vankka** [comment]
This should be fixed on the latest snapshot - https://snapshot.discordsrv.com & I believe it happened because a code block was sent in one of the linked Discord channels
