### ISSUE TITLE
An unknown error occurred building JDA

### ISSUE THREAD

**Issue by fioletovayasherstb** [DiscordSRV/DiscordSRV#1134]
(I am writing via google translator) hello, I have a problem, after installing the plugin for hosting on mohist, the plugin stopped working on the following error
 [00:11:42 ERROR]: [DiscordSRV] [JDA] There was an I/O error while executing a REST request: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
 [00:11:43 ERROR]: [DiscordSRV] An unknown error occurred building JDA...
 [00:11:43 ERROR]: [DiscordSRV] github.scarsz.discordsrv.dependencies.jda.api.exceptions.ErrorResponseException: -1: javax.net.ssl.SSLException
 [00:11:43 ERROR]: [DiscordSRV] at github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:227)
 [00:11:43 ERROR]: [DiscordSRV] at github.scarsz.discordsrv.dependencies.jda.api.requests.RestAction.complete(RestAction.java:623)
 [00:11:43 ERROR]: [DiscordSRV] at github.scarsz.discordsrv.dependencies.jda.api.utils.SessionControllerAdapter.getGateway(SessionControllerAdapter.java:86)
 [00:11:43 ERROR]: [DiscordSRV] at github.scarsz.discordsrv.dependencies.jda.internal.JDAImpl.getGateway(JDAImpl.java:298)
 [00:11:43 ERROR]: [DiscordSRV] at github.scarsz.discordsrv.dependencies.jda.internal.JDAImpl.login(JDAImpl.java:256)
 [00:11:43 ERROR]: [DiscordSRV] at github.scarsz.discordsrv.dependencies.jda.internal.JDAImpl.login(JDAImpl.java:248)
 [00:11:43 ERROR]: [DiscordSRV] at github.scarsz.discordsrv.dependencies.jda.api.JDABuilder.build(JDABuilder.java:1929)
 [00:11:43 ERROR]: [DiscordSRV] at github.scarsz.discordsrv.DiscordSRV.init(DiscordSRV.java:908)
 [00:11:43 ERROR]: [DiscordSRV] at java.base/java.lang.Thread.run(Thread.java:834)
 [00:11:43 ERROR]: [DiscordSRV] Caused by: javax.net.ssl.SSLException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
 [00:11:43 ERROR]: [DiscordSRV] at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)
 [00:11:43 ERROR]: [DiscordSRV] at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:320)
 [00:11:43 ERROR]: [DiscordSRV] at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:263)
 [00:11:43 ERROR]: [DiscordSRV] at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:258)
 [00:11:43 ERROR]: [DiscordSRV] at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1314)
 [00:11:43 ERROR]: [DiscordSRV] at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:408)
 [00:11:43 ERROR]: [DiscordSRV] at github.scarsz.discordsrv.dependencies.okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:320)
 [00:11:43 ERROR]: [DiscordSRV] at github.scarsz.discordsrv.dependencies.okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:284)
 [00:11:43 ERROR]: [DiscordSRV] at github.scarsz.discordsrv.dependencies.okhttp3.internal.connection.RealConnection.connect(RealConnection.java:169)
 [00:11:43 ERROR]: [DiscordSRV] at github.scarsz.discordsrv.dependencies.okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
 [00:11:43 ERROR]: [DiscordSRV] at github.scarsz.discordsrv.dependencies.okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
 [00:11:43 ERROR]: [DiscordSRV] at github.scarsz.discordsrv.dependencies.okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
 [00:11:43 ERROR]: [DiscordSRV] at github.scarsz.discordsrv.dependencies.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
 [00:11:43 ERROR]: [DiscordSRV] at github.scarsz.discordsrv.dependencies.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
 [00:11:43 ERROR]: [DiscordSRV] at github.scarsz.discordsrv.dependencies.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
 [00:11:43 ERROR]: [DiscordSRV] at github.scarsz.discordsrv.dependencies.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
 [00:11:43 ERROR]: [DiscordSRV] at github.scarsz.discordsrv.dependencies.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
 [00:11:43 ERROR]: [DiscordSRV] at github.scarsz.discordsrv.dependencies.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
 [00:11:43 ERROR]: [DiscordSRV] at github.scarsz.discordsrv.dependencies.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
 [00:11:43 ERROR]: [DiscordSRV] at github.scarsz.discordsrv.dependencies.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
 [00:11:43 ERROR]: [DiscordSRV] at github.scarsz.discordsrv.dependencies.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
 [00:11:43 ERROR]: [DiscordSRV] at github.scarsz.discordsrv.dependencies.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
 [00:11:43 ERROR]: [DiscordSRV] at github.scarsz.discordsrv.dependencies.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
 [00:11:43 ERROR]: [DiscordSRV] at github.scarsz.discordsrv.dependencies.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264)
 [00:11:43 ERROR]: [DiscordSRV] at github.scarsz.discordsrv.dependencies.okhttp3.RealCall.execute(RealCall.java:93)
 [00:11:43 ERROR]: [DiscordSRV] at github.scarsz.discordsrv.dependencies.jda.internal.requests.Requester.execute(Requester.java:200)
 [00:11:43 ERROR]: [DiscordSRV] at github.scarsz.discordsrv.dependencies.jda.internal.requests.Requester.execute(Requester.java:140)
 [00:11:43 ERROR]: [DiscordSRV] at github.scarsz.discordsrv.dependencies.jda.internal.requests.Requester.execute(Requester.java:123)
 [00:11:43 ERROR]: [DiscordSRV] at github.scarsz.discordsrv.dependencies.jda.internal.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:478)
 [00:11:43 ERROR]: [DiscordSRV] at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
 [00:11:43 ERROR]: [DiscordSRV] at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 [00:11:43 ERROR]: [DiscordSRV] at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
 [00:11:43 ERROR]: [DiscordSRV] at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 [00:11:43 ERROR]: [DiscordSRV] at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 [00:11:43 ERROR]: [DiscordSRV] ... 1 more
 [00:11:43 ERROR]: [DiscordSRV] Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
 [00:11:43 ERROR]: [DiscordSRV] at java.base/sun.security.validator.PKIXValidator.(PKIXValidator.java:89)
 [00:11:43 ERROR]: [DiscordSRV] at java.base/sun.security.validator.Validator.getInstance(Validator.java:181)
 [00:11:43 ERROR]: [DiscordSRV] at java.base/sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:300)
 [00:11:43 ERROR]: [DiscordSRV] at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:176)
 [00:11:43 ERROR]: [DiscordSRV] at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:189)
 [00:11:43 ERROR]: [DiscordSRV] at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
 [00:11:43 ERROR]: [DiscordSRV] at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1308)
 [00:11:43 ERROR]: [DiscordSRV] at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1199)
 [00:11:43 ERROR]: [DiscordSRV] at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1146)
 [00:11:43 ERROR]: [DiscordSRV] at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
 [00:11:43 ERROR]: [DiscordSRV] at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
 [00:11:43 ERROR]: [DiscordSRV] at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
 [00:11:43 ERROR]: [DiscordSRV] at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:177)
 [00:11:43 ERROR]: [DiscordSRV] at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
 [00:11:43 ERROR]: [DiscordSRV] at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
 [00:11:43 ERROR]: [DiscordSRV] at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
 [00:11:43 ERROR]: [DiscordSRV] at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
 [00:11:43 ERROR]: [DiscordSRV] ... 29 more
 [00:11:43 ERROR]: [DiscordSRV] Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
 [00:11:43 ERROR]: [DiscordSRV] at java.base/java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
 [00:11:43 ERROR]: [DiscordSRV] at java.base/java.security.cert.PKIXParameters.(PKIXParameters.java:120)
 [00:11:43 ERROR]: [DiscordSRV] at java.base/java.security.cert.PKIXBuilderParameters.(PKIXBuilderParameters.java:104)
 [00:11:43 ERROR]: [DiscordSRV] at java.base/sun.security.validator.PKIXValidator.(PKIXValidator.java:86)
 [00:11:43 ERROR]: [DiscordSRV] ... 45 more
 [00:11:43 ERROR]: [DiscordSRV] Caused by: github.scarsz.discordsrv.dependencies.jda.api.exceptions.ContextException
 [00:11:43 ERROR]: [DiscordSRV] at github.scarsz.discordsrv.dependencies.jda.api.exceptions.ContextException.here(ContextException.java:54)
 [00:11:43 ERROR]: [DiscordSRV] at github.scarsz.discordsrv.dependencies.jda.api.requests.Request.(Request.java:71)
 [00:11:43 ERROR]: [DiscordSRV] at github.scarsz.discordsrv.dependencies.jda.api.requests.RestFuture.(RestFuture.java:36)
 [00:11:43 ERROR]: [DiscordSRV] at github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.submit(RestActionImpl.java:209)
 [00:11:43 ERROR]: [DiscordSRV] at github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:219)
 [00:11:43 ERROR]: [DiscordSRV] at github.scarsz.discordsrv.dependencies.jda.api.requests.RestAction.complete(RestAction.java:623)
 [00:11:43 ERROR]: [DiscordSRV] at github.scarsz.discordsrv.dependencies.jda.api.utils.SessionControllerAdapter.getGateway(SessionControllerAdapter.java:86)
 [00:11:43 ERROR]: [DiscordSRV] at github.scarsz.discordsrv.dependencies.jda.internal.JDAImpl.getGateway(JDAImpl.java:298)
 [00:11:43 ERROR]: [DiscordSRV] at github.scarsz.discordsrv.dependencies.jda.internal.JDAImpl.login(JDAImpl.java:256)
 [00:11:43 ERROR]: [DiscordSRV] at github.scarsz.discordsrv.dependencies.jda.internal.JDAImpl.login(JDAImpl.java:248)
 [00:11:43 ERROR]: [DiscordSRV] at github.scarsz.discordsrv.dependencies.jda.api.JDABuilder.build(JDABuilder.java:1929)
 [00:11:43 ERROR]: [DiscordSRV] at github.scarsz.discordsrv.DiscordSRV.init(DiscordSRV.java:908)
 [00:11:43 ERROR]: [DiscordSRV] ... 1 more

**Comment by Scarsz** [comment]
You have a misconfigured or outdated version of Java
