### ISSUE TITLE
DiscordSRV Displays Error on User Login us.myles.ViaVersion.api.Via.getManager() no longer exists in ViaVersion 4.0

### ISSUE THREAD

**Issue by StrawberryOG** [DiscordSRV/DiscordSRV#1153]
Error whenever anyone logs in while using ViaVersion 4.0 = https://www.spigotmc.org/resources/viaversion.19254/

```
[17:56:42] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to DiscordSRV v1.22.0
java.lang.NoSuchMethodError: 'us.myles.ViaVersion.ViaManager us.myles.ViaVersion.api.Via.getManager()'
	at github.scarsz.discordsrv.dependencies.kyori.adventure.platform.bukkit.BukkitFacet$ViaHook.apply(BukkitFacet.java:347) ~[?:?]
	at github.scarsz.discordsrv.dependencies.kyori.adventure.platform.bukkit.BukkitFacet$ViaHook.apply(BukkitFacet.java:344) ~[?:?]
	at github.scarsz.discordsrv.dependencies.kyori.adventure.platform.viaversion.ViaFacet.findConnection(ViaFacet.java:96) ~[?:?]
	at github.scarsz.discordsrv.dependencies.kyori.adventure.platform.viaversion.ViaFacet.findProtocol(ViaFacet.java:100) ~[?:?]
	at github.scarsz.discordsrv.dependencies.kyori.adventure.platform.viaversion.ViaFacet.isApplicable(ViaFacet.java:92) ~[?:?]
	at github.scarsz.discordsrv.dependencies.kyori.adventure.platform.facet.Facet.of(Facet.java:100) ~[?:?]
	at github.scarsz.discordsrv.dependencies.kyori.adventure.platform.facet.FacetAudience.<init>(FacetAudience.java:109) ~[?:?]
	at github.scarsz.discordsrv.dependencies.kyori.adventure.platform.bukkit.BukkitAudience.<init>(BukkitAudience.java:85) ~[?:?]
	at github.scarsz.discordsrv.dependencies.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.createAudience(BukkitAudiencesImpl.java:162) ~[?:?]
	at github.scarsz.discordsrv.dependencies.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.createAudience(BukkitAudiencesImpl.java:71) ~[?:?]
	at github.scarsz.discordsrv.dependencies.kyori.adventure.platform.facet.FacetAudienceProvider.lambda$addViewer$0(FacetAudienceProvider.java:89) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705) ~[?:?]
	at github.scarsz.discordsrv.dependencies.kyori.adventure.platform.facet.FacetAudienceProvider.addViewer(FacetAudienceProvider.java:88) ~[?:?]
	at github.scarsz.discordsrv.dependencies.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.lambda$new$3(BukkitAudiencesImpl.java:101) ~[?:?]
	at github.scarsz.discordsrv.dependencies.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.lambda$registerEvent$5(BukkitAudiencesImpl.java:215) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-653]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-653]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-653]
	at net.minecraft.server.v1_13_R2.PlayerList.onPlayerJoin(PlayerList.java:369) ~[patched_1.13.2.jar:git-Paper-653]
	at net.minecraft.server.v1_13_R2.PlayerList.a(PlayerList.java:180) ~[patched_1.13.2.jar:git-Paper-653]
	at net.minecraft.server.v1_13_R2.LoginListener.b(LoginListener.java:169) ~[patched_1.13.2.jar:git-Paper-653]
	at net.minecraft.server.v1_13_R2.LoginListener.tick(LoginListener.java:65) ~[patched_1.13.2.jar:git-Paper-653]
	at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:271) ~[patched_1.13.2.jar:git-Paper-653]
	at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:129) ~[patched_1.13.2.jar:git-Paper-653]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1132) ~[patched_1.13.2.jar:git-Paper-653]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-653]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-653]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-653]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by Vankka** [comment]
This is fixed on latest development builds - https://snapshot.discordsrv.com & will be fixed on the next release
