### ISSUE TITLE
Version 1.17 bring us some little issue when someone write to chat :3

### ISSUE THREAD

**Issue by CloudeLecaw** [DiscordSRV/DiscordSRV#1157]
```
[09:12:22] [Craft Scheduler Thread - 10/WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.EntityPlayer
[09:12:22] [Craft Scheduler Thread - 10/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:140)
[09:12:22] [Craft Scheduler Thread - 10/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
[09:12:22] [Craft Scheduler Thread - 10/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[09:12:22] [Craft Scheduler Thread - 10/WARN]: 	at github.scarsz.discordsrv.util.NMSUtil.fixBukkitClass(NMSUtil.java:108)
[09:12:22] [Craft Scheduler Thread - 10/WARN]: 	at github.scarsz.discordsrv.util.NMSUtil.<clinit>(NMSUtil.java:61)
[09:12:22] [Craft Scheduler Thread - 10/WARN]: 	at github.scarsz.discordsrv.DiscordSRV.getAvatarUrl(DiscordSRV.java:2069)
[09:12:22] [Craft Scheduler Thread - 10/WARN]: 	at github.scarsz.discordsrv.DiscordSRV.sendJoinMessage(DiscordSRV.java:1808)
[09:12:22] [Craft Scheduler Thread - 10/WARN]: 	at github.scarsz.discordsrv.listeners.PlayerJoinLeaveListener.lambda$onPlayerJoin$1(PlayerJoinLeaveListener.java:94)
[09:12:22] [Craft Scheduler Thread - 10/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:81)
[09:12:22] [Craft Scheduler Thread - 10/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[09:12:22] [Craft Scheduler Thread - 10/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[09:12:22] [Craft Scheduler Thread - 10/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[09:12:22] [Craft Scheduler Thread - 10/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by Scarsz** [comment]
Has been fixed in development builds
