### ISSUE TITLE
some kind of error 1.17

### ISSUE THREAD

**Issue by rkfsociety** [DiscordSRV/DiscordSRV#1164]
[02:49:20] [DiscordSRV - Initialization/ERROR]: [DiscordSRV] java.lang.NoSuchMethodError: org.apache.logging.slf4j.Log4jLoggerFactory: method 'void <init>()' not found

[02:49:20] [DiscordSRV - Initialization/ERROR]: [DiscordSRV] 	at org.slf4j.impl.StaticLoggerBinder.<init>(StaticLoggerBinder.java:53)

[02:49:20] [DiscordSRV - Initialization/ERROR]: [DiscordSRV] 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:41)

[02:49:20] [DiscordSRV - Initialization/ERROR]: [DiscordSRV] 	at java.base/java.lang.Class.forName0(Native Method)

[02:49:20] [DiscordSRV - Initialization/ERROR]: [DiscordSRV] 	at java.base/java.lang.Class.forName(Class.java:375)

[02:49:20] [DiscordSRV - Initialization/ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.jda.internal.utils.JDALogger.<clinit>(JDALogger.java:49)

[02:49:20] [DiscordSRV - Initialization/ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.<clinit>(RestActionImpl.java:44)

[02:49:20] [DiscordSRV - Initialization/ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.dependencies.jda.api.requests.restaction.MessageAction.setDefaultMentions(MessageAction.java:113)

[02:49:20] [DiscordSRV - Initialization/ERROR]: [DiscordSRV] 	at github.scarsz.discordsrv.DiscordSRV.init(DiscordSRV.java:622)

[02:49:20] [DiscordSRV - Initialization/ERROR]: [DiscordSRV] 	at java.base/java.lang.Thread.run(Thread.java:831)

Paper version git-Paper-"770bcf3" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) Error obtaining version information Previous version: git-Paper-"3740db0" (MC: 1.17)

**Comment by Vankka** [comment]
One of the Paper devs just noted that this should be fixed on their next build.
