### ISSUE TITLE
Issue with console logs being clogged up

### ISSUE THREAD

**Issue by XoCassie** [DiscordSRV/DiscordSRV#1190]
I'm having an issue with the console logs being clogged up by debugs. If anyone could help me that would be great!
This happens in the console logs every time someone from Minecraft sends a message. 

[Wed, 7. Jul 2021 15:38:32 GMT INFO] [DEBUG] Chat message received, canceled: false, channel: global
[Wed, 7. Jul 2021 15:38:32 GMT INFO] [DEBUG] Failed to look up group for player Xo_Cassie: SuperPerms no group permissions.
java.lang.UnsupportedOperationException: SuperPerms no group permissions.
    at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPrimaryGroup(Permission_SuperPerms.java:96)
    at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:679)
    at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:691)
    at github.scarsz.discordsrv.hooks.VaultHook.getPrimaryGroup(VaultHook.java:54)
    at github.scarsz.discordsrv.DiscordSRV.processChatMessage(DiscordSRV.java:1656)
    at github.scarsz.discordsrv.DiscordSRV.processChatMessage(DiscordSRV.java:1592)
    at github.scarsz.discordsrv.listeners.PlayerChatListener.lambda$onAsyncPlayerChat$0(PlayerChatListener.java:43)
    at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100)
    at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
    at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
    at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by ANutley** [comment]
Disable debug mode in config.yml.

**Comment by XoCassie** [comment]
> Disable debug mode in config.yml.

Wouldn't that stop us from seeing anything that may be important? I'm new to all of this so any help or explanation would be great.

**Comment by Dinty1** [comment]
No, debug messages are only useful when trying to find issues with the plugin. Disabling it doesn't do any harm

**Comment by XoCassie** [comment]
> No, debug messages are only useful when trying to find issues with the plugin. Disabling it doesn't do any harm

Okay thank you guys for the help!
