### ISSUE TITLE
Error after server crash

### ISSUE THREAD

**Issue by BazZziliuS** [DiscordSRV/DiscordSRV#1228]
Server version 1.17.1
bukkit core latest version

[Server thread/ERROR]: Error occurred while enabling DiscordSRV v1.23.0 (Is it up to date?)
java.util.NoSuchElementException: null 'root' premature end of path *root*
at github.scarsz.discordsrv.dependencies.alexh.weak.DynamicNothing.asObject(DynamicNothing.java:36) ~[?:?]
at github.scarsz.discordsrv.dependencies.alexh.weak.Dynamic.as(Dynamic.java:182) ~[?:?]
at github.scarsz.discordsrv.dependencies.alexh.weak.Weak.asMap(Weak.java:83) ~[?:?]
at github.scarsz.discordsrv.util.ConfigUtil.logMissingOptions(ConfigUtil.java:175) ~[?:?]
at github.scarsz.discordsrv.DiscordSRV.onEnable(DiscordSRV.java:443) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[server.jar:3215-Bukkit-c30e8f8]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[server.jar:3215-Bukkit-c30e8f8]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[server.jar:3215-Bukkit-c30e8f8]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:491) ~[server.jar:3215-Bukkit-c30e8f8]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:417) ~[server.jar:3215-Bukkit-c30e8f8]
at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:594) ~[server.jar:3215-Bukkit-c30e8f8]
at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:253) ~[server.jar:3215-Bukkit-c30e8f8]
at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:972) ~[server.jar:3215-Bukkit-c30e8f8]
at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293) ~[server.jar:3215-Bukkit-c30e8f8]
at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by Dinty1** [comment]
Join the support server for support https://discord.discordsrv.com
