### ISSUE TITLE
Plugin dosen't load

### ISSUE THREAD

**Issue by Miki200v2** [DiscordSRV/DiscordSRV#1244]
As in the title, the plugin does not load, there is some information thrown in the console but i don't know what else may be an issue as i fixed the thing the console was throwing an error about, the thing it throws is in the codebox below.
`[23:49:52 ERROR]: Could not load 'plugins\DiscordSRV-Build-1.23.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.RuntimeException: Failed to load config
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:141) ~[patched_1.16.4.jar:git-Paper-348]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.16.4.jar:git-Paper-348]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.16.4.jar:git-Paper-348]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:389) ~[patched_1.16.4.jar:git-Paper-348]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:206) ~[patched_1.16.4.jar:git-Paper-348]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936) ~[patched_1.16.4.jar:git-Paper-348]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-348]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]
Caused by: java.lang.RuntimeException: Failed to load config
        at github.scarsz.discordsrv.DiscordSRV.<init>(DiscordSRV.java:398) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_301]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_301]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_301]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_301]
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_301]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:91) ~[patched_1.16.4.jar:git-Paper-348]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.16.4.jar:git-Paper-348]
        ... 7 more
Caused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning for the next token
found character '`' that cannot start any token. (Do not use ` for indentation)
 in 'string', line 57, column 146:
     ...  ponownie połączyć swoje konta."```
                                         ^

        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:419) ~[patched_1.16.4.jar:git-Paper-348]
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227) ~[patched_1.16.4.jar:git-Paper-348]
        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558) ~[patched_1.16.4.jar:git-Paper-348]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[patched_1.16.4.jar:git-Paper-348]
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) ~[patched_1.16.4.jar:git-Paper-348]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:235) ~[patched_1.16.4.jar:git-Paper-348]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162) ~[patched_1.16.4.jar:git-Paper-348]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:257) ~[patched_1.16.4.jar:git-Paper-348]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:248) ~[patched_1.16.4.jar:git-Paper-348]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:236) ~[patched_1.16.4.jar:git-Paper-348]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162) ~[patched_1.16.4.jar:git-Paper-348]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:257) ~[patched_1.16.4.jar:git-Paper-348]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:248) ~[patched_1.16.4.jar:git-Paper-348]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:236) ~[patched_1.16.4.jar:git-Paper-348]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162) ~[patched_1.16.4.jar:git-Paper-348]
        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:95) ~[patched_1.16.4.jar:git-Paper-348]
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:119) ~[patched_1.16.4.jar:git-Paper-348]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:150) ~[patched_1.16.4.jar:git-Paper-348]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:472) ~[patched_1.16.4.jar:git-Paper-348]
        at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:452) ~[patched_1.16.4.jar:git-Paper-348]
        at github.scarsz.configuralize.Provider.load(Provider.java:28) ~[?:?]
        at github.scarsz.configuralize.Provider.loadResource(Provider.java:62) ~[?:?]
        at github.scarsz.configuralize.Provider.load(Provider.java:51) ~[?:?]
        at github.scarsz.configuralize.DynamicConfig.loadAll(DynamicConfig.java:96) ~[?:?]
        at github.scarsz.discordsrv.DiscordSRV.<init>(DiscordSRV.java:396) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_301]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_301]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_301]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_301]
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_301]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:91) ~[patched_1.16.4.jar:git-Paper-348]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.16.4.jar:git-Paper-348]
        ... 7 more`

**Comment by Scarsz** [comment]
There's a pug that the Polish linking.yml has "\`\`\`" at the end of the file. Remove that file and restart the server.
