### ISSUE TITLE
[1.7.10] Plugin doesn't load, console throws error

### ISSUE THREAD

**Issue by Khazoda** [DiscordSRV/DiscordSRV#1299]
### Expected behavior

The spigot page lists 1.7 as a supported Minecraft version, indicating that the plugin should work on 1.7.10 servers.

### Actual behavior

The plugin isn't loaded and the console throws an error:

`[14:17:44] [Server thread/ERROR]: Could not load 'plugins\DiscordSRV-Build-1.24.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Cannot find main class `github.scarsz.discordsrv.DiscordSRV'
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:191) ~[PluginClassLoader.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[JavaPluginLoader.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334) ~[SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:256) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:320) [CraftServer.class:1.7.10-R0.1-SNAPSHOT]
	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:461) [ayq.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:174) [ayq.class:?]
	at net.minecraft.world.World.<init>(World.java:360) [ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:160) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:367) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_311]
Caused by: java.lang.ClassNotFoundException: Failed to remap class github.scarsz.discordsrv.DiscordSRV
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:488) ~[PluginClassLoader.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:409) ~[PluginClassLoader.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:1.7.10-R0.1-SNAPSHOT]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_311]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_311]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_311]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_311]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:189) ~[PluginClassLoader.class:1.7.10-R0.1-SNAPSHOT]
	... 12 more
Caused by: java.lang.IllegalArgumentException: INVOKESPECIAL/STATIC on interfaces require ASM 5
	at org.objectweb.asm.MethodVisitor.visitMethodInsn(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.ClassReader.a(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.ClassReader.b(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:246) ~[JarRemapper.class:?]
	at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:232) ~[JarRemapper.class:?]
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:453) ~[PluginClassLoader.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:409) ~[PluginClassLoader.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:1.7.10-R0.1-SNAPSHOT]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_311]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_311]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_311]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_311]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:189) ~[PluginClassLoader.class:1.7.10-R0.1-SNAPSHOT]
	... 12 more`

### Steps to reproduce

add plugin to plugins directory and start server

### Server software and version

Latest KCauldron 1.7.10

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

**Comment by Vankka** [comment]
You need ASM 5 to use DiscordSRV, you can view instructions for updating ASM here: https://docs.discordsrv.com/FAQ/#the-plugin-crashes-at-serverstart
