### ISSUE TITLE
Alerts error

### ISSUE THREAD

**Issue by TheWylot** [DiscordSRV/DiscordSRV#1417]
### Expected behavior

i didnt do anything, just plugin spam this error with an interval

### Actual behavior

some message and logs dont say idk why

### Steps to reproduce

[16:40:19 WARN]: [DiscordSRV] Plugin DiscordSRV v1.25.1 generated an exception while executing task 144006402
java.lang.IllegalArgumentException: character to be escaped is missing
        at java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1019) ~[?:?]
        at java.util.regex.Matcher.appendReplacement(Matcher.java:907) ~[?:?]
        at github.scarsz.discordsrv.util.NamedValueFormatter.format(NamedValueFormatter.java:57) ~[DiscordSRV-Build-1.25.1.jar:?]
        at github.scarsz.discordsrv.util.NamedValueFormatter.formatExpressions(NamedValueFormatter.java:92) ~[DiscordSRV-Build-1.25.1.jar:?]
        at github.scarsz.discordsrv.modules.alerts.AlertListener.lambda$process$9(AlertListener.java:461) ~[DiscordSRV-Build-1.25.1.jar:?]
        at github.scarsz.discordsrv.DiscordSRV.lambda$translateMessage$61(DiscordSRV.java:1984) ~[DiscordSRV-Build-1.25.1.jar:?]
        at java.util.Optional.map(Optional.java:260) ~[?:?]
        at github.scarsz.discordsrv.DiscordSRV.translateMessage(DiscordSRV.java:1984) ~[DiscordSRV-Build-1.25.1.jar:?]
        at github.scarsz.discordsrv.modules.alerts.AlertListener.process(AlertListener.java:496) ~[DiscordSRV-Build-1.25.1.jar:?]
        at github.scarsz.discordsrv.modules.alerts.AlertListener.lambda$runAlertsForEvent$2(AlertListener.java:262) ~[DiscordSRV-Build-1.25.1.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]

### Server software and version

git-Pufferfish-22 (MC: 1.17.1)

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

**Comment by Scarsz** [comment]
Show your alerts.yml file

**Comment by okunamayanad** [comment]
You need to fill the spots correctly. @TheWylot

**Comment by Vankka** [comment]
Closing due to lack of info
