### ISSUE TITLE
Help!! - [DiscordSRV] [JDA] One of the EventListeners had an uncaught exception

### ISSUE THREAD

**Issue by YuaVN** [DiscordSRV/DiscordSRV#1463]
### Expected behavior

# Log : 
[11:37:21 ERROR]: [DiscordSRV] [JDA] One of the EventListeners had an uncaught exception
java.lang.NoClassDefFoundError: github/scarsz/discordsrv/dependencies/jda/api/events/message/MessageReceivedEvent
        at InteractiveChatDiscordSrvAddon-4.2.3.8.jar//com.loohp.interactivechatdiscordsrvaddon.listeners.OutboundToDiscordEvents$JDAEvents.onMessageReceived(OutboundToDiscordEvents.java:1023)
        at DiscordSRV-Build-1.26.0.jar//github.scarsz.discordsrv.dependencies.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:483)
        at DiscordSRV-Build-1.26.0.jar//github.scarsz.discordsrv.dependencies.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
        at DiscordSRV-Build-1.26.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
        at DiscordSRV-Build-1.26.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
        at DiscordSRV-Build-1.26.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.JDAImpl.handleEvent(JDAImpl.java:159)
        at DiscordSRV-Build-1.26.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:123)
        at DiscordSRV-Build-1.26.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
        at DiscordSRV-Build-1.26.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952)
        at DiscordSRV-Build-1.26.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839)
        at DiscordSRV-Build-1.26.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817)
        at DiscordSRV-Build-1.26.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:991)
        at DiscordSRV-Build-1.26.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
        at DiscordSRV-Build-1.26.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
        at DiscordSRV-Build-1.26.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
        at DiscordSRV-Build-1.26.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
        at DiscordSRV-Build-1.26.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.main(ReadingThread.java:108)
        at DiscordSRV-Build-1.26.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.runMain(ReadingThread.java:64)
        at DiscordSRV-Build-1.26.0.jar//github.scarsz.discordsrv.dependencies.ws.client.WebSocketThread.run(WebSocketThread.java:45)

### Actual behavior

.

### Steps to reproduce

.

### Server software and version

Pufferfish-1.17.1-R0.1-SNAPSHOT.jar

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [ ] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

**Comment by Scarsz** [comment]
That is an issue with `InteractiveChatDiscordSrvAddon`. Not an issue with DiscordSRV. You didn't ask in the Discord server either, although you had it checked.
