### ISSUE TITLE
Discord error during inicialization [DiscordSRV] java.lang.NoSuchFieldError: EMPTY_ARRAY

### ISSUE THREAD

**Issue by MangaPsychopath** [DiscordSRV/DiscordSRV#1470]
### Expected behavior

DiscordSRV should start normaly.

### Actual behavior

Discord shuts down during plugin inicialization

### Steps to reproduce

Start server

### Server software and version

Magma (1.12.2)

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

### Log:
[13:14:42] [DiscordSRV - Initialization/INFO] [github.scarsz.discordsrv.DiscordSRV]: [DiscordSRV] - TC:welcome-log(xxxxxxxxxxxxxxxxxxxxxxxxxxx)
[13:14:42] [DiscordSRV - Initialization/INFO] [github.scarsz.discordsrv.DiscordSRV]: [DiscordSRV] - TC:main-chat(xxxxxxxxxxxxxxxxxxxxxxxxxxx)
[13:14:42] [DiscordSRV - Initialization/INFO] [github.scarsz.discordsrv.DiscordSRV]: [DiscordSRV] - TC:mc-chat(xxxxxxxxxxxxxxxxxxxxxxxxxxx)
[13:14:42] [DiscordSRV - Initialization/INFO] [github.scarsz.discordsrv.DiscordSRV]: [DiscordSRV] - TC:mc-console(xxxxxxxxxxxxxxxxxxxxxxxxxxx)
[13:14:42] [DiscordSRV - Initialization/INFO] [github.scarsz.discordsrv.DiscordSRV]: [DiscordSRV] Console forwarding assigned to channel TC:mc-console(xxxxxxxxxxxxxxxxxxxxxxxxxxx)

[13:14:42] [DiscordSRV - Initialization/ERROR] [github.scarsz.discordsrv.DiscordSRV]: [DiscordSRV] java.lang.NoSuchFieldError: EMPTY_ARRAY
[13:14:42] [DiscordSRV - Initialization/ERROR] [github.scarsz.discordsrv.DiscordSRV]: [DiscordSRV]      at org.apache.logging.log4j.core.appender.AbstractAppender.<init>(AbstractAppender.java:195)
[13:14:42] [DiscordSRV - Initialization/ERROR] [github.scarsz.discordsrv.DiscordSRV]: [DiscordSRV]      at github.scarsz.discordsrv.objects.log4j.ConsoleAppender.<init>(ConsoleAppender.java:78)
[13:14:42] [DiscordSRV - Initialization/ERROR] [github.scarsz.discordsrv.DiscordSRV]: [DiscordSRV]      at github.scarsz.discordsrv.DiscordSRV.init(DiscordSRV.java:976)
[13:14:42] [DiscordSRV - Initialization/ERROR] [github.scarsz.discordsrv.DiscordSRV]: [DiscordSRV]      at java.lang.Thread.run(Thread.java:750)

[13:14:42] [Server thread/INFO] [github.scarsz.discordsrv.DiscordSRV]: [DiscordSRV] Disabling DiscordSRV v1.22.0
[13:14:42] [DiscordSRV - JDA Callback 1/ERROR] [github.scarsz.discordsrv.DiscordSRV]: [DiscordSRV] DiscordSRV encountered an unknown Discord error: -1: java.io.InterruptedIOException
[13:14:42] [DiscordSRV - Shutdown/INFO] [github.scarsz.discordsrv.DiscordSRV]: [DiscordSRV] Shutdown completed in 366ms

**Comment by BoredManCodes** [comment]
`I asked in DiscordSRV's Discord server to see whether this issue is in fact a bug that needs to be fixed.`
I do not see any tickets or messages referring to this issue.

Join the server and ask for help first.
https://discordsrv.com/discord
