### ISSUE TITLE
DiscordSRV Bug

### ISSUE THREAD

**Issue by antoniovcampbell** [DiscordSRV/DiscordSRV#1487]
### Expected behavior

not show this error.

### Actual behavior

 [TAB Processing Thread/WARN]: [LuckPerms] An exception was thrown by github.scarsz.discordsrv.hooks.permissions.LuckPermsHook whilst calculating the context of subject CraftPlayer{name=TonyACX}
java.lang.NullPointerException: Cannot invoke "github.scarsz.discordsrv.dependencies.jda.api.JDA.getUserById(String)" because the return value of "github.scarsz.discordsrv.util.DiscordUtil.getJda()" is null
        at github.scarsz.discordsrv.hooks.permissions.LuckPermsHook.calculate(LuckPermsHook.java:137) ~[?:?]
        at github.scarsz.discordsrv.hooks.permissions.LuckPermsHook.calculate(LuckPermsHook.java:48) ~[?:?]
        at me.lucko.luckperms.common.context.manager.ContextManager.callContextCalculator(ContextManager.java:140) ~[?:?]
        at me.lucko.luckperms.common.context.manager.ContextManager.calculate(ContextManager.java:159) ~[?:?]
        at me.lucko.luckperms.common.context.manager.QueryOptionsCache.supply(QueryOptionsCache.java:54) ~[?:?]
        at me.lucko.luckperms.common.context.manager.QueryOptionsCache.supply(QueryOptionsCache.java:42) ~[?:?]
        at me.lucko.luckperms.common.cache.ExpiringCache.get(ExpiringCache.java:64) ~[?:?]
        at me.lucko.luckperms.common.context.manager.QueryOptionsCache.getQueryOptions(QueryOptionsCache.java:59) ~[?:?]
        at me.lucko.luckperms.common.context.manager.ContextManager.getQueryOptions(ContextManager.java:85) ~[?:?]
        at me.lucko.luckperms.bukkit.LPBukkitPlugin.lambda$getQueryOptionsForUser$3(LPBukkitPlugin.java:367) ~[?:?]
        at java.util.Optional.map(Optional.java:260) ~[?:?]
        at me.lucko.luckperms.bukkit.LPBukkitPlugin.getQueryOptionsForUser(LPBukkitPlugin.java:367) ~[?:?]
        at me.lucko.luckperms.common.api.implementation.ApiContextManager.getQueryOptions(ApiContextManager.java:93) ~[?:?]
        at me.neznamy.tab.shared.permission.LuckPerms.getValue(LuckPerms.java:80) ~[?:?]
        at me.neznamy.tab.shared.permission.LuckPerms.getPrefix(LuckPerms.java:50) ~[?:?]
        at me.neznamy.tab.shared.placeholders.PlayerPlaceholderImpl.request(PlayerPlaceholderImpl.java:130) ~[?:?]
        at me.neznamy.tab.shared.placeholders.PlayerPlaceholderImpl.update(PlayerPlaceholderImpl.java:53) ~[?:?]
        at me.neznamy.tab.shared.features.PlaceholderManagerImpl.updatePlayerPlaceholder(PlaceholderManagerImpl.java:117) ~[?:?]
        at me.neznamy.tab.shared.features.PlaceholderManagerImpl.refresh(PlaceholderManagerImpl.java:68) ~[?:?]
        at me.neznamy.tab.shared.CpuManager.lambda$runMeasuredTask$8(CpuManager.java:350) ~[?:?]
        at me.neznamy.tab.shared.CpuManager.lambda$submit$1(CpuManager.java:112) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Steps to reproduce

i dont know the steps to reproduce this error.

### Server software and version

spigot-1.19.3.jar

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

**Comment by Dinty1** [comment]
^please open a support ticket about this rather than an issue
