### ISSUE TITLE
Bug when send message from Discord to Minecraft

### ISSUE THREAD

**Issue by BlocBlocTheBloc0** [DiscordSRV/DiscordSRV#1533]
### Expected behavior

The message send from Discord, display to Minecraft Chat

### Actual behavior

Nothing happend and logs say : 
[23:57:13] [Async Chat Thread - #2/INFO]: <BlocBlocTheBloc> Hello World !
2023-05-21 23:57:13,915 JDA MainWS-ReadThread WARN org.apache.logging.slf4j.Log4jLogger caught java.lang.IllegalStateException logging ReusableParameterizedMessage: Got an unexpected error. Please redirect the following message to the devs:
	JDA {}
	{} -> {} java.lang.IllegalStateException: zip file closed
	at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:831)
	at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:330)
	at java.base/java.util.jar.JarFile.getEntry(JarFile.java:518)
	at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:473)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:159)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:104)
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at github.scarsz.discordsrv.objects.log4j.JdaFilter.check(JdaFilter.java:67)
	at github.scarsz.discordsrv.objects.log4j.JdaFilter.filter(JdaFilter.java:81)
	at org.apache.logging.log4j.core.filter.CompositeFilter.filter(CompositeFilter.java:587)
	at org.apache.logging.log4j.core.filter.AbstractFilterable.isFiltered(AbstractFilterable.java:154)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:623)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:560)
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82)
	at org.apache.logging.log4j.core.Logger.log(Logger.java:162)
	at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142)
	
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2028)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1891)
	at org.apache.logging.slf4j.Log4jLogger.error(Log4jLogger.java:310)at github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839)at github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:967)
	
	at github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817)	
	at github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:991)
	at github.scarsz.discordsrv.dependencies.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
	at github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
at github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
	at github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
	at github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.main(ReadingThread.java:108)
	at github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at github.scarsz.discordsrv.dependencies.ws.client.WebSocketThread.run(WebSocketThread.java:45)

2023-05-21 23:57:16,729 JDA MainWS-ReadThread WARN org.apache.logging.slf4j.Log4jLogger caught java.lang.IllegalStateException logging ReusableParameterizedMessage: Got an unexpected error. Please redirect the following message to the devs:
	JDA {}
	{} -> {} java.lang.IllegalStateException: zip file closed
	at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:831)
	at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:330)
	at java.base/java.util.jar.JarFile.getEntry(JarFile.java:518)
	at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:473)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:159)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:104)
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at github.scarsz.discordsrv.objects.log4j.JdaFilter.check(JdaFilter.java:67)	

at github.scarsz.discordsrv.objects.log4j.JdaFilter.filter(JdaFilter.java:81)at org.apache.logging.log4j.core.filter.CompositeFilter.filter(CompositeFilter.java:587)		
	

at org.apache.logging.log4j.core.filter.AbstractFilterable.isFiltered(AbstractFilterable.java:154)at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:623)	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:560)
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82)
	
at org.apache.logging.log4j.core.Logger.log(Logger.java:162)	at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2028)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1891)

	at github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
	at github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)	at org.apache.logging.slf4j.Log4jLogger.error(Log4jLogger.java:310)
	at github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:967)
	at github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839)
	at github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817)
	at github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:991)
	at github.scarsz.discordsrv.dependencies.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
	at github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
	at github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.main(ReadingThread.java:108)
	at github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at github.scarsz.discordsrv.dependencies.ws.client.WebSocketThread.run(WebSocketThread.java:45) 

### Steps to reproduce

Juste send a message from Discord to Minecraft

### Server software and version

Spigot 1.19.4

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

**Comment by James-Bennett-295** [comment]
You claim to have asked in the Discord server, can you share your user tag?
