### ISSUE TITLE
Doesn't load on latest Paper

### ISSUE THREAD

**Issue by Electronik21** [DiscordSRV/DiscordSRV#1543]
### Expected behavior

For the plugin to load and work

### Actual behavior

The plugin doesn't load and fails with ```java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException```. I think it's caused by [this paper commit](https://github.com/PaperMC/Paper/commit/1f5bec71f398620a666eca35a8cb29d0b294dc79) which added a couple patches from Folia

### Steps to reproduce

1. Install any paper 1.20.1 build # 42 or later
2. Install latest discordsrv
3. Start the server

### Server software and version

git-Paper-43 (MC: 1.20.1)

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

### Anything else

Log:
```
[03:14:23 PM ERROR]: [DiscordSRV] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException
[03:14:23 PM ERROR]: [DiscordSRV]       at discordsrv.jar//github.scarsz.discordsrv.util.SchedulerUtil.callMethod(SchedulerUtil.java:40)
[03:14:23 PM ERROR]: [DiscordSRV]       at discordsrv.jar//github.scarsz.discordsrv.util.SchedulerUtil.callMethod(SchedulerUtil.java:45)
[03:14:23 PM ERROR]: [DiscordSRV]       at discordsrv.jar//github.scarsz.discordsrv.util.SchedulerUtil.runTaskLater(SchedulerUtil.java:115)
[03:14:23 PM ERROR]: [DiscordSRV]       at discordsrv.jar//github.scarsz.discordsrv.modules.voice.VoiceModule.<init>(VoiceModule.java:79)
[03:14:23 PM ERROR]: [DiscordSRV]       at discordsrv.jar//github.scarsz.discordsrv.DiscordSRV.init(DiscordSRV.java:1325)
[03:14:23 PM ERROR]: [DiscordSRV]       at java.base/java.lang.Thread.run(Thread.java:1623)
[03:14:23 PM ERROR]: [DiscordSRV] Caused by: java.lang.reflect.InvocationTargetException
[03:14:23 PM ERROR]: [DiscordSRV]       at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
[03:14:23 PM ERROR]: [DiscordSRV]       at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[03:14:23 PM ERROR]: [DiscordSRV]       at discordsrv.jar//github.scarsz.discordsrv.util.SchedulerUtil.callMethod(SchedulerUtil.java:38)
[03:14:23 PM ERROR]: [DiscordSRV]       ... 5 more
[03:14:23 PM ERROR]: [DiscordSRV] Caused by: java.lang.IllegalArgumentException: Delay ticks may not be <= 0
[03:14:23 PM ERROR]: [DiscordSRV]       at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.runDelayed(FoliaGlobalRegionScheduler.java:61)
[03:14:23 PM ERROR]: [DiscordSRV]       at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[03:14:23 PM INFO]: [DiscordSRV] Disabling DiscordSRV v1.26.3-SNAPSHOT
```

**Comment by Vankka** [comment]
Above commit likely fixes the issue (https://snapshot.discordsrv.com for a dev build), might still need to add a check so the Folia scheduler only gets used on Folia now that the Folia scheduler api is included in Paper...

**Comment by Electronik21** [comment]
That commit fixed it. Thank you
