### ISSUE TITLE
Error due to Discord outage

### ISSUE THREAD

**Issue by Distolfix** [DiscordSRV/DiscordSRV#1544]
### Expected behavior

[23:23:44 WARN]: github.scarsz.discordsrv.dependencies.jda.api.exceptions.ErrorResponseException: 0: 503: Service Unavailable
[23:23:44 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:227)
[23:23:44 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.api.requests.RestAction.complete(RestAction.java:633)
[23:23:44 WARN]:        at DiscordSRV-Build-1.26.2.jar//me.scarsz.jdaappender.ChannelLoggingHandler.updateMessage(ChannelLoggingHandler.java:239)
[23:23:44 WARN]:        at DiscordSRV-Build-1.26.2.jar//me.scarsz.jdaappender.ChannelLoggingHandler.flush(ChannelLoggingHandler.java:144)
[23:23:44 WARN]:        at DiscordSRV-Build-1.26.2.jar//me.scarsz.jdaappender.ChannelLoggingHandler.lambda$schedule$0(ChannelLoggingHandler.java:55)
[23:23:44 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[23:23:44 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[23:23:44 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[23:23:44 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[23:23:44 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[23:23:44 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[23:23:44 WARN]: Caused by: github.scarsz.discordsrv.dependencies.jda.api.exceptions.ContextException
[23:23:44 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.api.exceptions.ContextException.here(ContextException.java:54)
[23:23:44 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.api.requests.Request.<init>(Request.java:71)
[23:23:44 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.api.requests.RestFuture.<init>(RestFuture.java:36)
[23:23:44 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.submit(RestActionImpl.java:209)
[23:23:44 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:219)
[23:23:44 WARN]:        ... 10 more
[23:23:46 WARN]: github.scarsz.discordsrv.dependencies.jda.api.exceptions.ErrorResponseException: 0: 503: Service Unavailable
[23:23:46 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:227)
[23:23:46 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.api.requests.RestAction.complete(RestAction.java:633)
[23:23:46 WARN]:        at DiscordSRV-Build-1.26.2.jar//me.scarsz.jdaappender.ChannelLoggingHandler.updateMessage(ChannelLoggingHandler.java:239)
[23:23:46 WARN]:        at DiscordSRV-Build-1.26.2.jar//me.scarsz.jdaappender.ChannelLoggingHandler.dumpStack(ChannelLoggingHandler.java:157)
[23:23:46 WARN]:        at DiscordSRV-Build-1.26.2.jar//me.scarsz.jdaappender.ChannelLoggingHandler.flush(ChannelLoggingHandler.java:136)
[23:23:46 WARN]:        at DiscordSRV-Build-1.26.2.jar//me.scarsz.jdaappender.ChannelLoggingHandler.lambda$schedule$0(ChannelLoggingHandler.java:55)
[23:23:46 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[23:23:46 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[23:23:46 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[23:23:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[23:23:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[23:23:46 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[23:23:46 WARN]: Caused by: github.scarsz.discordsrv.dependencies.jda.api.exceptions.ContextException
[23:23:46 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.api.exceptions.ContextException.here(ContextException.java:54)
[23:23:46 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.api.requests.Request.<init>(Request.java:71)
[23:23:46 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.api.requests.RestFuture.<init>(RestFuture.java:36)
[23:23:46 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.submit(RestActionImpl.java:209)
[23:23:46 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:219)
[23:23:46 WARN]:        ... 11 more
[23:24:03 WARN]: github.scarsz.discordsrv.dependencies.jda.api.exceptions.ErrorResponseException: 0: 503: Service Unavailable
[23:24:03 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:227)
[23:24:03 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.api.requests.RestAction.complete(RestAction.java:633)
[23:24:03 WARN]:        at DiscordSRV-Build-1.26.2.jar//me.scarsz.jdaappender.ChannelLoggingHandler.updateMessage(ChannelLoggingHandler.java:239)
[23:24:03 WARN]:        at DiscordSRV-Build-1.26.2.jar//me.scarsz.jdaappender.ChannelLoggingHandler.dumpStack(ChannelLoggingHandler.java:157)
[23:24:03 WARN]:        at DiscordSRV-Build-1.26.2.jar//me.scarsz.jdaappender.ChannelLoggingHandler.flush(ChannelLoggingHandler.java:136)
[23:24:03 WARN]:        at DiscordSRV-Build-1.26.2.jar//me.scarsz.jdaappender.ChannelLoggingHandler.lambda$schedule$0(ChannelLoggingHandler.java:55)
[23:24:03 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[23:24:03 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[23:24:03 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[23:24:03 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[23:24:03 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[23:24:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[23:24:03 WARN]: Caused by: github.scarsz.discordsrv.dependencies.jda.api.exceptions.ContextException
[23:24:03 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.api.exceptions.ContextException.here(ContextException.java:54)
[23:24:03 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.api.requests.Request.<init>(Request.java:71)
[23:24:03 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.api.requests.RestFuture.<init>(RestFuture.java:36)
[23:24:03 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.submit(RestActionImpl.java:209)
[23:24:03 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:219)
[23:24:03 WARN]:        ... 11 more
[23:24:09 WARN]: github.scarsz.discordsrv.dependencies.jda.api.exceptions.ErrorResponseException: 0: 503: Service Unavailable
[23:24:09 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:227)
[23:24:09 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.api.requests.RestAction.complete(RestAction.java:633)
[23:24:09 WARN]:        at DiscordSRV-Build-1.26.2.jar//me.scarsz.jdaappender.ChannelLoggingHandler.updateMessage(ChannelLoggingHandler.java:239)
[23:24:09 WARN]:        at DiscordSRV-Build-1.26.2.jar//me.scarsz.jdaappender.ChannelLoggingHandler.dumpStack(ChannelLoggingHandler.java:157)
[23:24:09 WARN]:        at DiscordSRV-Build-1.26.2.jar//me.scarsz.jdaappender.ChannelLoggingHandler.flush(ChannelLoggingHandler.java:136)
[23:24:09 WARN]:        at DiscordSRV-Build-1.26.2.jar//me.scarsz.jdaappender.ChannelLoggingHandler.lambda$schedule$0(ChannelLoggingHandler.java:55)
[23:24:09 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[23:24:09 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[23:24:09 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[23:24:09 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[23:24:09 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[23:24:09 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[23:24:09 WARN]: Caused by: github.scarsz.discordsrv.dependencies.jda.api.exceptions.ContextException
[23:24:09 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.api.exceptions.ContextException.here(ContextException.java:54)
[23:24:09 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.api.requests.Request.<init>(Request.java:71)
[23:24:09 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.api.requests.RestFuture.<init>(RestFuture.java:36)
[23:24:09 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.submit(RestActionImpl.java:209)
[23:24:09 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:219)
[23:24:09 WARN]:        ... 11 more
[23:24:10 WARN]: github.scarsz.discordsrv.dependencies.jda.api.exceptions.ErrorResponseException: 0: 503: Service Unavailable
[23:24:10 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:227)
[23:24:10 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.api.requests.RestAction.complete(RestAction.java:633)
[23:24:10 WARN]:        at DiscordSRV-Build-1.26.2.jar//me.scarsz.jdaappender.ChannelLoggingHandler.updateMessage(ChannelLoggingHandler.java:239)
[23:24:10 WARN]:        at DiscordSRV-Build-1.26.2.jar//me.scarsz.jdaappender.ChannelLoggingHandler.dumpStack(ChannelLoggingHandler.java:157)
[23:24:10 WARN]:        at DiscordSRV-Build-1.26.2.jar//me.scarsz.jdaappender.ChannelLoggingHandler.flush(ChannelLoggingHandler.java:136)
[23:24:10 WARN]:        at DiscordSRV-Build-1.26.2.jar//me.scarsz.jdaappender.ChannelLoggingHandler.lambda$schedule$0(ChannelLoggingHandler.java:55)
[23:24:10 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[23:24:10 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[23:24:10 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[23:24:10 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[23:24:10 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[23:24:10 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[23:24:10 WARN]: Caused by: github.scarsz.discordsrv.dependencies.jda.api.exceptions.ContextException
[23:24:10 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.api.exceptions.ContextException.here(ContextException.java:54)
[23:24:10 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.api.requests.Request.<init>(Request.java:71)
[23:24:10 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.api.requests.RestFuture.<init>(RestFuture.java:36)
[23:24:10 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.submit(RestActionImpl.java:209)
[23:24:10 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:219)
[23:24:10 WARN]:        ... 11 more
[23:24:20 WARN]: github.scarsz.discordsrv.dependencies.jda.api.exceptions.ErrorResponseException: 0: 503: Service Unavailable
[23:24:20 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:227)
[23:24:20 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.api.requests.RestAction.complete(RestAction.java:633)
[23:24:20 WARN]:        at DiscordSRV-Build-1.26.2.jar//me.scarsz.jdaappender.ChannelLoggingHandler.updateMessage(ChannelLoggingHandler.java:249)
[23:24:20 WARN]:        at DiscordSRV-Build-1.26.2.jar//me.scarsz.jdaappender.ChannelLoggingHandler.dumpStack(ChannelLoggingHandler.java:157)
[23:24:20 WARN]:        at DiscordSRV-Build-1.26.2.jar//me.scarsz.jdaappender.ChannelLoggingHandler.flush(ChannelLoggingHandler.java:136)
[23:24:20 WARN]:        at DiscordSRV-Build-1.26.2.jar//me.scarsz.jdaappender.ChannelLoggingHandler.lambda$schedule$0(ChannelLoggingHandler.java:55)
[23:24:20 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[23:24:20 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[23:24:20 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[23:24:20 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[23:24:20 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[23:24:20 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[23:24:20 WARN]: Caused by: github.scarsz.discordsrv.dependencies.jda.api.exceptions.ContextException
[23:24:20 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.api.exceptions.ContextException.here(ContextException.java:54)
[23:24:20 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.api.requests.Request.<init>(Request.java:71)
[23:24:20 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.api.requests.RestFuture.<init>(RestFuture.java:36)
[23:24:20 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.submit(RestActionImpl.java:209)
[23:24:20 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:219)
[23:24:20 WARN]:        ... 11 more

### Actual behavior

no

### Steps to reproduce

no

### Server software and version

Pufferfish 1.19.4

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

**Comment by James-Bennett-295** [comment]
You claim to have asked on the Discord server, can you share your Discord ID?

**Comment by Vankka** [comment]
This is caused by a Discord outage (https://discordstatus.com/) nothing we can do about it
