### ISSUE TITLE
Property or field 'address' cannot be found on null

### ISSUE THREAD

**Issue by andrewkm** [DiscordSRV/DiscordSRV#1597]
### Expected behavior

No error.

### Actual behavior

```
[12:32:23] [Folia Async Scheduler Thread #6/WARN]: [DiscordSRV] Async task for DiscordSRV v1.27.0-SNAPSHOT generated an exception
org.springframework.expression.spel.SpelEvaluationException: EL1007E: Property or field 'address' cannot be found on null
	at org.springframework.expression.spel.ast.PropertyOrFieldReference.readProperty(PropertyOrFieldReference.java:213) ~[DiscordSRV.jar:?]
	at org.springframework.expression.spel.ast.PropertyOrFieldReference.getValueInternal(PropertyOrFieldReference.java:104) ~[DiscordSRV.jar:?]
	at org.springframework.expression.spel.ast.PropertyOrFieldReference.getValueInternal(PropertyOrFieldReference.java:91) ~[DiscordSRV.jar:?]
	at org.springframework.expression.spel.ast.CompoundExpression.getValueRef(CompoundExpression.java:61) ~[DiscordSRV.jar:?]
	at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:91) ~[DiscordSRV.jar:?]
	at org.springframework.expression.spel.ast.SpelNodeImpl.getTypedValue(SpelNodeImpl.java:117) ~[DiscordSRV.jar:?]
	at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:308) ~[DiscordSRV.jar:?]
	at github.scarsz.discordsrv.util.SpELExpressionBuilder.evaluate(SpELExpressionBuilder.java:71) ~[DiscordSRV.jar:?]
	at github.scarsz.discordsrv.util.SpELExpressionBuilder.evaluate(SpELExpressionBuilder.java:65) ~[DiscordSRV.jar:?]
	at github.scarsz.discordsrv.util.NamedValueFormatter.lambda$formatExpressions$1(NamedValueFormatter.java:96) ~[DiscordSRV.jar:?]
	at github.scarsz.discordsrv.util.NamedValueFormatter.format(NamedValueFormatter.java:55) ~[DiscordSRV.jar:?]
	at github.scarsz.discordsrv.util.NamedValueFormatter.formatExpressions(NamedValueFormatter.java:90) ~[DiscordSRV.jar:?]
	at github.scarsz.discordsrv.modules.alerts.AlertListener.lambda$process$9(AlertListener.java:459) ~[DiscordSRV.jar:?]
	at github.scarsz.discordsrv.DiscordSRV.lambda$translateMessage$63(DiscordSRV.java:1987) ~[DiscordSRV.jar:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at github.scarsz.discordsrv.DiscordSRV.translateMessage(DiscordSRV.java:1987) ~[DiscordSRV.jar:?]
	at github.scarsz.discordsrv.modules.alerts.AlertListener.process(AlertListener.java:494) ~[DiscordSRV.jar:?]
	at github.scarsz.discordsrv.modules.alerts.AlertListener.lambda$runAlertsForEvent$2(AlertListener.java:260) ~[DiscordSRV.jar:?]
	at github.scarsz.discordsrv.util.SchedulerUtil.lambda$runTaskAsynchronously$1(SchedulerUtil.java:95) ~[DiscordSRV.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[paper-1.20.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Steps to reproduce

Unsure, caught it during startup / player joining.

### Server software and version

Paper 1.20.2 Build 223

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

### Anything else

Paper 1.20.2 Build 223
DiscordSRV built against: https://github.com/DiscordSRV/DiscordSRV/commit/fdcb09f7f73494ae0ae4dfcb649ef34dcaf51dbf

**Comment by Dinty1** [comment]
Please actually ask about this in the discord server first. As far as I can tell you’re not even in it anymore
