### ISSUE TITLE
Infinity spamming on unknown msg 

### ISSUE THREAD

**Issue by AlphaO612** [DiscordSRV/DiscordSRV#1634]
### Expected behavior

Report warning and stop spamming warning to the console

### Actual behavior

Infinity sending to console msg on use custom command for plugin TP+ 

### Steps to reproduce

```
[15:06:52 INFO]: Aplick issued server command: /tp 05dima
[15:06:53 WARN]: java.lang.RuntimeException: java.util.concurrent.ExecutionException: github.scarsz.discordsrv.dependencies.jda.api.exceptions.ErrorResponseException: 10008: Unknown Message
[15:06:53 WARN]:        at DiscordSRV-Build-1.27.0.jar//me.scarsz.jdaappender.ChannelLoggingHandler.updateMessage(ChannelLoggingHandler.java:249)
[15:06:53 WARN]:        at DiscordSRV-Build-1.27.0.jar//me.scarsz.jdaappender.ChannelLoggingHandler.dumpStack(ChannelLoggingHandler.java:159)
[15:06:53 WARN]:        at DiscordSRV-Build-1.27.0.jar//me.scarsz.jdaappender.ChannelLoggingHandler.flush(ChannelLoggingHandler.java:138)
[15:06:53 WARN]:        at DiscordSRV-Build-1.27.0.jar//me.scarsz.jdaappender.ChannelLoggingHandler.lambda$schedule$0(ChannelLoggingHandler.java:57)
[15:06:53 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[15:06:53 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[15:06:53 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[15:06:53 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[15:06:53 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[15:06:53 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[15:06:53 WARN]: Caused by: java.util.concurrent.ExecutionException: github.scarsz.discordsrv.dependencies.jda.api.exceptions.ErrorResponseException: 10008: Unknown Message
[15:06:53 WARN]:        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
[15:06:53 WARN]:        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[15:06:53 WARN]:        at DiscordSRV-Build-1.27.0.jar//me.scarsz.jdaappender.ChannelLoggingHandler.updateMessage(ChannelLoggingHandler.java:241)
[15:06:53 WARN]:        ... 9 more
[15:06:53 WARN]: Caused by: github.scarsz.discordsrv.dependencies.jda.api.exceptions.ErrorResponseException: 10008: Unknown Message
[15:06:53 WARN]:        at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.api.exceptions.ErrorResponseException.create(ErrorResponseException.java:185)
[15:06:53 WARN]:        at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.api.requests.Request.onFailure(Request.java:117)
[15:06:53 WARN]:        at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.handleResponse(RestActionImpl.java:270)
[15:06:53 WARN]:        at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.api.requests.Request.handleResponse(Request.java:259)
[15:06:53 WARN]:        at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.Requester.execute(Requester.java:237)
[15:06:53 WARN]:        at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.Requester.execute(Requester.java:141)
[15:06:53 WARN]:        at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.Requester.execute(Requester.java:124)
[15:06:53 WARN]:        at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:478)
[15:06:53 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[15:06:53 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[15:06:53 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[15:06:53 WARN]:        ... 3 more
[15:06:53 WARN]: Caused by: github.scarsz.discordsrv.dependencies.jda.api.exceptions.ContextException
[15:06:53 WARN]:        at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.api.exceptions.ContextException.here(ContextException.java:54)
[15:06:53 WARN]:        at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.api.requests.Request.<init>(Request.java:71)
[15:06:53 WARN]:        at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.api.requests.RestFuture.<init>(RestFuture.java:36)
[15:06:53 WARN]:        at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.submit(RestActionImpl.java:209)
[15:06:53 WARN]:        at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.api.requests.RestAction.submit(RestAction.java:694)
[15:06:53 WARN]:        at DiscordSRV-Build-1.27.0.jar//me.scarsz.jdaappender.ChannelLoggingHandler.updateMessage(ChannelLoggingHandler.java:241)
[15:06:53 WARN]:        at DiscordSRV-Build-1.27.0.jar//me.scarsz.jdaappender.ChannelLoggingHandler.dumpStack(ChannelLoggingHandler.java:159)
[15:06:53 WARN]:        at DiscordSRV-Build-1.27.0.jar//me.scarsz.jdaappender.ChannelLoggingHandler.flush(ChannelLoggingHandler.java:138)
[15:06:53 WARN]:        at DiscordSRV-Build-1.27.0.jar//me.scarsz.jdaappender.ChannelLoggingHandler.lambda$schedule$0(ChannelLoggingHandler.java:57)
[15:06:53 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[15:06:53 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[15:06:53 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[15:06:53 WARN]:        ... 3 more
```
that's it part sending again. again and again... until reload plugin, but after using command, that's happening again

### Server software and version

git-Paper-17 (MC: 1.20) (Implementing API version 1.20-R0.1-SNAPSHOT) (Git: c287e92)

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [ ] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.
- [ ] I didn't actually check any of these things

**Comment by James-Bennett-295** [comment]
There is already an issue open for this in the library used for the console ([JDAAppender #18](https://github.com/Scarsz/JDAAppender/issues/18))

**Comment by AlphaO612** [comment]
> There is already an issue open for this in the library used for the console ([JDAAppender #18](https://github.com/Scarsz/JDAAppender/issues/18))

Oh... ok. Do u know how to turn off it(Like stop its spamming)?
I cant read my logs :)

**Comment by thewilloftheshadow** [comment]
That happens when a message that the bot sends in the console channel is deleted, so find what's deleting the messages

**Comment by AlphaO612** [comment]
nothing deleting. I a bit checked it.

**Comment by granny** [comment]
Fixed in the latest snapshot build. Issue will be automatically closed once a release build is published.
