### ISSUE TITLE
Fails to retrieve NMS classes that use mojang mappings

### ISSUE THREAD

**Issue by jurohn** [DiscordSRV/DiscordSRV#1672]
### Expected behavior

No console errors

### Actual behavior

Console error:
```

04.05 07:38:12 [Server] WARN java.lang.ClassNotFoundException: Could not find net.minecraft.server.EntityPlayer
04.05 07:38:12 [Server] WARN at DiscordSRV-1.28.0-SNAPSHOT-c68b722.jar//github.scarsz.discordsrv.util.NMSUtil.fixBukkitClass(NMSUtil.java:130)
04.05 07:38:12 [Server] WARN at DiscordSRV-1.28.0-SNAPSHOT-c68b722.jar//github.scarsz.discordsrv.util.NMSUtil.<clinit>(NMSUtil.java:65)
04.05 07:38:12 [Server] WARN at DiscordSRV-1.28.0-SNAPSHOT-c68b722.jar//github.scarsz.discordsrv.DiscordSRV.getAvatarUrl(DiscordSRV.java:2060)
04.05 07:38:12 [Server] WARN at DiscordSRV-1.28.0-SNAPSHOT-c68b722.jar//github.scarsz.discordsrv.DiscordSRV.sendJoinMessage(DiscordSRV.java:1905)
04.05 07:38:12 [Server] WARN at DiscordSRV-1.28.0-SNAPSHOT-c68b722.jar//github.scarsz.discordsrv.listeners.PlayerJoinLeaveListener.lambda$onPlayerJoin$1(PlayerJoinLeaveListener.java:94)
04.05 07:38:12 [Server] WARN at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101)
04.05 07:38:12 [Server] WARN at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
04.05 07:38:12 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
04.05 07:38:12 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
04.05 07:38:12 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
04.05 07:38:12 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Steps to reproduce

Install paper 1.20.6 latest dev (version 36) and discordSRV newest dev build (as of 04-05-2024)

### Server software and version

git-Paper-36 (MC 1.20.6)

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.
- [ ] I didn't actually check any of these things

**Comment by Aearost** [comment]
I can confirm I have been encountering this error as well. It seems to happen any time a player connects to the server. The message still is sent to the hooked discord channel (we still see the join message in Discord), however the error is still displayed.

**Comment by jurohn** [comment]
Correct, can be closed :) Thank you!

**Comment by thewilloftheshadow** [comment]
We'll close it once 1.28.0 is released and this is fixed there instead of solely in a snapshot o7

**Comment by QuasarBlume165** [comment]
Merci @granny this is really helpful. Thanks a lot 💯
