### ISSUE TITLE
java.lang.ClassNotFoundException: Could not find net.minecraft.server.EntityPlayer

### ISSUE THREAD

**Issue by Strahilchu** [DiscordSRV/DiscordSRV#1693]
### Expected behavior

No error

### Actual behavior

[20:16:14 WARN]: java.lang.ClassNotFoundException: Could not find net.minecraft.server.EntityPlayer
[20:16:14 WARN]:        at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.util.NMSUtil.fixBukkitClass(NMSUtil.java:122)
[20:16:14 WARN]:        at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.util.NMSUtil.<clinit>(NMSUtil.java:61)
[20:16:14 WARN]:        at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.DiscordSRV.getAvatarUrl(DiscordSRV.java:2025)
[20:16:14 WARN]:        at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.DiscordSRV.sendJoinMessage(DiscordSRV.java:1870)
[20:16:14 WARN]:        at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.listeners.PlayerJoinLeaveListener.lambda$onPlayerJoin$1(PlayerJoinLeaveListener.java:94)
[20:16:14 WARN]:        at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.util.SchedulerUtil.lambda$runTaskLaterAsynchronously$4(SchedulerUtil.java:125)
[20:16:14 WARN]:        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217)
[20:16:14 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[20:16:14 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[20:16:14 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[20:16:14 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[20:16:14 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[20:16:14 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

### Steps to reproduce

Join on 1.20.6

### Server software and version

Purpur Version: 1.20.6-2230-eac4198 (MC: 1.20.6)*

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.
- [X] I didn't actually check any of these things

**Comment by Dinty1** [comment]
Use https://snapshot.discordsrv.com/

**Comment by Dinty1** [comment]
(This is the development build)

**Comment by lahnan** [comment]
> Fixed on the development build. https://snapshot.discordsrv.com/

how If I using aternos?

**Comment by granny** [comment]
@lahnan you'll have to wait for a discordsrv release to come out

**Comment by foxya27** [comment]
> > Fixed on the development build. https://snapshot.discordsrv.com/
> 
> how If I using aternos?

Site not working

**Comment by PadowYT2** [comment]
> > > Fixed on the development build. https://snapshot.discordsrv.com/
> > 
> > 
> > how If I using aternos?
> 
> Site not working

You can install the latest development version from https://github.com/DiscordSRV/DiscordSRV/actions/runs/9623200234/artifacts/1627157696
