### ISSUE TITLE
Discord -> Minecraft Ban Sync not working

### ISSUE THREAD

**Issue by IngeniousCoder** [DiscordSRV/DiscordSRV#1694]
### Expected behavior

When banned on Discord, the player should automatically get banned on minecraft.

### Actual behavior

- [Mon 22:22:42 ERROR DiscordSRV] [JDA] One of the EventListeners had an uncaught exception
java.lang.IllegalStateException: java.lang.NoSuchMethodException: org.bukkit.craftbukkit.v1_20_R2.entity.CraftPlayer.getScheduler()
    at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.util.SchedulerUtil.callMethod(SchedulerUtil.java:40)
    at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.util.SchedulerUtil.callMethod(SchedulerUtil.java:49)
    at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.util.SchedulerUtil.runTaskForPlayer(SchedulerUtil.java:133)
    at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.listeners.DiscordBanListener.onGuildBan(DiscordBanListener.java:65)
    at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:483)
    at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
    at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
    at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
    at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.JDAImpl.handleEvent(JDAImpl.java:159)
    at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.handle.GuildBanHandler.handleInternally(GuildBanHandler.java:56)
    at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
    at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952)
    at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839)
    at Dis
- [Mon 22:22:42 ERROR DiscordSRV] cordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817)
    at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:991)
    at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
    at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
    at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
    at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
    at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.main(ReadingThread.java:108)
    at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.runMain(ReadingThread.java:64)
    at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.ws.client.WebSocketThread.run(WebSocketThread.java:45)
Caused by: java.lang.NoSuchMethodException: org.bukkit.craftbukkit.v1_20_R2.entity.CraftPlayer.getScheduler()
    at java.base/java.lang.Class.getDeclaredMethod(Class.java:2675)
    at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.util.SchedulerUtil.callMethod(SchedulerUtil.java:38)
    ... 21 more

### Steps to reproduce

Ban a player on discord.

### Server software and version

git-Paper-223

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.
- [ ] I didn't actually check any of these things

### Anything else

Permissions validated, bot has permissions to ban users.

**Comment by Dinty1** [comment]
This is (I think) already fixed on development builds. https://snapshot.discordsrv.com

**Comment by granny** [comment]
closed by https://github.com/DiscordSRV/DiscordSRV/commit/49b83f3526045cf4d3b3576f4bf7c6a1cce5c1fa
