### ISSUE TITLE
/discord link doesn’t work

### ISSUE THREAD

**Issue by Discorderer** [DiscordSRV/DiscordSRV#375]
```
11.08 13:34:21 [Server] WARN handleDisconnection() called twice
11.08 13:34:21 [Server] INFO Spirit_Bender went on a long journey
11.08 13:34:21 [Disconnect] User Spirit_Bender has disconnected, reason: Timed out
11.08 13:34:00 [Server] INFO Spirit_Bender: wat
11.08 13:34:00 [Multicraft] Skipped 2 lines due to rate limit (30/s)
11.08 13:33:57 [Server] WARN at github.scarsz.discordsrv.util.DebugUtil.run(DebugUtil.java:98)
11.08 13:33:57 [Server] WARN at github.scarsz.discordsrv.util.DebugUtil.uploadReport(DebugUtil.java:209)
11.08 13:33:57 [Server] WARN at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
11.08 13:33:57 [Server] WARN at github.scarsz.discordsrv.util.DebugUtil.lambda$uploadReport$4(DebugUtil.java:210)
11.08 13:33:57 [Server] WARN at java.lang.String.replace(String.java:2239)
11.08 13:33:57 [Server] WARN Caused by: java.lang.NullPointerException
11.08 13:33:57 [Server] WARN at java.lang.Thread.run(Thread.java:748)
11.08 13:33:57 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
11.08 13:33:57 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
11.08 13:33:57 [Server] WARN at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
11.08 13:33:57 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
11.08 13:33:57 [Server] WARN at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
11.08 13:33:57 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11.08 13:33:57 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
11.08 13:33:57 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
11.08 13:33:57 [Server] WARN at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
11.08 13:33:57 [Server] WARN at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
11.08 13:33:57 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1227)
11.08 13:33:57 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1392)
11.08 13:33:57 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:651)
11.08 13:33:57 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
11.08 13:33:57 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
11.08 13:33:57 [Server] WARN at github.scarsz.discordsrv.DiscordSRV.onCommand(DiscordSRV.java:540)
11.08 13:33:57 [Server] WARN at github.scarsz.discordsrv.objects.managers.CommandManager.handle(CommandManager.java:104)
11.08 13:33:57 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
11.08 13:33:57 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11.08 13:33:57 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
11.08 13:33:57 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11.08 13:33:57 [Server] WARN java.lang.reflect.InvocationTargetException
```

**Comment by Scarsz** [comment]
This is not a full stack trace. Give the lines from your server log.

**Comment by axemwa** [comment]
I'm having the same issue, but no error appears I get this show when I try to DM the bot

"ClydeBOTToday at 12:19 AM
Your message could not be delivered because you don't share a server with the recipient or you disabled direct messages on your shared server, recipient is only accepting direct messages from friends, or you were blocked by the recipient." using latest SNAPSHOT to date

**Comment by Vankka** [comment]
@axemwa that's because you have private messages from/to guild members disabled (see privacy settings)

**Comment by axemwa** [comment]
Literally just found it before I read this message, thankyou :)

**Comment by axemwa** [comment]
@Vankka what if when a player joins the server but it wont show the player has joined message like it usually does, know what would fix this?

**Comment by Vankka** [comment]
probably has discordsrv.silentjoin 

if you need anymore help please join Discord https://scarsz.me/discord #support 
we don't use the GitHub issue tracker for support & this isn't even your issue to begin with

**Comment by Scarsz** [comment]
don’t hijack issues

**Comment by Scarsz** [comment]
actually am going to close this from no response
