### ISSUE TITLE
Exception thrown on startup

### ISSUE THREAD

**Issue by KarlOfDuty** [DiscordSRV/DiscordSRV#419]
```yaml
[22:14:33 WARN]: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
[22:14:33 WARN]:        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
[22:14:33 WARN]:        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1946)
[22:14:33 WARN]:        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:316)
[22:14:33 WARN]:        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310)
[22:14:33 WARN]:        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639)
[22:14:33 WARN]:        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223)
[22:14:33 WARN]:        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
[22:14:33 WARN]:        at sun.security.ssl.Handshaker.process_record(Handshaker.java:965)
[22:14:33 WARN]:        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064)
[22:14:33 WARN]:        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
[22:14:33 WARN]:        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
[22:14:33 WARN]:        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
[22:14:33 WARN]:        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
[22:14:33 WARN]:        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
[22:14:33 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
[22:14:33 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
[22:14:33 WARN]:        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
[22:14:33 WARN]:        at java.net.URL.openStream(URL.java:1045)
[22:14:33 WARN]:        at org.apache.commons.io.IOUtils.toString(IOUtils.java:1153)
[22:14:33 WARN]:        at fr.klemms.slotmachine.KlemmsUpdate$1.run(KlemmsUpdate.java:66)
[22:14:33 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82)
[22:14:33 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:448)
[22:14:33 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008)
[22:14:33 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[22:14:33 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943)
[22:14:33 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841)
[22:14:33 WARN]:        at java.lang.Thread.run(Thread.java:748)
[22:14:33 WARN]: Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
[22:14:33 WARN]:        at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:362)
[22:14:33 WARN]:        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:270)
[22:14:33 WARN]:        at sun.security.validator.Validator.validate(Validator.java:262)
[22:14:33 WARN]:        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
[22:14:33 WARN]:        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
[22:14:33 WARN]:        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
[22:14:33 WARN]:        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1621)
[22:14:33 WARN]:        ... 22 more
[22:14:33 WARN]: Caused by: java.security.cert.CertPathValidatorException: validity check failed
[22:14:33 WARN]:        at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
[22:14:33 WARN]:        at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:233)
[22:14:33 WARN]:        at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:141)
[22:14:33 WARN]:        at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:80)
[22:14:33 WARN]:        at java.security.cert.CertPathValidator.validate(CertPathValidator.java:292)
[22:14:33 WARN]:        at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:357)
[22:14:33 WARN]:        ... 28 more
[22:14:33 WARN]: Caused by: java.security.cert.CertificateExpiredException: NotAfter: Fri Dec 14 16:24:07 CET 2018
[22:14:33 WARN]:        at sun.security.x509.CertificateValidity.valid(CertificateValidity.java:274)
[22:14:33 WARN]:        at sun.security.x509.X509CertImpl.checkValidity(X509CertImpl.java:629)
[22:14:33 WARN]:        at sun.security.provider.certpath.BasicChecker.verifyValidity(BasicChecker.java:190)
[22:14:33 WARN]:        at sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:144)
[22:14:33 WARN]:        at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
[22:14:33 WARN]:        ... 33 more
```

**Comment by KarlOfDuty** [comment]
Hang on, wrong plugin, had multiple github tabs open sorry.
