### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by x1p** [DiscordSRV/DiscordSRV#421]
Saw this error appearing. It stopped working.
```
[22:24:38] [Log4j2-TF-1-AsyncLogger[AsyncContext@55f96302]-1/ERROR]: [DiscordSRV] [JDA] One of the EventListeners had an uncaught exception
[22:25:08] [Server thread/INFO]: Player123 issued server command: /
[22:25:09] [Server thread/INFO]: Player123 lost connection: Disconnected
...
[22:30:30] [User Authenticator #114/INFO]: UUID of player Player123 is censored-uuid-uuid-uuid-uuid
[22:30:30] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to DiscordSRV v1.16.6
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.2.jar:git-Paper-488]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.PlayerList.onPlayerJoin(PlayerList.java:369) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.PlayerList.a(PlayerList.java:180) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.LoginListener.b(LoginListener.java:170) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.LoginListener.tick(LoginListener.java:66) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:263) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:130) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1129) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-488]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
	at github.scarsz.discordsrv.listeners.PlayerJoinLeaveListener.PlayerJoinEvent(PlayerJoinLeaveListener.java:83) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor651.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-488]
	... 14 more
```
DiscordSRV-Build-1.16.6
Paper 1.13.2 build 488

**Comment by Vankka** [comment]
Join https://scarsz.me/discord for help, please post the link to this ticket in #support
