### ISSUE TITLE
Connection error or unfound files

### ISSUE THREAD

**Issue by PianoRailways** [DiscordSRV/DiscordSRV#449]
Messages won't sync between MC and Discord. This is my log with relevant information, i think:

https://hastebin.com/joparipere

> [18:55:01 WARN]: [DiscordSRV] [JDA] Attempting to reconnect!
>
[18:55:01 INFO]: [DiscordSRV] [JDA] Connected to WebSocket
>
[18:55:02 INFO]: [DiscordSRV] [JDA] Finished Loading!
>
[18:55:02 INFO]: [DiscordSRV] Found server G:pianmc(172991126297509888)
>
[18:55:02 INFO]: [DiscordSRV] - TC:eingang(172991126297509888)
>
[18:55:02 INFO]: [DiscordSRV] - TC:test(315145490247188480)
>
[18:55:02 INFO]: [DiscordSRV] - TC:minecraftchat(178869562484195328)
>
[18:55:02 INFO]: [DiscordSRV] - TC:simulatoren(398796865543602176)
>
[18:55:02 INFO]: [DiscordSRV] - TC:seelsorge(410884800799440896)
>
[18:55:02 INFO]: [DiscordSRV] - TC:regeln-ingame(467777801987162132)
>
[18:55:02 INFO]: [DiscordSRV] - TC:tweets(567389039552888856)
>
[18:55:02 INFO]: [DiscordSRV] - TC:infos-ankündigungen(300676181358018580)
>
[18:55:02 INFO]: [DiscordSRV] - TC:newsticker(473224091290042368)
>
[18:55:02 INFO]: [DiscordSRV] - TC:archiv(380451749288214528)
>
[18:55:02 INFO]: [DiscordSRV] - TC:bilder(294859583418269697)
>
[18:55:02 INFO]: [DiscordSRV] - TC:schreiben(173724381846044683)
>
[18:55:02 INFO]: [DiscordSRV] - TC:witze(317025164862685185)
>
[18:55:02 INFO]: [DiscordSRV] - TC:musik(233181376885686272)
>
[18:55:02 INFO]: [DiscordSRV] - TC:hgl-films(531532134226067457)
>
[18:55:02 INFO]: [DiscordSRV] - TC:jugendgarten-diskussionen(537716651815075842)
>
[18:55:02 INFO]: [DiscordSRV] - TC:videos(188312098361704448)
>
[18:55:02 INFO]: [DiscordSRV] - TC:irgendetwas-anderes(441647625075294208)
>
[18:55:02 INFO]: [DiscordSRV] - TC:non-pianmc(486884347832696842)
>
[18:55:02 INFO]: [DiscordSRV] - TC:support(172991981771816962)
>
[18:55:02 INFO]: [DiscordSRV] - TC:tribunal(173794725982240771)
>
[18:55:02 INFO]: [DiscordSRV] - TC:shop-aufträge-bestellungen(464883401963470858)
>
[18:55:02 INFO]: [DiscordSRV] - TC:ränge-rollen(197728273822777344)
>
[18:55:02 INFO]: [DiscordSRV] - TC:administratives(366164519031930880)
>
[18:55:02 INFO]: [DiscordSRV] - TC:administratives-zum-wiki(486901600909131786)
>
[18:55:02 INFO]: [DiscordSRV] - TC:administratives-zum-forum(498177345644134430)
>
[18:55:02 INFO]: [DiscordSRV] - TC:administratives-google-sites(567383710911954944)
>
[18:55:02 INFO]: [DiscordSRV] - TC:anregungen(335158038837329922)
>
[18:55:02 INFO]: [DiscordSRV] - TC:umfragen(536536008456536074)
>
[18:55:02 INFO]: [DiscordSRV] - TC:teamchat(179100576469090304)
>
[18:55:02 INFO]: [DiscordSRV] - TC:team-minecraftchat(566016164354850821)
>
[18:55:02 INFO]: [DiscordSRV] - TC:console(462281901286096896)
>
[18:55:02 INFO]: [DiscordSRV] - TC:diskussion-über-das-weitere-fortfahren-von-revival(519168618769022996)
>
[18:55:02 INFO]: [DiscordSRV] - TC:statistische-zahlen(553583279878569984)
>
[18:55:02 INFO]: [DiscordSRV] - TC:bewerben(468124954353860628)
>
[18:55:02 INFO]: [DiscordSRV] - TC:item-erstattungen(468125323591155714)
>
[18:55:02 INFO]: [DiscordSRV] - TC:protection-antrag(468125265143529473)
>
[18:55:02 INFO]: [DiscordSRV] - TC:revival(435478201918291979)
>
[18:55:02 INFO]: [DiscordSRV] - TC:kukkies(531419678917263375)
>
[18:55:02 INFO]: [DiscordSRV] - TC:ragemode(534474915336683520)
>
[18:55:02 INFO]: [DiscordSRV] - TC:wahrheit-pflicht(561501978073759754)
>
[18:55:02 INFO]: [DiscordSRV] - TC:mee6-log(538352458989305856)
>
[18:55:02 INFO]: [DiscordSRV] - TC:loggerbot(538366608515530762)
>
[18:55:02 INFO]: [DiscordSRV] - TC:schlafzimmerschlachten(569984805299683396)
>
[18:55:02 INFO]: [DiscordSRV] - TC:gewaltauseinandersetzungen(569984921347817490)
>
[18:55:02 INFO]: [DiscordSRV] - TC:redaktion(572880312191811604)
>
[18:55:02 INFO]: [DiscordSRV] Console forwarding assigned to channel TC:console(462281901286096896)
>
[18:55:02 WARN]: java.lang.NoClassDefFoundError: github/scarsz/discordsrv/dependencies/google/common/collect/Lists
>
[18:55:02 WARN]: 	at github.scarsz.discordsrv.objects.CancellationDetector.<init>(CancellationDetector.java:42)
>
[18:55:02 WARN]: 	at github.scarsz.discordsrv.DiscordSRV.init(DiscordSRV.java:397)
>
[18:55:02 WARN]: 	at java.lang.Thread.run(Thread.java:748)
>
[18:55:02 WARN]: Caused by: java.lang.ClassNotFoundException: github.scarsz.discordsrv.dependencies.google.common.collect.Lists
>
[18:55:02 WARN]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
>
[18:55:02 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:134)
>
[18:55:02 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:80)
>
[18:55:02 WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
>
[18:55:02 WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>
[18:55:02 WARN]: 	... 3 more
>
[18:55:02 ERROR]: [DiscordSRV] DiscordSRV failed to load properly: github/scarsz/discordsrv/dependencies/google/common/collect/Lists. See ERROR/Failed to send debug report: java.io.FileNotFoundException: https://debug.scarsz.me/post for more information.
[Pterodactyl Daemon] Server marked as STOPPING
>stop

**Comment by Vankka** [comment]
Join Discord for support, https://scarsz.me/discord #support

**Comment by PianoRailways** [comment]
Please check your comment before you publish!!! The website doesn't Work!!

**Comment by Scarsz** [comment]
It was down because of me doing server migration. It works now.
