### ISSUE TITLE
Initialization/WARN]: java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class 

### ISSUE THREAD

**Issue by alvarlagerlof** [DiscordSRV/DiscordSRV#463]
This on the latest version of DiscordSRV on 1.14

```
[05:21:20] [DiscordSRV - Initialization/INFO]: [DiscordSRV] DiscordSRV is up-to-date. (06b77741bbc622d715d3ee44158b0e2516453dac)
[05:21:20] [DiscordSRV - Initialization/INFO]: [DiscordSRV] Language initialized as English
[05:21:20] [DiscordSRV - Initialization/INFO]: [DiscordSRV] ===============================================================================
[05:21:20] [DiscordSRV - Initialization/INFO]: [DiscordSRV]          Need a server host? Try PebbleHost! Plans starting at $1/GB!
[05:21:20] [DiscordSRV - Initialization/INFO]: [DiscordSRV]  Use promo code "DISCORDSRV" at checkout for 15% off your first three bills!
[05:21:20] [DiscordSRV - Initialization/INFO]: [DiscordSRV] ===============================================================================
[05:21:20] [DiscordSRV - Initialization/WARN]: java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class github/scarsz/discordsrv/dependencies/okhttp3/Authenticator. Met$
[05:21:20] [DiscordSRV - Initialization/WARN]:  at github.scarsz.discordsrv.dependencies.okhttp3.Authenticator.<clinit>(Authenticator.java:100)
[05:21:20] [DiscordSRV - Initialization/WARN]:  at github.scarsz.discordsrv.dependencies.okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.java:493)
[05:21:20] [DiscordSRV - Initialization/WARN]:  at github.scarsz.discordsrv.dependencies.jda.core.JDABuilder.build(JDABuilder.java:881)
[05:21:20] [DiscordSRV - Initialization/WARN]:  at github.scarsz.discordsrv.DiscordSRV.init(DiscordSRV.java:311)
[05:21:20] [DiscordSRV - Initialization/WARN]:  at java.base/java.lang.Thread.run(Thread.java:834)
[05:21:20] [DiscordSRV - Initialization/WARN]: com.github.kevinsawicki.http.HttpRequest$HttpRequestException: javax.net.ssl.SSLException: Received fatal alert: record_overflow
[05:21:20] [DiscordSRV - Initialization/WARN]:  at com.github.kevinsawicki.http.HttpRequest.code(HttpRequest.java:1562)
[05:21:20] [DiscordSRV - Initialization/WARN]:  at github.scarsz.discordsrv.util.DebugUtil.uploadToBin(DebugUtil.java:268)
[05:21:20] [DiscordSRV - Initialization/WARN]:  at github.scarsz.discordsrv.util.DebugUtil.uploadReport(DebugUtil.java:238)
[05:21:20] [DiscordSRV - Initialization/WARN]:  at github.scarsz.discordsrv.util.DebugUtil.run(DebugUtil.java:106)
[05:21:20] [DiscordSRV - Initialization/WARN]:  at github.scarsz.discordsrv.DiscordSRV.lambda$onEnable$2(DiscordSRV.java:187)
[05:21:20] [DiscordSRV - Initialization/WARN]:  at java.base/java.lang.Thread.dispatchUncaughtException(Thread.java:2001)
[05:21:20] [DiscordSRV - Initialization/WARN]: Caused by: javax.net.ssl.SSLException: Received fatal alert: record_overflow
[05:21:20] [DiscordSRV - Initialization/WARN]:  at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)
[05:21:20] [DiscordSRV - Initialization/WARN]:  at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
[05:21:20] [DiscordSRV - Initialization/WARN]:  at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:308)
[05:21:20] [DiscordSRV - Initialization/WARN]:  at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:285)
[05:21:20] [DiscordSRV - Initialization/WARN]:  at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:181)
[05:21:20] [DiscordSRV - Initialization/WARN]:  at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
[05:21:20] [DiscordSRV - Initialization/WARN]:  at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1155)
[05:21:20] [DiscordSRV - Initialization/WARN]:  at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1125)
[05:21:20] [DiscordSRV - Initialization/WARN]:  at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:823)
[05:21:20] [DiscordSRV - Initialization/WARN]:  at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
[05:21:20] [DiscordSRV - Initialization/WARN]:  at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
[05:21:20] [DiscordSRV - Initialization/WARN]:  at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
[05:21:20] [DiscordSRV - Initialization/WARN]:  at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:746)
[05:21:20] [DiscordSRV - Initialization/WARN]:  at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
[05:21:20] [DiscordSRV - Initialization/WARN]:  at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:717)
[05:21:20] [DiscordSRV - Initialization/WARN]:  at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1604)
[05:21:20] [DiscordSRV - Initialization/WARN]:  at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
[05:21:20] [DiscordSRV - Initialization/WARN]:  at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
[05:21:20] [DiscordSRV - Initialization/WARN]:  at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:329)
[05:21:20] [DiscordSRV - Initialization/WARN]:  at com.github.kevinsawicki.http.HttpRequest.code(HttpRequest.java:1560)
[05:21:20] [DiscordSRV - Initialization/WARN]:  ... 5 more
[05:21:20] [DiscordSRV - Initialization/ERROR]: [DiscordSRV] DiscordSRV failed to load properly: Inconsistent constant pool data in classfile for class github/scarsz/discordsrv/dependencies/okhttp3/Authenti$
```

**Comment by Scarsz** [comment]
1.16.9 only supports Java 8

**Comment by alvarlagerlof** [comment]
Ok

**Comment by xlnd47** [comment]
any idea how to downgrade from 12 to 8 without destroying my server? :)

**Comment by Vankka** [comment]
DiscordSRV supports Java 12 in the latest dev builds, you can download it here: https://ci.scarsz.me/repository/download/DiscordSRV_Build/140:id/DiscordSRV-Build-1.17.0-SNAPSHOT-104.jar

**Comment by xlnd47** [comment]
i think i cant download it without logging in

**Comment by xlnd47** [comment]
I need to login to download the latest artifact from development

**Comment by Vankka** [comment]
Click "login as guest" and try again

**Comment by xlnd47** [comment]
Ok I did, I downloaded build 103 because 104 I cant download as guest

**Comment by xlnd47** [comment]
Ok works perfect, thanks!
