### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by mrnicedonovan** [DiscordSRV/DiscordSRV#468]
```
[DiscordSRV - Channel Topic Updater/WARN]: java.lang.NullPointerException
[16:07:27] [DiscordSRV - Channel Topic Updater/WARN]:   at github.scarsz.discordsrv.hooks.vanish.EssentialsHook.isVanished(EssentialsHook.java:32)
[16:07:27] [DiscordSRV - Channel Topic Updater/WARN]:   at github.scarsz.discordsrv.util.PlayerUtil.isVanished(PlayerUtil.java:135)
[16:07:27] [DiscordSRV - Channel Topic Updater/WARN]:   at github.scarsz.discordsrv.util.PlayerUtil.lambda$getOnlinePlayers$0(PlayerUtil.java:69)
[16:07:27] [DiscordSRV - Channel Topic Updater/WARN]:   at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
[16:07:27] [DiscordSRV - Channel Topic Updater/WARN]:   at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
[16:07:27] [DiscordSRV - Channel Topic Updater/WARN]:   at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[16:07:27] [DiscordSRV - Channel Topic Updater/WARN]:   at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[16:07:27] [DiscordSRV - Channel Topic Updater/WARN]:   at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
[16:07:27] [DiscordSRV - Channel Topic Updater/WARN]:   at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[16:07:27] [DiscordSRV - Channel Topic Updater/WARN]:   at java.util.stream.ReferencePipeline.collect(Unknown Source)
[16:07:27] [DiscordSRV - Channel Topic Updater/WARN]:   at github.scarsz.discordsrv.util.PlayerUtil.getOnlinePlayers(PlayerUtil.java:70)
[16:07:27] [DiscordSRV - Channel Topic Updater/WARN]:   at github.scarsz.discordsrv.objects.threads.ChannelTopicUpdater.applyPlaceholders(ChannelTopicUpdater.java:81)
[16:07:27] [DiscordSRV - Channel Topic Updater/WARN]:   at github.scarsz.discordsrv.objects.threads.ChannelTopicUpdater.run(ChannelTopicUpdater.java:45)
```

**Comment by Vankka** [comment]
It's a problem with your essentials plugin (it may or may not be installed or working). If you'd like further assistance please join Discord here: https://scarsz.me/discord
