### ISSUE TITLE
Crash on load: record_overflow

### ISSUE THREAD

**Issue by Sylvyrfysh** [DiscordSRV/DiscordSRV#478]
Crash happens on load after configure.

```
[23:19:00 INFO]: [DiscordSRV] Enabling DiscordSRV v1.16.9
[23:19:00 INFO]: Done (109.507s)! For help, type "help"
[23:19:00 INFO]: Timings Reset
[23:19:05 INFO]: [DiscordSRV] DiscordSRV is up-to-date. (06b77741bbc622d715d3ee44158b0e2516453dac)
[23:19:05 INFO]: [DiscordSRV] Language initialized as English
[23:19:05 INFO]: [DiscordSRV] ===============================================================================
[23:19:05 INFO]: [DiscordSRV]          Need a server host? Try PebbleHost! Plans starting at $1/GB!
[23:19:05 INFO]: [DiscordSRV]  Use promo code "DISCORDSRV" at checkout for 15% off your first three bills!
[23:19:05 INFO]: [DiscordSRV] ===============================================================================
[23:19:05 WARN]: java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class github/scarsz/discordsrv/dependencies/okhttp3/Authenticator. Method lambda$static$0(Lgithub/scarsz/discordsrv/dependencies/okhttp3/Route;Lgithub/scarsz/discordsrv/dependencies/okhttp3/Response;)Lgithub/scarsz/discordsrv/dependencies/okhttp3/Request; at index 35 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
[23:19:05 WARN]:        at github.scarsz.discordsrv.dependencies.okhttp3.Authenticator.<clinit>(Authenticator.java:100)
[23:19:05 WARN]:        at github.scarsz.discordsrv.dependencies.okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.java:493)
[23:19:05 WARN]:        at github.scarsz.discordsrv.dependencies.jda.core.JDABuilder.build(JDABuilder.java:881)
[23:19:05 WARN]:        at github.scarsz.discordsrv.DiscordSRV.init(DiscordSRV.java:311)
[23:19:05 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[23:19:06 WARN]: com.github.kevinsawicki.http.HttpRequest$HttpRequestException: javax.net.ssl.SSLException: Received fatal alert: record_overflow
[23:19:06 WARN]:        at com.github.kevinsawicki.http.HttpRequest.code(HttpRequest.java:1562)
[23:19:06 WARN]:        at github.scarsz.discordsrv.util.DebugUtil.uploadToBin(DebugUtil.java:268)
[23:19:06 WARN]:        at github.scarsz.discordsrv.util.DebugUtil.uploadReport(DebugUtil.java:238)
[23:19:06 WARN]:        at github.scarsz.discordsrv.util.DebugUtil.run(DebugUtil.java:106)
[23:19:06 WARN]:        at github.scarsz.discordsrv.DiscordSRV.lambda$onEnable$2(DiscordSRV.java:187)
[23:19:06 WARN]:        at java.base/java.lang.Thread.dispatchUncaughtException(Thread.java:2001)
[23:19:06 WARN]: Caused by: javax.net.ssl.SSLException: Received fatal alert: record_overflow
[23:19:06 WARN]:        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)
[23:19:06 WARN]:        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
[23:19:06 WARN]:        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:308)
[23:19:06 WARN]:        at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:285)
[23:19:06 WARN]:        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:181)
[23:19:06 WARN]:        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
[23:19:06 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1155)
[23:19:06 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1125)
[23:19:06 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:823)
[23:19:06 WARN]:        at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
[23:19:06 WARN]:        at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
[23:19:06 WARN]:        at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
[23:19:06 WARN]:        at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:746)
[23:19:06 WARN]:        at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
[23:19:06 WARN]:        at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:717)
[23:19:06 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1604)
[23:19:06 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
[23:19:06 WARN]:        at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
[23:19:06 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:329)
[23:19:06 WARN]:        at com.github.kevinsawicki.http.HttpRequest.code(HttpRequest.java:1560)
[23:19:06 WARN]:        ... 5 more
[23:19:06 ERROR]: [DiscordSRV] DiscordSRV failed to load properly: Inconsistent constant pool data in classfile for class github/scarsz/discordsrv/dependencies/okhttp3/Authenticator. Method lambda$static$0(Lgithub/scarsz/discordsrv/dependencies/okhttp3/Route;Lgithub/scarsz/discordsrv/dependencies/okhttp3/Response;)Lgithub/scarsz/discordsrv/dependencies/okhttp3/Request; at index 35 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef. See ERROR/Failed to send debug report: javax.net.ssl.SSLException: Received fatal alert: record_overflow for more information.
```

Set up was performed as directed by `https://github.com/DiscordSRV/DiscordSRV/wiki/Installation`

**Comment by Vankka** [comment]
Get the latest dev build from: https://ci.scarsz.me/viewLog.html?buildId=123&buildTypeId=DiscordSRV_Build&tab=artifacts&guest=1
