### ISSUE TITLE
DiscordSRV doesn't link with discord

### ISSUE THREAD

**Issue by At0micA55** [DiscordSRV/DiscordSRV#492]
Hello so my issue is that... after moving to 1.14.2, upgrading the plugin and doing a full /stop then restart, my plugin shows me a error... and doesn't sync with Discord :/ My config is alright cause a minute before everything was fine except my console not updating itself (in discord).  The plugin seem fine cause it all work if i do /discord in game or in my console, but it is not updating with Discord, like the chat is not working in both "directions" and the console is not updating... 

Here is the error;
```
[18:39:28] [DiscordSRV - Initialization/INFO]: [DiscordSRV] Language initialized as English
[18:39:28] [DiscordSRV - Initialization/INFO]: [DiscordSRV] §8===============================================================================
[18:39:28] [DiscordSRV - Initialization/INFO]: [DiscordSRV] §a         Need a server host? Try PebbleHost! Plans starting at $1/GB!
[18:39:28] [DiscordSRV - Initialization/INFO]: [DiscordSRV] §a Use promo code "DISCORDSRV" at checkout for 15% off your first three bills!
[18:39:28] [DiscordSRV - Initialization/INFO]: [DiscordSRV] §8===============================================================================
[18:39:29] [DiscordSRV - Initialization/WARN]: java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class github/scarsz/discordsrv/dependencies/okhttp3/Authenticator. Method lambda$static$0(Lgithub/scarsz/discordsrv/dependencies/okhttp3/Route;Lgithub/scarsz/discordsrv/dependencies/okhttp3/Response;)Lgithub/scarsz/discordsrv/dependencies/okhttp3/Request; at index 35 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
[18:39:29] [DiscordSRV - Initialization/WARN]: 	at github.scarsz.discordsrv.dependencies.okhttp3.Authenticator.<clinit>(Authenticator.java:100)
[18:39:29] [DiscordSRV - Initialization/WARN]: 	at github.scarsz.discordsrv.dependencies.okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.java:493)
[18:39:29] [DiscordSRV - Initialization/WARN]: 	at github.scarsz.discordsrv.dependencies.jda.core.JDABuilder.build(JDABuilder.java:881)
[18:39:29] [DiscordSRV - Initialization/WARN]: 	at github.scarsz.discordsrv.DiscordSRV.init(DiscordSRV.java:311)
[18:39:29] [DiscordSRV - Initialization/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[18:39:29] [DiscordSRV - Initialization/WARN]: com.github.kevinsawicki.http.HttpRequest$HttpRequestException: javax.net.ssl.SSLException: Received fatal alert: record_overflow
[18:39:29] [DiscordSRV - Initialization/WARN]: 	at com.github.kevinsawicki.http.HttpRequest.code(HttpRequest.java:1562)
[18:39:29] [DiscordSRV - Initialization/WARN]: 	at github.scarsz.discordsrv.util.DebugUtil.uploadToBin(DebugUtil.java:268)
[18:39:29] [DiscordSRV - Initialization/WARN]: 	at github.scarsz.discordsrv.util.DebugUtil.uploadReport(DebugUtil.java:238)
[18:39:29] [DiscordSRV - Initialization/WARN]: 	at github.scarsz.discordsrv.util.DebugUtil.run(DebugUtil.java:106)
[18:39:29] [DiscordSRV - Initialization/WARN]: 	at github.scarsz.discordsrv.DiscordSRV.lambda$onEnable$2(DiscordSRV.java:187)
[18:39:29] [DiscordSRV - Initialization/WARN]: 	at java.base/java.lang.Thread.dispatchUncaughtException(Thread.java:2001)
[18:39:29] [DiscordSRV - Initialization/WARN]: Caused by: javax.net.ssl.SSLException: Received fatal alert: record_overflow
[18:39:29] [DiscordSRV - Initialization/WARN]: 	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)
[18:39:29] [DiscordSRV - Initialization/WARN]: 	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
[18:39:29] [DiscordSRV - Initialization/WARN]: 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:308)
[18:39:29] [DiscordSRV - Initialization/WARN]: 	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:285)
[18:39:29] [DiscordSRV - Initialization/WARN]: 	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:181)
[18:39:29] [DiscordSRV - Initialization/WARN]: 	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
[18:39:29] [DiscordSRV - Initialization/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1155)
[18:39:29] [DiscordSRV - Initialization/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1125)
[18:39:29] [DiscordSRV - Initialization/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:823)
[18:39:29] [DiscordSRV - Initialization/WARN]: 	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
[18:39:29] [DiscordSRV - Initialization/WARN]: 	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
[18:39:29] [DiscordSRV - Initialization/WARN]: 	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
[18:39:29] [DiscordSRV - Initialization/WARN]: 	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:746)
[18:39:29] [DiscordSRV - Initialization/WARN]: 	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
[18:39:29] [DiscordSRV - Initialization/WARN]: 	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:717)
[18:39:29] [DiscordSRV - Initialization/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1604)
[18:39:29] [DiscordSRV - Initialization/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
[18:39:29] [DiscordSRV - Initialization/WARN]: 	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
[18:39:29] [DiscordSRV - Initialization/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:329)
[18:39:29] [DiscordSRV - Initialization/WARN]: 	at com.github.kevinsawicki.http.HttpRequest.code(HttpRequest.java:1560)
[18:39:29] [DiscordSRV - Initialization/WARN]: 	... 5 more
[18:39:29] [DiscordSRV - Initialization/ERROR]: [DiscordSRV] DiscordSRV failed to load properly: Inconsistent constant pool data in classfile for class github/scarsz/discordsrv/dependencies/okhttp3/Authenticator. Method lambda$static$0(Lgithub/scarsz/discordsrv/dependencies/okhttp3/Route;Lgithub/scarsz/discordsrv/dependencies/okhttp3/Response;)Lgithub/scarsz/discordsrv/dependencies/okhttp3/Request; at index 35 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef. See ERROR/Failed to send debug report: javax.net.ssl.SSLException: Received fatal alert: record_overflow for more information.
```

Hope you have a great day and that this help fix something ^_^ 
At0micA55

**Comment by Scarsz** [comment]
This is a bug in your installed JRE. I'd suggest using JRE 8.

**Comment by At0micA55** [comment]
In linux if i do java -version i get
```
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu218.10.1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu218.10.1, mixed mode, sharing)
```

So i am using Java 11...

**Comment by Scarsz** [comment]
> ```
> openjdk version "11.0.3" 2019-04-16
> OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu218.10.1)
> OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu218.10.1, mixed mode, sharing)
> ```
> 
> So i am using Java 11...

Which isn't JRE 8. This is an OpenJDK bug. Use Java 8.

**Comment by At0micA55** [comment]
Ok how can i use Java 8 or higher on Linux ?

**Comment by Scarsz** [comment]
Google has many tutorials

**Comment by At0micA55** [comment]
Why everything was working in 1.13.2 before tho and not working now in 1.14.2 ? :/ No Bug at all in 1.13.2
