### ISSUE TITLE
Fresh install (with config) crashes on start using spigot 1.14.3

### ISSUE THREAD

**Issue by JPaulMora** [DiscordSRV/DiscordSRV#497]
```
[08:14:12] [DiscordSRV - Initialization/INFO]: [DiscordSRV] DiscordSRV is up-to-date. (06b77741bbc622d715d3ee44158b0e2516453dac)
[08:14:12] [DiscordSRV - Initialization/INFO]: [DiscordSRV] Language initialized as English
[08:14:12] [DiscordSRV - Initialization/INFO]: [DiscordSRV] §8===============================================================================
[08:14:12] [DiscordSRV - Initialization/INFO]: [DiscordSRV] §a         Need a server host? Try PebbleHost! Plans starting at $1/GB!
[08:14:12] [DiscordSRV - Initialization/INFO]: [DiscordSRV] §a Use promo code "DISCORDSRV" at checkout for 15% off your first three bills!
[08:14:12] [DiscordSRV - Initialization/INFO]: [DiscordSRV] §8===============================================================================
[08:14:12] [DiscordSRV - Initialization/WARN]: java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class github/scarsz/discordsrv/dependencies/okhttp3/Authenticator. Method lambda$static$0(Lgithub/scarsz/discordsrv/dependencies/okhttp3/Route;Lgithub/scarsz/discordsrv/dependencies/okhttp3/Response;)Lgithub/scarsz/discordsrv/dependencies/okhttp3/Request; at index 35 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
[08:14:12] [DiscordSRV - Initialization/WARN]:  at github.scarsz.discordsrv.dependencies.okhttp3.Authenticator.<clinit>(Authenticator.java:100)
[08:14:12] [DiscordSRV - Initialization/WARN]:  at github.scarsz.discordsrv.dependencies.okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.java:493)
[08:14:12] [DiscordSRV - Initialization/WARN]:  at github.scarsz.discordsrv.dependencies.jda.core.JDABuilder.build(JDABuilder.java:881)
[08:14:12] [DiscordSRV - Initialization/WARN]:  at github.scarsz.discordsrv.DiscordSRV.init(DiscordSRV.java:311)
[08:14:12] [DiscordSRV - Initialization/WARN]:  at java.base/java.lang.Thread.run(Thread.java:834)
[08:14:13] [DiscordSRV - Initialization/WARN]: com.github.kevinsawicki.http.HttpRequest$HttpRequestException: javax.net.ssl.SSLException: Received fatal alert: record_overflow
[08:14:13] [DiscordSRV - Initialization/WARN]:  at com.github.kevinsawicki.http.HttpRequest.code(HttpRequest.java:1562)
[08:14:13] [DiscordSRV - Initialization/WARN]:  at github.scarsz.discordsrv.util.DebugUtil.uploadToBin(DebugUtil.java:268)
[08:14:13] [DiscordSRV - Initialization/WARN]:  at github.scarsz.discordsrv.util.DebugUtil.uploadReport(DebugUtil.java:238)
[08:14:13] [DiscordSRV - Initialization/WARN]:  at github.scarsz.discordsrv.util.DebugUtil.run(DebugUtil.java:106)
[08:14:13] [DiscordSRV - Initialization/WARN]:  at github.scarsz.discordsrv.DiscordSRV.lambda$onEnable$2(DiscordSRV.java:187)
[08:14:13] [DiscordSRV - Initialization/WARN]:  at java.base/java.lang.Thread.dispatchUncaughtException(Thread.java:2001)
[08:14:13] [DiscordSRV - Initialization/WARN]: Caused by: javax.net.ssl.SSLException: Received fatal alert: record_overflow
[08:14:13] [DiscordSRV - Initialization/WARN]:  at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)
[08:14:13] [DiscordSRV - Initialization/WARN]:  at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
[08:14:13] [DiscordSRV - Initialization/WARN]:  at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:308)
[08:14:13] [DiscordSRV - Initialization/WARN]:  at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:285)
[08:14:13] [DiscordSRV - Initialization/WARN]:  at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:181)
[08:14:13] [DiscordSRV - Initialization/WARN]:  at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
[08:14:13] [DiscordSRV - Initialization/WARN]:  at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1155)
[08:14:13] [DiscordSRV - Initialization/WARN]:  at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1125)
[08:14:13] [DiscordSRV - Initialization/WARN]:  at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:823)
[08:14:13] [DiscordSRV - Initialization/WARN]:  at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
[08:14:13] [DiscordSRV - Initialization/WARN]:  at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
[08:14:13] [DiscordSRV - Initialization/WARN]:  at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
[08:14:13] [DiscordSRV - Initialization/WARN]:  at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:746)
[08:14:13] [DiscordSRV - Initialization/WARN]:  at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
[08:14:13] [DiscordSRV - Initialization/WARN]:  at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:717)
[08:14:13] [DiscordSRV - Initialization/WARN]:  at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1604)
[08:14:13] [DiscordSRV - Initialization/WARN]:  at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
[08:14:13] [DiscordSRV - Initialization/WARN]:  at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
[08:14:13] [DiscordSRV - Initialization/WARN]:  at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:329)
[08:14:13] [DiscordSRV - Initialization/WARN]:  at com.github.kevinsawicki.http.HttpRequest.code(HttpRequest.java:1560)
[08:14:13] [DiscordSRV - Initialization/WARN]:  ... 5 more
[08:14:13] [DiscordSRV - Initialization/ERROR]: [DiscordSRV] DiscordSRV failed to load properly: Inconsistent constant pool data in classfile for class github/scarsz/discordsrv/dependencies/okhttp3/Authenticator. Method lambda$static$0(Lgithub/scarsz/discordsrv/dependencies/okhttp3/Route;Lgithub/scarsz/discordsrv/dependencies/okhttp3/Response;)Lgithub/scarsz/discordsrv/dependencies/okhttp3/Request; at index 35 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef. See ERROR/Failed to send debug report: javax.net.ssl.SSLException: Received fatal alert: record_overflow for more information.
```

**Comment by Scarsz** [comment]
Already been fixed in dev builds https://ci.scarsz.me/guestAuth/app/rest/builds/id:94/artifacts/content/DiscordSRV-Build-1.17.0-SNAPSHOT-112.jar

**Comment by JPaulMora** [comment]
Officially my shortest lived issue, thanks!
