### ISSUE TITLE
There was an exception while executing a REST request

### ISSUE THREAD

**Issue by Steveycat** [DiscordSRV/DiscordSRV#498]
I've recently switch server host and now see this error thrown by DiscordSRV. It was working fine on my VM but no longer works on the new server hosting website. What is the potential cause of this error and is there a work around?

Plugins used and there version
- Spigot 1.14.3
- CoreProtect-2.17.5
- CustomJoinLeaveMessage-1.6.5
- DiscordSRV-Build-1.16.9
- Dynmap-3.0-beta-4-spigot
- Vault

Here is the start up logs
```
06.07 02:08:04 [Server] Server thread/INFO [CoreProtect] Enabling CoreProtect v2.17.5

06.07 02:08:05 [Server] Server thread/INFO [CoreProtect] CoreProtect has been successfully enabled!

06.07 02:08:05 [Server] Server thread/INFO [CoreProtect] Using SQLite for data storage.

06.07 02:08:05 [Server] Server thread/INFO [dynmap] Enabling dynmap v3.0-beta-4-213

06.07 02:08:05 [Server] Server thread/INFO [dynmap] Using Bukkit Permissions (superperms) for access 
control

06.07 02:08:05 [Server] Server thread/INFO [dynmap] Web interface permissions only available for online users

06.07 02:08:05 [Server] Server thread/INFO [dynmap] Mod Support processing completed

06.07 02:08:05 [Server] Server thread/INFO [dynmap] Loaded 25 shaders.

06.07 02:08:05 [Server] Server thread/INFO [dynmap] Loaded 82 perspectives.

06.07 02:08:05 [Server] Server thread/INFO [dynmap] Loaded 14 lightings.

06.07 02:08:05 [Server] Server thread/INFO [dynmap] Web server started on address 
145.239.204.174:2719

06.07 02:08:05 [Server] Server thread/INFO [dynmap] version 3.0-beta-4-213 is enabled - core version 3.0-beta-4-213

06.07 02:08:05 [Server] Server thread/INFO [dynmap] For support, visit https://forums.dynmap.us

06.07 02:08:05 [Server] Server thread/INFO [dynmap] To report or track bugs, visit https://github.com/webbukkit/dynmap/issues

06.07 02:08:05 [Server] Server thread/INFO [dynmap] Loaded 3 maps of world 'survival'.

06.07 02:08:05 [Server] Server thread/INFO [dynmap] Loaded 2 maps of world 'survival_nether'.

06.07 02:08:05 [Server] Server thread/INFO [dynmap] Loaded 2 maps of world 'survival_the_end'.

06.07 02:08:05 [Server] Server thread/INFO [dynmap] Enabled

06.07 02:08:05 [Server] Server thread/INFO [CustomJoinLeaveMessage] Enabling 
CustomJoinLeaveMessage v1.6.5

06.07 02:08:05 [Server] Server thread/INFO [CustomJoinLeaveMessage] Custom join/leave message enabled

06.07 02:08:05 [Server] Server thread/INFO [DiscordSRV] Enabling DiscordSRV v1.16.9

06.07 02:08:05 [Server] Server thread/INFO Server permissions file permissions.yml is empty, ignoring it

06.07 02:08:05 [Server] Startup Done (6.068s)! For help, type "help"

06.07 02:08:05 [Server] Craft Scheduler Thread - 1/INFO [Vault] Checking for Updates ...

06.07 02:08:06 [Server] DiscordSRV - Initialization/INFO [DiscordSRV] Language initialized as English

06.07 02:08:06 [Server] DiscordSRV - Initialization/ERROR [DiscordSRV] Failed to fetch URL 
https://api.github.com/repos/Scarsz/DiscordSRV/compare/1b6e3bf8ee2f7ddaf3ac71e550a1cac17d238668...06b77741bbc622d715d3ee44158b0e2516453dac: Connection refused (Connection refused)

06.07 02:08:06 [Server] DiscordSRV - Initialization/WARN [DiscordSRV] Update check failed: null

06.07 02:08:06 [Server] DiscordSRV - Initialization/INFO [DiscordSRV] ===============================================================================

06.07 02:08:06 [Server] DiscordSRV - Initialization/INFO [DiscordSRV]  Need a server host? Try PebbleHost! Plans starting at $1/GB!

06.07 02:08:06 [Server] DiscordSRV - Initialization/INFO [DiscordSRV]  Use promo code "DISCORDSRV" at checkout for 15% off your first three bills!

06.07 02:08:06 [Server] DiscordSRV - Initialization/INFO [DiscordSRV] ===============================================================================

06.07 02:08:06 [Server] JDA RateLimit-Worker 1/ERROR [DiscordSRV] [JDA] There was an exception while executing a REST request

06.07 02:08:06 [Server] Server thread/INFO You are on the latest version of CustomJoinLeaveMessage: 1.6.5

06.07 02:08:06 [Server] DiscordSRV - Initialization/ERROR [DiscordSRV] An unknown error occurred building JDA...

06.07 02:08:06 [Server] DiscordSRV - Initialization/WARN github.scarsz.discordsrv.dependencies.jda.core.exceptions.ErrorResponseException: -1: java.net.ConnectException

06.07 02:08:06 [Server] DiscordSRV - Initialization/WARN at github.scarsz.discordsrv.dependencies.jda.core.exceptions.ErrorResponseException.create(ErrorResponseException.java:150)

06.07 02:08:06 [Server] DiscordSRV - Initialization/WARN at github.scarsz.discordsrv.dependencies.jda.core.requests.Request.onFailure(Request.java:96)

06.07 02:08:06 [Server] DiscordSRV - Initialization/WARN at github.scarsz.discordsrv.dependencies.jda.core.utils.SessionControllerAdapter$1.handleResponse(SessionControllerAdapter.java:89)

06.07 02:08:06 [Server] DiscordSRV - Initialization/WARN at github.scarsz.discordsrv.dependencies.jda.core.requests.Request.handleResponse(Request.java:184)

06.07 02:08:06 [Server] DiscordSRV - Initialization/WARN at github.scarsz.discordsrv.dependencies.jda.core.requests.Requester.execute(Requester.java:242)

06.07 02:08:06 [Server] DiscordSRV - Initialization/WARN at github.scarsz.discordsrv.dependencies.jda.core.requests.Requester.execute(Requester.java:133)

06.07 02:08:06 [Server] DiscordSRV - Initialization/WARN at github.scarsz.discordsrv.dependencies.jda.core.requests.Requester.execute(Requester.java:116)

06.07 02:08:06 [Server] DiscordSRV - Initialization/WARN at github.scarsz.discordsrv.dependencies.jda.core.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimit
er.java:350)

06.07 02:08:06 [Server] DiscordSRV - Initialization/WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

06.07 02:08:06 [Server] DiscordSRV - Initialization/WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)

06.07 02:08:06 [Server] DiscordSRV - Initialization/WARN at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)

06.07 02:08:06 [Server] DiscordSRV - Initialization/WARN at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)

06.07 02:08:06 [Server] DiscordSRV - Initialization/WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

06.07 02:08:06 [Server] DiscordSRV - Initialization/WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

06.07 02:08:06 [Server] DiscordSRV - Initialization/WARN at java.lang.Thread.run(Thread.java:748)

06.07 02:08:06 [Server] DiscordSRV - Initialization/WARN Caused by: java.net.ConnectException: Failed to connect to discordapp.com/162.159.133.233:443

06.07 02:08:06 [Server] DiscordSRV - Initialization/WARN at github.scarsz.discordsrv.dependencies.okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:249)

06.07 02:08:06 [Server] DiscordSRV - Initialization/WARN at github.scarsz.discordsrv.dependencies.okhttp3.internal.connection.RealConnection.connect(RealConnection.java:167)

06.07 02:08:06 [Server] DiscordSRV - Initialization/WARN at github.scarsz.discordsrv.dependencies.okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
```

**Comment by Scarsz** [comment]
Your server is failing to connect to Discord, nothing we can do about this

I’d try to see if you’re able to ping discordapp.com from the command line
