### ISSUE TITLE
Invalid plugin.yml, zip file is empty

### ISSUE THREAD

**Issue by Minecon724** [DiscordSRV/DiscordSRV#524]
I want to update plugin to version 1.17.1 from 1.16.9, but I recieve this error:

`[15:16:22] [Server thread/ERROR]: Could not load 'plugins/DiscordSRV-Build-1.17.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:160) ~[mc.jar:git-Spigot-eb3d921-2b93d83]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [mc.jar:git-Spigot-eb3d921-2b93d83]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:305) [mc.jar:git-Spigot-eb3d921-2b93d83]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [mc.jar:git-Spigot-eb3d921-2b93d83]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [mc.jar:git-Spigot-eb3d921-2b93d83]
	at java.lang.Thread.run(Thread.java:844) [?:?]
Caused by: java.util.zip.ZipException: zip file is empty
	at java.util.zip.ZipFile$Source.zerror(ZipFile.java:1252) ~[?:?]
	at java.util.zip.ZipFile$Source.findEND(ZipFile.java:1072) ~[?:?]
	at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1160) ~[?:?]
	at java.util.zip.ZipFile$Source.<init>(ZipFile.java:997) ~[?:?]
	at java.util.zip.ZipFile$Source.get(ZipFile.java:960) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:216) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:148) ~[?:?]
	at java.util.jar.JarFile.<init>(JarFile.java:324) ~[?:?]
	at java.util.jar.JarFile.<init>(JarFile.java:295) ~[?:?]
	at java.util.jar.JarFile.<init>(JarFile.java:261) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:148) ~[mc.jar:git-Spigot-eb3d921-2b93d83]
	... 5 more`

But when I install the older version, I get the same error.

Please help!

**Comment by Vankka** [comment]
Error on your end, try a different method of downloading the file
