### ISSUE TITLE
crashes on start using spigot 1.12.2

### ISSUE THREAD

**Issue by AiSuode** [DiscordSRV/DiscordSRV#543]
```
org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:1988)
[14:23:47 WARN]:        at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1960)
[14:23:47 WARN]:        at org.apache.logging.log4j.spi.AbstractLogger.info(AbstractLogger.java:1307)
[14:23:47 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.util.ForwardLogHandler.publish(ForwardLogHandler.java:37)
[14:23:47 WARN]:        at java.util.logging.Logger.log(Unknown Source)
[14:23:47 WARN]:        at org.slf4j.impl.JDK14LoggerAdapter.log(JDK14LoggerAdapter.java:582)
[14:23:47 WARN]:        at org.slf4j.impl.JDK14LoggerAdapter.info(JDK14LoggerAdapter.java:277)
[14:23:47 WARN]:        at github.scarsz.discordsrv.dependencies.jda.core.entities.impl.JDAImpl.login(JDAImpl.java:214)
[14:23:47 WARN]:        at github.scarsz.discordsrv.dependencies.jda.core.JDABuilder.build(JDABuilder.java:913)
[14:23:47 WARN]:        at github.scarsz.discordsrv.DiscordSRV.init(DiscordSRV.jav
```

**Comment by Scarsz** [comment]
This is nowhere near a full stack trace. Submit an actual one.
