### ISSUE TITLE
Cannot add new rank to user

### ISSUE THREAD

**Issue by iBrady** [DiscordSRV/DiscordSRV#563]
Hi!

Since a week, whenever a player tries to link their account to Discord, it does not give the "Verified" role anymore. It was working perfectly fine before..

I'm getting this error
```
[19:39:53] [Craft Scheduler Thread - 51/WARN]: [DiscordSRV] Plugin DiscordSRV v1.16.9 generated an exception while executing task 186
java.lang.IllegalArgumentException: Provided Member issuer and Role target must be from the same Guild!
	at github.scarsz.discordsrv.dependencies.jda.core.utils.PermissionUtil.canInteract(PermissionUtil.java:82) ~[?:?]
	at github.scarsz.discordsrv.dependencies.jda.core.entities.impl.MemberImpl.canInteract(MemberImpl.java:195) ~[?:?]
	at github.scarsz.discordsrv.util.DiscordUtil.lambda$modifyRolesOfMember$10(DiscordUtil.java:549) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_222]
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556) ~[?:1.8.0_222]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_222]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_222]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_222]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_222]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[?:1.8.0_222]
	at github.scarsz.discordsrv.util.DiscordUtil.modifyRolesOfMember(DiscordUtil.java:549) ~[?:?]
	at github.scarsz.discordsrv.util.GroupSynchronizationUtil.reSyncGroups(GroupSynchronizationUtil.java:103) ~[?:?]
	at github.scarsz.discordsrv.util.GroupSynchronizationUtil.reSyncGroups(GroupSynchronizationUtil.java:42) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_222]
	at github.scarsz.discordsrv.util.GroupSynchronizationUtil.lambda$static$0(GroupSynchronizationUtil.java:38) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Paper-1618]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```

This is in my configuration file:
``` MinecraftDiscordAccountLinkedRoleNameToAddUserTo: "Verified"```

**Comment by pkrok01** [comment]
1. Update to the [latest release of DiscordSRV](https://github.com/DiscordSRV/DiscordSRV/releases)
2. `Provided Member issuer and Role target must be from the same Guild!`
Bot is in multiple servers; This isn't supported.
