### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by PoProstuMieciek** [DiscordSRV/DiscordSRV#566]
After updating DiscordSRV from Build1.17.1 to Build1.18 and running PaperSpigot 1.14.4 server I get error:

```
[12:25:30] [DiscordSRV - Initialization/WARN]: java.lang.NullPointerException
[12:25:30] [DiscordSRV - Initialization/WARN]: 	at github.scarsz.configuralize.Source.isLanguageAvailable(Source.java:48)
[12:25:30] [DiscordSRV - Initialization/WARN]: 	at github.scarsz.configuralize.DynamicConfig.lambda$isLanguageAvailable$0(DynamicConfig.java:42)
[12:25:30] [DiscordSRV - Initialization/WARN]: 	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
[12:25:30] [DiscordSRV - Initialization/WARN]: 	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
[12:25:30] [DiscordSRV - Initialization/WARN]: 	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
[12:25:30] [DiscordSRV - Initialization/WARN]: 	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
[12:25:30] [DiscordSRV - Initialization/WARN]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
[12:25:30] [DiscordSRV - Initialization/WARN]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
[12:25:30] [DiscordSRV - Initialization/WARN]: 	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
[12:25:30] [DiscordSRV - Initialization/WARN]: 	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
[12:25:30] [DiscordSRV - Initialization/WARN]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[12:25:30] [DiscordSRV - Initialization/WARN]: 	at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:454)
[12:25:30] [DiscordSRV - Initialization/WARN]: 	at github.scarsz.configuralize.DynamicConfig.isLanguageAvailable(DynamicConfig.java:42)
[12:25:30] [DiscordSRV - Initialization/WARN]: 	at github.scarsz.discordsrv.DiscordSRV.init(DiscordSRV.java:259)
[12:25:30] [DiscordSRV - Initialization/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[12:25:30] [DiscordSRV - Initialization/WARN]: java.lang.NullPointerException
[12:25:30] [DiscordSRV - Initialization/WARN]: 	at github.scarsz.configuralize.DynamicConfig.lambda$dget$1(DynamicConfig.java:104)
[12:25:30] [DiscordSRV - Initialization/WARN]: 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[12:25:30] [DiscordSRV - Initialization/WARN]: 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
[12:25:30] [DiscordSRV - Initialization/WARN]: 	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
[12:25:30] [DiscordSRV - Initialization/WARN]: 	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
[12:25:30] [DiscordSRV - Initialization/WARN]: 	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
[12:25:30] [DiscordSRV - Initialization/WARN]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
[12:25:30] [DiscordSRV - Initialization/WARN]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
[12:25:30] [DiscordSRV - Initialization/WARN]: 	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
[12:25:30] [DiscordSRV - Initialization/WARN]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[12:25:30] [DiscordSRV - Initialization/WARN]: 	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
[12:25:30] [DiscordSRV - Initialization/WARN]: 	at github.scarsz.configuralize.DynamicConfig.dget(DynamicConfig.java:106)
[12:25:30] [DiscordSRV - Initialization/WARN]: 	at github.scarsz.configuralize.DynamicConfig.getString(DynamicConfig.java:169)
[12:25:30] [DiscordSRV - Initialization/WARN]: 	at github.scarsz.discordsrv.util.DebugUtil.run(DebugUtil.java:66)
[12:25:30] [DiscordSRV - Initialization/WARN]: 	at github.scarsz.discordsrv.util.DebugUtil.run(DebugUtil.java:56)
[12:25:30] [DiscordSRV - Initialization/WARN]: 	at github.scarsz.discordsrv.DiscordSRV.lambda$onEnable$3(DiscordSRV.java:227)
[12:25:30] [DiscordSRV - Initialization/WARN]: 	at java.lang.Thread.dispatchUncaughtException(Thread.java:1959)
[12:25:30] [DiscordSRV - Initialization/ERROR]: [DiscordSRV] DiscordSRV failed to load properly: null. See Failed to collect debug information: null. Check the console for further details. for more information.
```

**Comment by Scarsz** [comment]
already fixed in https://github.com/DiscordSRV/DiscordSRV/commit/d7781b7dbe7ea32982aa7ea1d349eb7192adb042


https://lol.scarsz.me/ygBWLs/DiscordSRV-Build-1.18.1-SNAPSHOT.jar
