### ISSUE TITLE
MC 1.15 Spigot issues

### ISSUE THREAD

**Issue by MJRLegends** [DiscordSRV/DiscordSRV#587]
```
[Tue, 10. Dec 2019 23:09:56 EST WARN] java.lang.NoClassDefFoundError: org/bukkit/event/player/PlayerAchievementAwardedEvent
[Tue, 10. Dec 2019 23:09:56 EST WARN]     at github.scarsz.discordsrv.listeners.PlayerAchievementsListener.<init>(PlayerAchievementsListener.java:35)
[Tue, 10. Dec 2019 23:09:56 EST WARN]     at github.scarsz.discordsrv.DiscordSRV.init(DiscordSRV.java:583)
[Tue, 10. Dec 2019 23:09:56 EST WARN]     at java.lang.Thread.run(Thread.java:748)
[Tue, 10. Dec 2019 23:09:56 EST WARN] Caused by: java.lang.ClassNotFoundException: org.bukkit.event.player.PlayerAchievementAwardedEvent
[Tue, 10. Dec 2019 23:09:56 EST WARN]     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[Tue, 10. Dec 2019 23:09:56 EST WARN]     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81)
[Tue, 10. Dec 2019 23:09:56 EST WARN]     at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[Tue, 10. Dec 2019 23:09:56 EST WARN]     at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[Tue, 10. Dec 2019 23:09:56 EST WARN]     ... 3 more
[Tue, 10. Dec 2019 23:09:57 EST ERROR] [DiscordSRV] DiscordSRV failed to load properly: org/bukkit/event/player/PlayerAchievementAwardedEvent. See https://bin.scarsz.me/141872ad-2a56-40d2-a65c-6f6f7b03a68e#Ozs1JjcD559SSaqLhrUmJVEEjszQVtfw for more information.
```

**Comment by Scarsz** [comment]
https://github.com/DiscordSRV/DiscordSRV/commit/c7ee494d132914c0f2d16c0bf61ca9e30b465ece https://lol.scarsz.me/YxpjiJ/DiscordSRV-Build-1.18.3-SNAPSHOT.jar

**Comment by MJRLegends** [comment]
Thanks <3

**Comment by MJRLegends** [comment]
All works now thanks
