### ISSUE TITLE
Plugin DiscordSRV v1.18.4 generated an exception while executing task 100

### ISSUE THREAD

**Issue by SimmsRyan97** [DiscordSRV/DiscordSRV#598]
```
19.12 23:40:13 [Server] WARN [DiscordSRV] Plugin DiscordSRV v1.18.4 generated an exception while executing task 100
19.12 23:40:13 [Server] INFO github.scarsz.discordsrv.dependencies.jda.api.exceptions.InsufficientPermissionException: Cannot perform action due to a lack of Permission. Missing permission: MANAGE_ROLES
19.12 23:40:13 [Server] INFO at github.scarsz.discordsrv.dependencies.jda.internal.entities.GuildImpl.checkPermission(GuildImpl.java:1215) ~[?:?]
19.12 23:40:13 [Server] INFO at github.scarsz.discordsrv.dependencies.jda.internal.entities.GuildImpl.modifyMemberRoles(GuildImpl.java:1008) ~[?:?]
19.12 23:40:13 [Server] INFO at github.scarsz.discordsrv.util.DiscordUtil.modifyRolesOfMember(DiscordUtil.java:564) ~[?:?]
19.12 23:40:13 [Server] INFO at github.scarsz.discordsrv.util.GroupSynchronizationUtil.reSyncGroups(GroupSynchronizationUtil.java:110) ~[?:?]
19.12 23:40:13 [Server] INFO at github.scarsz.discordsrv.util.GroupSynchronizationUtil.reSyncGroups(GroupSynchronizationUtil.java:42) ~[?:?]
19.12 23:40:13 [Server] INFO at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_222]
19.12 23:40:13 [Server] INFO at github.scarsz.discordsrv.util.GroupSynchronizationUtil.lambda$static$0(GroupSynchronizationUtil.java:38) ~[?:?]
19.12 23:40:13 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-175]
19.12 23:40:13 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-175]
19.12 23:40:13 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-175]
19.12 23:40:13 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
19.12 23:40:13 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
19.12 23:40:13 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```

**Comment by Scarsz** [comment]
Once again, read the error

**Comment by ErythroCraft** [comment]
More than 2000 lines of

[So., 28. März 2021 14:22:57 MESZ WARN] [DiscordSRV] Plugin DiscordSRV v1.21.3 generated an exception while executing task 219

What is wrong on my server?

**Comment by GreemDev** [comment]
Join the discord. https://scarsz.me/discord
As stated above. It helps to read sometimes.
