### ISSUE TITLE
Voice module error

### ISSUE THREAD

**Issue by LeeGodSRC** [DiscordSRV/DiscordSRV#600]
```
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:370) ~[server.jar:git-iSpigot-PaperEdition]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[server.jar:git-iSpigot-PaperEdition]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:88) ~[server.jar:git-iSpigot-PaperEdition]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:539) ~[server.jar:git-iSpigot-PaperEdition]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:524) ~[server.jar:git-iSpigot-PaperEdition]
at net.minecraft.server.v1_8_R3.PlayerList.disconnect(SourceFile:354) ~[server.jar:git-iSpigot-PaperEdition]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(SourceFile:843) ~[server.jar:git-iSpigot-PaperEdition]
at net.minecraft.server.v1_8_R3.NetworkManager.l(SourceFile:337) ~[server.jar:git-iSpigot-PaperEdition]
at net.minecraft.server.v1_8_R3.ServerConnection.c(SourceFile:140) ~[server.jar:git-iSpigot-PaperEdition]
at net.minecraft.server.v1_8_R3.MinecraftServer.tickServer(SourceFile:735) ~[server.jar:git-iSpigot-PaperEdition]
at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$run$0(SourceFile:617) ~[server.jar:git-iSpigot-PaperEdition]
at spg.lgdev.thread.iSpigotThread.lambda$schedule$0(SourceFile:44) ~[server.jar:git-iSpigot-PaperEdition]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_212]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_212]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.util.ConcurrentModificationException
at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1561) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_212]
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_212]
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_212]
at github.scarsz.discordsrv.modules.voice.VoiceModule.onPlayerQuit(VoiceModule.java:287) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:368) ~[server.jar:git-iSpigot-PaperEdition]
... 18 more
```

**Comment by Vankka** [comment]
This might've been fixed in dev builds, https://discordsrv.com/discordsrv-snapshot
