### ISSUE TITLE
Server offline since upgrading the server.

### ISSUE THREAD

**Issue by RaidersPlay** [DiscordSRV/DiscordSRV#620]
I've upgraded the server to 1.15.2
I've noticed that the server is now showing as offline although the bot shows as online.
I'm also noticing a bunch of warnings and errors in the logs.

```
[09:36:13] [DiscordSRV - Initialization/WARN]: github.scarsz.discordsrv.dependencies.google.gson.JsonSyntaxException: Expected a github.scarsz.discordsrv.dependencies.google.gson.JsonObject but was github.scarsz.discordsrv.dependencies.google.gson.JsonPrimitive
[09:36:13] [DiscordSRV - Initialization/WARN]: 	at github.scarsz.discordsrv.dependencies.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:897)
[09:36:13] [DiscordSRV - Initialization/WARN]: 	at github.scarsz.discordsrv.dependencies.google.gson.Gson.fromJson(Gson.java:927)
[09:36:13] [DiscordSRV - Initialization/WARN]: 	at github.scarsz.discordsrv.dependencies.google.gson.Gson.fromJson(Gson.java:892)
[09:36:13] [DiscordSRV - Initialization/WARN]: 	at github.scarsz.discordsrv.dependencies.google.gson.Gson.fromJson(Gson.java:841)
[09:36:13] [DiscordSRV - Initialization/WARN]: 	at github.scarsz.discordsrv.dependencies.google.gson.Gson.fromJson(Gson.java:813)
[09:36:13] [DiscordSRV - Initialization/WARN]: 	at github.scarsz.discordsrv.objects.managers.AccountLinkManager.<init>(AccountLinkManager.java:56)
[09:36:13] [DiscordSRV - Initialization/WARN]: 	at github.scarsz.discordsrv.DiscordSRV.init(DiscordSRV.java:584)
[09:36:13] [DiscordSRV - Initialization/WARN]: 	at java.lang.Thread.run(Unknown Source)
[09:36:15] [DiscordSRV - Initialization/ERROR]: [DiscordSRV] DiscordSRV failed to load properly: Expected a github.scarsz.discordsrv.dependencies.google.gson.JsonObject but was github.scarsz.discordsrv.dependencies.google.gson.JsonPrimitive. See https://bin.scarsz.me/8d8654f5-ddc6-4623-87ec-ac31b0c37fce#lb9lnZKv1C7GdCDqYXCemIgP86pUzOql for more information.
```

**Comment by Vankka** [comment]
liked accounts file is broken, delete it
