### ISSUE TITLE
Exception while executing task 62

### ISSUE THREAD

**Issue by ZebroUnion** [DiscordSRV/DiscordSRV#656]
java.lang.IllegalArgumentException: Invalid key: Network.Strength
        at github.scarsz.configuralize.DynamicConfig.lambda$null$3(DynamicConfig.java:109) ~[?:?]
        at java.util.Optional.orElseThrow(Unknown Source) ~[?:1.8.0_241]
        at github.scarsz.configuralize.DynamicConfig.lambda$dget$4(DynamicConfig.java:109) ~[?:?]
        at java.util.Optional.orElseGet(Unknown Source) ~[?:1.8.0_241]
        at github.scarsz.configuralize.DynamicConfig.dget(DynamicConfig.java:106) ~[?:?]
        at github.scarsz.configuralize.DynamicConfig.getDouble(DynamicConfig.java:327) ~[?:?]
        at github.scarsz.discordsrv.modules.voice.VoiceModule.getStrength(VoiceModule.java:352) ~[?:?]
        at github.scarsz.discordsrv.modules.voice.VoiceModule.lambda$tick$17(VoiceModule.java:152) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_241]
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_241]
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_241]
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_241]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_241]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_241]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_241]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_241]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_241]
        at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_241]
        at github.scarsz.discordsrv.modules.voice.VoiceModule.tick(VoiceModule.java:160) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[sserver.jar:git-Spigot-800b93f-8160e29]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [sserver.jar:git-Spigot-800b93f-8160e29]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_241]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]

**Comment by Vankka** [comment]
Your voice.yml is missing the Network.Strength option, you can find a copy of the file here: https://github.com/DiscordSRV/DiscordSRV/blob/master/src/main/resources/voice/en.yml
