### ISSUE TITLE
IllegalArgumentException: Cannot use CacheFlag.ACTIVITY without GatewayIntent.GUILD_PRESENCES!

### ISSUE THREAD

**Issue by mibby** [DiscordSRV/DiscordSRV#671]
DiscordSRV-Build-1.19.0-SNAPSHOT-1585655817

```
[05:06:49] [DiscordSRV - Initialization/INFO]: [DiscordSRV] This build of DiscordSRV is identical to develop. [latest public dev build]
[05:06:49] [DiscordSRV - Initialization/ERROR]: [DiscordSRV] An unknown error occurred building JDA...
[05:06:49] [DiscordSRV - Initialization/WARN]: java.lang.IllegalArgumentException: Cannot use CacheFlag.ACTIVITY without GatewayIntent.GUILD_PRESENCES!
[05:06:49] [DiscordSRV - Initialization/WARN]: 	at github.scarsz.discordsrv.dependencies.jda.api.JDABuilder.checkIntents(JDABuilder.java:1767)
[05:06:49] [DiscordSRV - Initialization/WARN]: 	at github.scarsz.discordsrv.dependencies.jda.api.JDABuilder.build(JDABuilder.java:1694)
[05:06:49] [DiscordSRV - Initialization/WARN]: 	at github.scarsz.discordsrv.DiscordSRV.init(DiscordSRV.java:514)
[05:06:49] [DiscordSRV - Initialization/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by Vankka** [comment]
update your dev build

**Comment by mibby** [comment]
@Vankka To what? I downloaded the SNAPSHOT from https://snapshot.discordsrv.com/ an hour before posting this ticket.

**Comment by Vankka** [comment]
fixed, jda's cache flags are just annoying as shit, apparently
