### ISSUE TITLE
Can't drag to voice chat correctly

### ISSUE THREAD

**Issue by minexo79** [DiscordSRV/DiscordSRV#687]
I'm use the dev build `SNAPSHOT-1586513902`, the [previous bug](https://github.com/DiscordSRV/DiscordSRV/issues/676) has disapper. But If both players in area are being too near or run randomly, it will have a random probability that the plugin is unable to drag player into corresponding voice chat correctly until someone leave the area.

hardware spec:
```md
GCP: c2-standard-4 (4-core/16G ram)
SSD: 120G
OS: Ubuntu 18.04 LTS
```
config:
```yml
Tick speed: 3
Strength: 10
```

error log:
```md
[06:35:31 ERROR]: [DiscordSRV] [JDA] There was an exception while executing a REST request
java.lang.IllegalStateException: Already Executed
        at github.scarsz.discordsrv.dependencies.okhttp3.RealCall.execute(RealCall.java:85)
        at github.scarsz.discordsrv.dependencies.jda.internal.requests.Requester.execute(Requester.java:205)
        at github.scarsz.discordsrv.dependencies.jda.internal.requests.Requester.execute(Requester.java:145)
        at github.scarsz.discordsrv.dependencies.jda.internal.requests.Requester.execute(Requester.java:128)
        at github.scarsz.discordsrv.dependencies.jda.internal.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:435)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by Vankka** [comment]
Need extra details, set `DebugJDARestActions` to `true`. Communicating through Discord would likely be easier as well https://discordsrv.com/discord

**Comment by Vankka** [comment]
Inactive, no response in over a month
