### ISSUE TITLE
Discord Rank Sync

### ISSUE THREAD

**Issue by feja111** [DiscordSRV/DiscordSRV#705]
[19:35:57] [Craft Scheduler Thread - 13/WARN]: [DiscordSRV] Plugin DiscordSRV v1.18.4 generated an exception while executing task 23
java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class java.lang.String (java.util.LinkedHashMap and java.lang.String are in module java.base of loader 'bootstrap')
        at github.scarsz.discordsrv.util.GroupSynchronizationUtil.reSyncGroups(GroupSynchronizationUtil.java:73) ~[?:?]
        at github.scarsz.discordsrv.util.GroupSynchronizationUtil.reSyncGroups(GroupSynchronizationUtil.java:42) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1540) ~[?:?]
        at github.scarsz.discordsrv.util.GroupSynchronizationUtil.lambda$static$0(GroupSynchronizationUtil.java:38) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.15.2.jar:git-Spigot-8faa8b4-fba9f48]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.15.2.jar:git-Spigot-8faa8b4-fba9f48]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[19:36:58] [Craft Scheduler Thread - 14/WARN]: [DiscordSRV] Plugin DiscordSRV v1.18.4 generated an exception while executing task 23
java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class java.lang.String (java.util.LinkedHashMap and java.lang.String are in module java.base of loader 'bootstrap')
        at github.scarsz.discordsrv.util.GroupSynchronizationUtil.reSyncGroups(GroupSynchronizationUtil.java:73) ~[?:?]
        at github.scarsz.discordsrv.util.GroupSynchronizationUtil.reSyncGroups(GroupSynchronizationUtil.java:42) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1540) ~[?:?]
        at github.scarsz.discordsrv.util.GroupSynchronizationUtil.lambda$static$0(GroupSynchronizationUtil.java:38) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.15.2.jar:git-Spigot-8faa8b4-fba9f48]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.15.2.jar:git-Spigot-8faa8b4-fba9f48]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
>

**Comment by Vankka** [comment]
You messed up the config for group sync
