### ISSUE TITLE
Issue with last update

### ISSUE THREAD

**Issue by Aubhisamme** [DiscordSRV/DiscordSRV#720]
Hello, great plugin, but since your last update in 1.18.4, I have many bugs. I tried to install it from scratch but everytime I still get this error in the console after it joined my channels:

```
[16:22:08]: [WARN] java.lang.IllegalArgumentException: ID may not be empty
[16:22:08]: [WARN] at github.scarsz.discordsrv.dependencies.jda.internal.utils.Checks.notEmpty(Checks.java:63)
[16:22:08]: [WARN] at github.scarsz.discordsrv.dependencies.jda.api.utils.MiscUtil.parseSnowflake(MiscUtil.java:105)
[16:22:08]: [WARN] at github.scarsz.discordsrv.dependencies.jda.api.utils.cache.SnowflakeCacheView.getElementById(SnowflakeCacheView.java:59)
[16:22:08]: [WARN] at github.scarsz.discordsrv.dependencies.jda.api.JDA.getTextChannelById(JDA.java:1177)
[16:22:08]: [WARN] at github.scarsz.discordsrv.DiscordSRV.getMainTextChannel(DiscordSRV.java:156)
[16:22:08]: [WARN] at github.scarsz.discordsrv.DiscordSRV.init(DiscordSRV.java:543)
[16:22:08]: [WARN] at java.base/java.lang.Thread.run(Thread.java:834)
[16:22:08]: [WARN] java.lang.IllegalArgumentException: ID may not be empty
[16:22:08]: [WARN] at github.scarsz.discordsrv.dependencies.jda.internal.utils.Checks.notEmpty(Checks.java:63)
[16:22:08]: [WARN] at github.scarsz.discordsrv.dependencies.jda.api.utils.MiscUtil.parseSnowflake(MiscUtil.java:105)
[16:22:08]: [WARN] at github.scarsz.discordsrv.dependencies.jda.api.utils.cache.SnowflakeCacheView.getElementById(SnowflakeCacheView.java:59)
[16:22:08]: [WARN] at github.scarsz.discordsrv.dependencies.jda.api.JDA.getTextChannelById(JDA.java:1177)
[16:22:08]: [WARN] at github.scarsz.discordsrv.DiscordSRV.getMainTextChannel(DiscordSRV.java:156)
[16:22:08]: [WARN] at github.scarsz.discordsrv.util.DebugUtil.run(DebugUtil.java:74)
[16:22:08]: [WARN] at github.scarsz.discordsrv.util.DebugUtil.run(DebugUtil.java:56)
[16:22:08]: [WARN] at github.scarsz.discordsrv.DiscordSRV.lambda$onEnable$5(DiscordSRV.java:274)
[16:22:08]: [WARN] at java.base/java.lang.Thread.dispatchUncaughtException(Thread.java:2001)
[16:22:08]: [ERROR] [DiscordSRV] DiscordSRV failed to load properly: ID may not be empty. See Failed to collect debug information: ID may not be empty. Check the console for further details. for more information.
```

**Comment by Vankka** [comment]
Your first channel in `Channels` is blank, eg. `Channels: {"global": ""}`

**Comment by Aubhisamme** [comment]
Okay sorry I was a moron, but now I get

```
[21:02:47]: [WARN] [DiscordSRV] [JDA] Encountered 429 on route /channels/715255224058642444
[21:02:47]: [WARN] [DiscordSRV] [JDA] Encountered 429 on route /channels/715244417648427148
[21:03:02]: [WARN] [DiscordSRV] [JDA] Encountered 429 on route /channels/715255224058642444
[21:03:02]: [WARN] [DiscordSRV] [JDA] Encountered 429 on route /channels/715244417648427148
[21:03:02]: [WARN] [DiscordSRV] [JDA] Encountered 429 on route /channels/715255224058642444
[21:03:02]: [WARN] [DiscordSRV] [JDA] Encountered 429 on route /channels/715244417648427148
```

My permissions are correct on my discord, the bot has everything it needs, the config doesn't miss anything, and I don't really know what gives...

**Comment by Vankka** [comment]
Grab latest dev build from https://snapshot.discordsrv.com
