### ISSUE TITLE
1.19.0 not loading, disabled due to error (miscast)

### ISSUE THREAD

**Issue by mbravorus** [DiscordSRV/DiscordSRV#741]
Unless there is some special update in configuration that needs to be done while updating to 1.19.0, it breaks on upgrade (replaced jar with 1.19.0, restarted server, got this:

```
[18:18:31 INFO]: [DiscordSRV] Enabling DiscordSRV v1.19.0
[18:18:31 WARN]: [DiscordSRV] Config key DiscordCannedResponses.!ip is missing from the config.yml. Using the default value of yourserveripchange.me
[18:18:31 ERROR]: Error occurred while enabling DiscordSRV v1.19.0 (Is it up to date?)
java.lang.ClassCastException: 'MaximumAttemptsForSystemDNSBeforeUsingFallbackDNS' miscast in path root->*MaximumAttemptsForSystemDNSBeforeUsingFallbackDNS*: Cannot cast java.lang.Integer to java.lang.String. Avoid by checking `if (aDynamic.is(String.class)) ...` or using `aDynamic.maybe().as(String.class)`
        at alexh.weak.DynamicChild.as(DynamicChild.java:52) ~[?:?]
        at alexh.weak.Weak.asString(Weak.java:67) ~[?:?]
        at github.scarsz.discordsrv.util.ConfigUtil.logMissingOptions(ConfigUtil.java:187) ~[?:?]
        at github.scarsz.discordsrv.DiscordSRV.onEnable(DiscordSRV.java:325) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[paper.jar:git-Paper-309]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[paper.jar:git-Paper-309]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[paper.jar:git-Paper-309]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[paper.jar:git-Paper-309]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[paper.jar:git-Paper-309]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[paper.jar:git-Paper-309]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[paper.jar:git-Paper-309]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:900) ~[paper.jar:git-Paper-309]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[18:18:31 INFO]: [DiscordSRV] Disabling DiscordSRV v1.19.0
```

**Comment by Scarsz** [comment]
update https://snapshot.discordsrv.com
