### ISSUE TITLE
Using quotations in a message results in an error in console, and message not being sent to server

### ISSUE THREAD

**Issue by MCHalfAssed** [DiscordSRV/DiscordSRV#754]
Adding quotation marks to a message when sending from the Discord to the server results in error, and the message does not send to the server.

If I send a message like this;

_they all use the excuse that "im bad at 1.9 pvp" lol_
_"can anyone see this?"_

You get the error below -

`[Tue, 9. Jun 2020 15:35:01 GMT ERROR] [JDA] One of the EventListeners had an uncaught exception
java.lang.RuntimeException: An internal error occured.
    at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:20)
    at com.comphenix.protocol.wrappers.WrappedChatComponent.deserialize(WrappedChatComponent.java:62)
    at com.comphenix.protocol.wrappers.WrappedChatComponent.fromJson(WrappedChatComponent.java:93)
    at mineverse.Aust1n46.chat.utilities.Format.createPacketPlayOutChat(Format.java:307)
    at github.scarsz.discordsrv.hooks.chat.VentureChatHook.broadcastMessageToChannel(VentureChatHook.java:212)
    at github.scarsz.discordsrv.DiscordSRV.broadcastMessageToMinecraftServer(DiscordSRV.java:1263)
    at github.scarsz.discordsrv.listeners.DiscordChatListener.onGuildMessageReceived(DiscordChatListener.java:238)
    at github.scarsz.discordsrv.dependencies.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:396)
    at github.scarsz.discordsrv.dependencies.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
    at github.scarsz.discordsrv.dependencies.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:82)
    at github.scarsz.discordsrv.dependencies.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:69)
    at github.scarsz.discordsrv.dependencies.jda.internal.JDAImpl.handleEvent(JDAImpl.java:166)
    at github.scarsz.discordsrv.dependencies.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:97)
    at github.scarsz.discordsrv.dependencies.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
    at github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:921)
    at github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:808)
    at github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:786)
    at githu
b.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:959)
    at github.scarsz.discordsrv.dependencies.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
    at github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
    at github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
    at github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
    at github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.main(ReadingThread.java:108)
    at github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.runMain(ReadingThread.java:64)
    at github.scarsz.discordsrv.dependencies.ws.client.WebSocketThread.run(WebSocketThread.java:45)
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 251 path $[6].text
    at com.google.gson.internal.Streams.parse(Streams.java:60)
    at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:65)
    at net.minecraft.server.v1_15_R1.ChatDeserializer.a(SourceFile:494)
    at net.minecraft.server.v1_15_R1.ChatDeserializer.a(SourceFile:519)
    at sun.reflect.GeneratedMethodAccessor53.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16)
    ... 24 more
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 251 path $[6].text
    at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
    at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:491)
    at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
    at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:738)
    at com.
google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:731)
    at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714)
    at com.google.gson.internal.Streams.parse(Streams.java:48)
    ... 31 more`

**Comment by Vankka** [comment]
Seems like a VentureChat side issue, pinged the author to have a look at this issue

**Comment by Vankka** [comment]
Please test with the latest development build, https://snapshot.discordsrv.com

**Comment by MCHalfAssed** [comment]
Tested, looks like the bug is squashed. Nice work team
