### ISSUE TITLE
Was unable to schedule next packet due to rejected execution by threadpool

### ISSUE THREAD

**Issue by bonjourkemal** [DiscordSRV/DiscordSRV#771]
When my server closing,
```
[22:10:33 ERROR]: [DiscordSRV] [JDA] Was unable to schedule next packet due to rejected execution by threadpool
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@475e1754 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@25c81db[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 1555]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
        at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
        at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
        at java.util.concurrent.Executors$DelegatedScheduledExecutorService.schedule(Executors.java:729)
        at github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketSendingThread.scheduleIdle(WebSocketSendingThread.java:82)
        at github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketSendingThread.scheduleNext(WebSocketSendingThread.java:166)
        at github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketSendingThread.run(WebSocketSendingThread.java:156)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
How do I fix?

DiscordSRV version: 
```
[22:14:22 INFO]: DiscordSRV version 1.19.0
[22:14:22 INFO]: The most powerful, configurable, open-source Discord bridge plugin out there.
[22:14:22 INFO]: Website: https://github.com/DiscordSRV/DiscordSRV
[22:14:22 INFO]: Authors: Scarsz, Androkai and Vankka
```
Server version:
```
[22:14:47 INFO]: This server is running Paper version git-Paper-372 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[22:14:47 INFO]: Checking version, please wait...
[22:14:47 INFO]: Previous version: git-Paper-367 (MC: 1.15.2)
[22:14:47 INFO]: You are running the latest version
```

**Comment by Scarsz** [comment]
Has been fixed in snapshots https://snapshot.discordsrv.com

**Comment by bonjourkemal** [comment]
`[22:21:41 ERROR]: Nag author: 'Scarsz' of 'DiscordSRV' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.`

Is there a solution for this?

**Comment by Vankka** [comment]
No there isn't as of now
