### ISSUE TITLE
Plugin trying to kick player asynchronously.

### ISSUE THREAD

**Issue by TheChilliPL** [DiscordSRV/DiscordSRV#786]
When player unlinks their account and plugin tries to kick them (as I've set in the config), it's trying to do it asynchronously (leading to an IllegalStateException)

<details><summary>Error in the console</summary>

```
[13:07:21 WARN]: [DiscordSRV] Plugin DiscordSRV v1.19.0 generated an exception while executing task 122
java.lang.IllegalStateException: Asynchronous player kick!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.14.4.jar:git-Paper-237]
        at org.bukkit.craftbukkit.v1_14_R1.entity.CraftPlayer.kickPlayer(CraftPlayer.java:430) ~[patched_1.14.4.jar:git-Paper-237]
        at github.scarsz.discordsrv.modules.requirelink.RequireLinkModule.noticePlayerUnlink(RequireLinkModule.java:154) ~[?:?]
        at github.scarsz.discordsrv.objects.managers.AccountLinkManager.unlink(AccountLinkManager.java:249) ~[?:?]
        at github.scarsz.discordsrv.commands.CommandUnlink.executeAsync(CommandUnlink.java:119) ~[?:?]
        at github.scarsz.discordsrv.commands.CommandUnlink.lambda$execute$0(CommandUnlink.java:47) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-237]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-237]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-237]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242-ea]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242-ea]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242-ea]
```
</details>

**Plugin version:** _1.19.0_
**Server version:** _git-Paper-237_ for _Minecraft 1.14.4_ implementing API _1.14.4-R0.1-SNAPSHOT_

**Comment by Vankka** [comment]
Has already been fixed, https://snapshot.discordsrv.com

**Comment by TheChilliPL** [comment]
Wow, thanks for the quick help!
