### ISSUE TITLE
v1.19.1 on Spigot 1.16.2 : unable to schedule next packet due to rejected execution by threadpool

### ISSUE THREAD

**Issue by SmoothieNoIce** [DiscordSRV/DiscordSRV#837]
Recently I updated my server to Spigot version 1.16.2, but this error occurred when i was starting up the server, and my server shut down immediately.

```[16:15:34] [DiscordSRV - JDA Gateway/ERROR]: [DiscordSRV] [JDA] Was unable to schedule next packet due to rejected execution by threadpool
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@35710b96[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@74f82db8[Wrapped task = github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketSendingThread@7f6635c7]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@79f66baa[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 12]
        at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
        at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:340)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562)
        at java.base/java.util.concurrent.Executors$DelegatedScheduledExecutorService.schedule(Executors.java:779)
        at github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketSendingThread.scheduleIdle(WebSocketSendingThread.java:82)
        at github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketSendingThread.scheduleNext(WebSocketSendingThread.java:166)
        at github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketSendingThread.run(WebSocketSendingThread.java:156)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

[16:15:34] [DiscordSRV - Shutdown/INFO]: [DiscordSRV] Shutdown completed in 499ms```

**Comment by Vankka** [comment]
Full log please.

**Comment by SmoothieNoIce** [comment]
I found the problem, because one of my plugins was disabled discord srv, sorry :P
