### ISSUE TITLE
Error while shutting down the server

### ISSUE THREAD

**Issue by MaximMaximS** [DiscordSRV/DiscordSRV#868]
Hello, my problem is that every time I turn off the server this error appears:

```
[08:50:35] [DiscordSRV - JDA Rate Limit/ERROR]: [DiscordSRV] [JDA] There was an exception while executing a REST request
java.lang.IllegalStateException: java.lang.InterruptedException
        at github.scarsz.discordsrv.dependencies.jda.api.utils.MiscUtil.locked(MiscUtil.java:129)
        at github.scarsz.discordsrv.dependencies.jda.internal.requests.ratelimit.BotRateLimiter.handleResponse(BotRateLimiter.java:215)
        at github.scarsz.discordsrv.dependencies.jda.internal.requests.Requester.execute(Requester.java:230)
        at github.scarsz.discordsrv.dependencies.jda.internal.requests.Requester.execute(Requester.java:139)
        at github.scarsz.discordsrv.dependencies.jda.internal.requests.Requester.execute(Requester.java:122)
        at github.scarsz.discordsrv.dependencies.jda.internal.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:461)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1220)
        at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:335)
        at github.scarsz.discordsrv.dependencies.jda.api.utils.MiscUtil.locked(MiscUtil.java:124)
        ... 12 more

```
I am using Spigot 1.16.3

**Comment by Vankka** [comment]
Safe to ignore
