### ISSUE TITLE
Discord SRV not working

### ISSUE THREAD

**Issue by cb12438** [DiscordSRV/DiscordSRV#941]
so when i start up my server and i do /plugins it appers in red and when i do something in the config trying to set it up it says "Discord SRV is disabled check your logs for errors during server start up to find ouy why"
so i did and it says this
"[04:20:57] [Server thread/INFO]: [DiscordSRV] Loading DiscordSRV v1.21.0
[04:20:57] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it"
i just installed the plugin and did the config and it did that is thier a way to fix this??

**Comment by Scarsz** [comment]
As the message says, you need to check your log *more thoroughly* for the error as to why the plugin disabled itself

**Comment by AternosBotForMadnessSMP** [comment]
I have the same issue here is the log 

[12:52:47 WARN]: Unexpected exception while parsing console command "discord"
org.bukkit.command.CommandException: Unhandled exception executing command 'discord' in plugin DiscordSRV v1.22.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Paper-731]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-731]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:827) ~[patched_1.16.5.jar:git-Paper-731]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:789) ~[patched_1.16.5.jar:git-Paper-731]
        at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:470) ~[patched_1.16.5.jar:git-Paper-731]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:437) ~[patched_1.16.5.jar:git-Paper-731]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1341) ~[patched_1.16.5.jar:git-Paper-731]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1129) ~[patched_1.16.5.jar:git-Paper-731]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-731]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686) ~[?:1.8.0_292]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:315) ~[?:1.8.0_292]
        at java.util.jar.JarFile.getEntry(JarFile.java:240) ~[?:1.8.0_292]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:223) ~[?:1.8.0_292]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:165) ~[patched_1.16.5.jar:git-Paper-731]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_292]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119) ~[patched_1.16.5.jar:git-Paper-731]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-731]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_292]
        at github.scarsz.discordsrv.DiscordSRV.onCommand(DiscordSRV.java:1452) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-731]
        ... 9 more

**Comment by AternosBotForMadnessSMP** [comment]
I have the same issue
Here is the log 

[12:52:47 WARN]: Unexpected exception while parsing console command "discord"
org.bukkit.command.CommandException: Unhandled exception executing command 'discord' in plugin DiscordSRV v1.22.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Paper-731]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-731]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:827) ~[patched_1.16.5.jar:git-Paper-731]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:789) ~[patched_1.16.5.jar:git-Paper-731]
        at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:470) ~[patched_1.16.5.jar:git-Paper-731]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:437) ~[patched_1.16.5.jar:git-Paper-731]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1341) ~[patched_1.16.5.jar:git-Paper-731]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1129) ~[patched_1.16.5.jar:git-Paper-731]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-731]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686) ~[?:1.8.0_292]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:315) ~[?:1.8.0_292]
        at java.util.jar.JarFile.getEntry(JarFile.java:240) ~[?:1.8.0_292]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:223) ~[?:1.8.0_292]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:165) ~[patched_1.16.5.jar:git-Paper-731]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_292]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119) ~[patched_1.16.5.jar:git-Paper-731]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-731]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_292]
        at github.scarsz.discordsrv.DiscordSRV.onCommand(DiscordSRV.java:1452) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-731]
        ... 9 more

**Comment by Scarsz** [comment]
> I have the same issue here is the log
> 
> [12:52:47 WARN]: Unexpected exception while parsing console command "discord"
> org.bukkit.command.CommandException: Unhandled exception executing command 'discord' in plugin DiscordSRV v1.22.0
> at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Paper-731]
> at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-731]
> at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:827) ~[patched_1.16.5.jar:git-Paper-731]
> at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:789) ~[patched_1.16.5.jar:git-Paper-731]
> at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:470) ~[patched_1.16.5.jar:git-Paper-731]
> at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:437) ~[patched_1.16.5.jar:git-Paper-731]
> at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1341) ~[patched_1.16.5.jar:git-Paper-731]
> at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1129) ~[patched_1.16.5.jar:git-Paper-731]
> at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-731]
> at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
> Caused by: java.lang.IllegalStateException: zip file closed
> at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686) ~[?:1.8.0_292]
> at java.util.zip.ZipFile.getEntry(ZipFile.java:315) ~[?:1.8.0_292]
> at java.util.jar.JarFile.getEntry(JarFile.java:240) ~[?:1.8.0_292]
> at java.util.jar.JarFile.getJarEntry(JarFile.java:223) ~[?:1.8.0_292]
> at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:165) ~[patched_1.16.5.jar:git-Paper-731]
> at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_292]
> at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119) ~[patched_1.16.5.jar:git-Paper-731]
> at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-731]
> at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_292]
> at github.scarsz.discordsrv.DiscordSRV.onCommand(DiscordSRV.java:1452) ~[?:?]
> at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-731]
> ... 9 more

That isn't even the same issue, this issue has been closed for months, and we don't do support on GitHub, as the bot already said.

**Comment by Mrslime240** [comment]
My discordm essage doesnt show up in ingame, but if i will chat on ingame my chat will show up on discord, the only problems is why my discord message doesnt show up in ingame ):
