### ISSUE TITLE
login error after after uploading discordsrv to the latest version

### ISSUE THREAD

**Issue by Fargus5** [DiscordSRV/DiscordSRV#968]
Hello

I'm receiving this error after uploading discordsrv to the latest version

```
[13:36:44]: [WARN] at org.inventivetalent.packetlistener.channel.INCChannel$1.run(INCChannel.java:33)
[13:36:44]: [WARN] at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[13:36:44]: [WARN] at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[13:36:44]: [WARN] at java.base/java.lang.Thread.run(Thread.java:834)
[13:36:44]: [WARN] at io.netty.channel.DefaultChannelPipeline.checkDuplicateName(DefaultChannelPipeline.java:1101)
[13:36:44]: [WARN] at io.netty.channel.DefaultChannelPipeline.filterName(DefaultChannelPipeline.java:302)
[13:36:44]: [WARN] at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:259)
[13:36:44]: [WARN] at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:249)
[13:36:44]: [WARN] at com.comphenix.protocol.injector.netty.PipelineProxy.addBefore(PipelineProxy.java:61)
[13:36:44]: [WARN] at com.comphenix.protocol.injector.netty.ChannelInjector$3$1.addBefore(ChannelInjector.java:287)
[13:36:44]: [WARN] at org.inventivetalent.packetlistener.channel.INCChannel$1.run(INCChannel.java:31)
[13:36:44]: [WARN] ... 3 more
[13:36:44]: [WARN] Now saving stats of player _Call_Me_Akira_
```

when a player login...

do u know what this could be?

**Comment by Vankka** [comment]
Need the full error

**Comment by Fargus5** [comment]
https://log.mtxserv.com/6EXthYv#L3335

**Comment by Vankka** [comment]
Not a DiscordSRV error
