### ISSUE TITLE
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

### ISSUE THREAD

**Issue by antv199** [DiscordSRV/DiscordSRV#975]
```
[ERROR] .... Could not pass event PlayerQuitEvent to DiscordSRV v1.21.2
github.scarsz.discordsrv.dependencies.kevinsawicki.http.HttpRequest$HttpRequestException: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
    at github.scarsz.discordsrv.dependencies.kevinsawicki.http.HttpRequest.code(HttpRequest.java:1562) ~[?:?]
    at github.scarsz.discordsrv.dependencies.mojang.Mojang.fetch(Mojang.java:81) ~[?:?]
    at github.scarsz.discordsrv.DiscordSRV.getAvatarUrl(DiscordSRV.java:1892) ~[?:?]
    at github.scarsz.discordsrv.DiscordSRV.getAvatarUrl(DiscordSRV.java:1883) ~[?:?]
    at github.scarsz.discordsrv.DiscordSRV.sendLeaveMessage(DiscordSRV.java:1697) ~[?:?]
    at github.scarsz.discordsrv.listeners.PlayerJoinLeaveListener.PlayerQuitEvent(PlayerJoinLeaveListener.java:132) ~[?:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor85.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-406]
    at org.bukkit.plugin.EventExecutor$$Lambda$3676.0000000014944BD0.execute(Unknown Source) ~[?:?]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-406]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-406]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-406]
    at net.minecraft.server.v1_16_R3.PlayerList.disconnect(PlayerList.java:513) ~[patched_1.16.4.jar:git-Paper-406]
    at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1690) ~[patched_1.16.4.jar:git-Paper-406]
    at net.minecraft.server.v1_16_R3.NetworkManager.handleDisconnection(NetworkManager.java:502) ~[patched_1.16.4.jar:git-Paper-406]
    at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:165) ~[patched_1.16.4.jar:git-Paper-406]
    at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1376) ~[patched_1.16.4.jar:git-Paper-406]
    at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-406]
    at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1204) ~[patched_1.16.4.jar:git-Paper-406]
    at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:992) ~[patched_1.16.4.jar:git-Paper-406]
    at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-406]
    at net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3147.0000000028186700.run(Unknown Source) ~[?:?]
    at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
    at sun.security.ssl.Alert.createSSLException(Unknown Source) ~[?:?]
    at sun.security.ssl.Alert.createSSLException(Unknown Source) ~[?:?]
    at sun.security.ssl.TransportContext.fatal(Unknown Source) ~[?:?]
    at sun.security.ssl.Alert$AlertConsumer.consume(Unknown Source) ~[?:?]
    at sun.security.ssl.TransportContext.dispatch(Unknown Source) ~[?:?]
    at sun.security.ssl.SSLTransport.decode(Unknown Source) ~[?:?]
    at sun.security.ssl.SSLSocketImpl.decode(Unknown Source) ~[?:?]
    at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source) ~[?:?]
    at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:?]
    at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source) ~[?:?]
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[?:?]
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:?]
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:?]
    at java.net.HttpURLConnection.getResponseCode(Unknown Source) ~[?:?]
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source) ~[?:?]
    at github.scarsz.discordsrv.dependencies.kevinsawicki.http.HttpRequest.code(HttpRequest.java:1560) ~[?:?]
... 22 more
```

**Comment by Vankka** [comment]
What java version and vendor?

**Comment by antv199** [comment]
Java 11 OpenJ9. More specifically :

```
System Info: Java 11 (Eclipse OpenJ9 VM openj9-0.10.0) Host: Linux 4.15.0-109-generic (amd64)
```

It used to work just fine in previous updates

The server runs on server.pro's hardware, just in case you need any additional hardware info

**Comment by Scarsz** [comment]
Unable to reproduce on 11 JRE/OpenJ9

`docker run -p 25565:25565 -it --rm --name test adoptopenjdk/openjdk11-openj9:jre /bin/bash -c "apt update; apt install httpie nano -y; cd ~; http -d https://papermc.io/api/v2/projects/paper/versions/1.16.4/builds/411/downloads/paper-1.16.4-411.jar; echo \"eula=true\" > eula.txt; mkdir plugins; cd plugins; http -d get.discordsrv.com; cd ..; java -jar paper-1.16.4-411.jar; nano plugins/DiscordSRV/config.yml; java -jar paper-1.16.4-411.jar"`

**Comment by Alejandro-Sosa** [comment]
It is a problem with the host, my test enviroment is hosted there and i noticed the same thing. When using the same jvm on the dedi everything works fine. For some reason their Java 11 is weirdly setup since in testing Java 8 seems to work fine. Anyway you should contact them to see a fix.

**Comment by antv199** [comment]
> It is a problem with the host, my test enviroment is hosted there and i noticed the same thing. When using the same jvm on the dedi everything works fine. For some reason their Java 11 is weirdly setup since in testing Java 8 seems to work fine. Anyway you should contact them to see a fix.

will do!

**Comment by antv199** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/25984671/105080628-c239dc00-5a99-11eb-8ab0-e2557d1dde5d.png)
Sorry to bother, but could the Java launch arguments be the reason why it is acting this way? I'm asking, since I know little to nothing about Java, in general.

**Comment by Scarsz** [comment]
Those start parameters wouldn't be causing this, it's something to do with the JRE
