### ISSUE TITLE
Disconnected from discord and loads with this error

### ISSUE THREAD

**Issue by L33B0B** [DiscordSRV/DiscordSRV#997]
Hi,

Having a few issues. Plugin was working fantastic till about noon today (1/25/2021) After that the messages stop flowing to discord channels. I tried restarting the server and i get the following errors in the console

Can anyone point me in the right direction to correct this? Thanks in advance!

```
[23:16:47 ERROR]: [DiscordSRV] [JDA] There was an I/O error while executing a REST request: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[23:16:47 ERROR]: [DiscordSRV] An unknown error occurred building JDA...
[23:16:47 ERROR]: [DiscordSRV] github.scarsz.discordsrv.dependencies.jda.api.exceptions.ErrorResponseException: -1: javax.net.ssl.SSLHandshakeException
[23:16:47 ERROR]: [DiscordSRV]  at github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:227)
[23:16:47 ERROR]: [DiscordSRV]  at github.scarsz.discordsrv.dependencies.jda.api.requests.RestAction.complete(RestAction.java:623)
[23:16:47 ERROR]: [DiscordSRV]  at github.scarsz.discordsrv.dependencies.jda.api.utils.SessionControllerAdapter.getGateway(SessionControllerAdapter.java:86)
[23:16:47 ERROR]: [DiscordSRV]  at github.scarsz.discordsrv.dependencies.jda.internal.JDAImpl.getGateway(JDAImpl.java:298)
[23:16:47 ERROR]: [DiscordSRV]  at github.scarsz.discordsrv.dependencies.jda.internal.JDAImpl.login(JDAImpl.java:256)
[23:16:47 ERROR]: [DiscordSRV]  at github.scarsz.discordsrv.dependencies.jda.internal.JDAImpl.login(JDAImpl.java:248)
[23:16:47 ERROR]: [DiscordSRV]  at github.scarsz.discordsrv.dependencies.jda.api.JDABuilder.build(JDABuilder.java:1918)
[23:16:47 ERROR]: [DiscordSRV]  at github.scarsz.discordsrv.DiscordSRV.init(DiscordSRV.java:885)
[23:16:47 ERROR]: [DiscordSRV]  at java.lang.Thread.run(Unknown Source)
[23:16:47 ERROR]: [DiscordSRV] Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[23:16:47 ERROR]: [DiscordSRV]  at sun.security.ssl.Alert.createSSLException(Unknown Source)
[23:16:47 ERROR]: [DiscordSRV]  at sun.security.ssl.TransportContext.fatal(Unknown Source)
[23:16:47 ERROR]: [DiscordSRV]  at sun.security.ssl.TransportContext.fatal(Unknown Source)
[23:16:47 ERROR]: [DiscordSRV]  at sun.security.ssl.TransportContext.fatal(Unknown Source)
[23:16:47 ERROR]: [DiscordSRV]  at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(Unknown Source)
[23:16:47 ERROR]: [DiscordSRV]  at sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(Unknown Source)
[23:16:47 ERROR]: [DiscordSRV]  at sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(Unknown Source)
[23:16:47 ERROR]: [DiscordSRV]  at sun.security.ssl.SSLHandshake.consume(Unknown Source)
[23:16:47 ERROR]: [DiscordSRV]  at sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
[23:16:47 ERROR]: [DiscordSRV]  at sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
[23:16:47 ERROR]: [DiscordSRV]  at sun.security.ssl.TransportContext.dispatch(Unknown Source)
[23:16:47 ERROR]: [DiscordSRV]  at sun.security.ssl.SSLTransport.decode(Unknown Source)
[23:16:47 ERROR]: [DiscordSRV]  at sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
[23:16:47 ERROR]: [DiscordSRV]  at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
[23:16:47 ERROR]: [DiscordSRV]  at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
[23:16:47 ERROR]: [DiscordSRV]  at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
[23:16:47 ERROR]: [DiscordSRV]  at github.scarsz.discordsrv.dependencies.okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:320)
[23:16:47 ERROR]: [DiscordSRV]  at github.scarsz.discordsrv.dependencies.okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:284)
[23:16:47 ERROR]: [DiscordSRV]  at github.scarsz.discordsrv.dependencies.okhttp3.internal.connection.RealConnection.connect(RealConnection.java:169)
[23:16:47 ERROR]: [DiscordSRV]  at github.scarsz.discordsrv.dependencies.okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
[23:16:47 ERROR]: [DiscordSRV]  at github.scarsz.discordsrv.dependencies.okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
[23:16:47 ERROR]: [DiscordSRV]  at github.scarsz.discordsrv.dependencies.okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
[23:16:47 ERROR]: [DiscordSRV]  at github.scarsz.discordsrv.dependencies.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
[23:16:47 ERROR]: [DiscordSRV]  at github.scarsz.discordsrv.dependencies.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[23:16:47 ERROR]: [DiscordSRV]  at github.scarsz.discordsrv.dependencies.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[23:16:47 ERROR]: [DiscordSRV]  at github.scarsz.discordsrv.dependencies.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
[23:16:47 ERROR]: [DiscordSRV]  at github.scarsz.discordsrv.dependencies.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[23:16:47 ERROR]: [DiscordSRV]  at github.scarsz.discordsrv.dependencies.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[23:16:47 ERROR]: [DiscordSRV]  at github.scarsz.discordsrv.dependencies.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
[23:16:47 ERROR]: [DiscordSRV]  at github.scarsz.discordsrv.dependencies.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[23:16:47 ERROR]: [DiscordSRV]  at github.scarsz.discordsrv.dependencies.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
[23:16:47 ERROR]: [DiscordSRV]  at github.scarsz.discordsrv.dependencies.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[23:16:47 ERROR]: [DiscordSRV]  at github.scarsz.discordsrv.dependencies.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[23:16:47 ERROR]: [DiscordSRV]  at github.scarsz.discordsrv.dependencies.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264)
[23:16:47 ERROR]: [DiscordSRV]  at github.scarsz.discordsrv.dependencies.okhttp3.RealCall.execute(RealCall.java:93)
[23:16:47 ERROR]: [DiscordSRV]  at github.scarsz.discordsrv.dependencies.jda.internal.requests.Requester.execute(Requester.java:200)
[23:16:47 ERROR]: [DiscordSRV]  at github.scarsz.discordsrv.dependencies.jda.internal.requests.Requester.execute(Requester.java:140)
[23:16:47 ERROR]: [DiscordSRV]  at github.scarsz.discordsrv.dependencies.jda.internal.requests.Requester.execute(Requester.java:123)
[23:16:47 ERROR]: [DiscordSRV]  at github.scarsz.discordsrv.dependencies.jda.internal.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:468)
[23:16:47 ERROR]: [DiscordSRV]  at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[23:16:47 ERROR]: [DiscordSRV]  at java.util.concurrent.FutureTask.run(Unknown Source)
[23:16:47 ERROR]: [DiscordSRV]  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
[23:16:47 ERROR]: [DiscordSRV]  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
[23:16:47 ERROR]: [DiscordSRV]  at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[23:16:47 ERROR]: [DiscordSRV]  at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[23:16:47 ERROR]: [DiscordSRV]  ... 1 more
[23:16:47 ERROR]: [DiscordSRV] Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[23:16:47 ERROR]: [DiscordSRV]  at sun.security.validator.PKIXValidator.doBuild(Unknown Source)
[23:16:47 ERROR]: [DiscordSRV]  at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
[23:16:47 ERROR]: [DiscordSRV]  at sun.security.validator.Validator.validate(Unknown Source)
[23:16:47 ERROR]: [DiscordSRV]  at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
[23:16:47 ERROR]: [DiscordSRV]  at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
[23:16:47 ERROR]: [DiscordSRV]  at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
[23:16:47 ERROR]: [DiscordSRV]  ... 42 more
[23:16:47 ERROR]: [DiscordSRV] Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[23:16:47 ERROR]: [DiscordSRV]  at sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
[23:16:47 ERROR]: [DiscordSRV]  at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
[23:16:47 ERROR]: [DiscordSRV]  at java.security.cert.CertPathBuilder.build(Unknown Source)
[23:16:47 ERROR]: [DiscordSRV]  ... 48 more
[23:16:47 ERROR]: [DiscordSRV] Caused by: github.scarsz.discordsrv.dependencies.jda.api.exceptions.ContextException
[23:16:47 ERROR]: [DiscordSRV]  at github.scarsz.discordsrv.dependencies.jda.api.exceptions.ContextException.here(ContextException.java:54)
[23:16:47 ERROR]: [DiscordSRV]  at github.scarsz.discordsrv.dependencies.jda.api.requests.Request.<init>(Request.java:71)
[23:16:47 ERROR]: [DiscordSRV]  at github.scarsz.discordsrv.dependencies.jda.api.requests.RestFuture.<init>(RestFuture.java:36)
[23:16:47 ERROR]: [DiscordSRV]  at github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.submit(RestActionImpl.java:209)
[23:16:47 ERROR]: [DiscordSRV]  at github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:219)
[23:16:47 ERROR]: [DiscordSRV]  at github.scarsz.discordsrv.dependencies.jda.api.requests.RestAction.complete(RestAction.java:623)
[23:16:47 ERROR]: [DiscordSRV]  at github.scarsz.discordsrv.dependencies.jda.api.utils.SessionControllerAdapter.getGateway(SessionControllerAdapter.java:86)
[23:16:47 ERROR]: [DiscordSRV]  at github.scarsz.discordsrv.dependencies.jda.internal.JDAImpl.getGateway(JDAImpl.java:298)
[23:16:47 ERROR]: [DiscordSRV]  at github.scarsz.discordsrv.dependencies.jda.internal.JDAImpl.login(JDAImpl.java:256)
[23:16:47 ERROR]: [DiscordSRV]  at github.scarsz.discordsrv.dependencies.jda.internal.JDAImpl.login(JDAImpl.java:248)
[23:16:47 ERROR]: [DiscordSRV]  at github.scarsz.discordsrv.dependencies.jda.api.JDABuilder.build(JDABuilder.java:1918)
[23:16:47 ERROR]: [DiscordSRV]  at github.scarsz.discordsrv.DiscordSRV.init(DiscordSRV.java:885)
[23:16:47 ERROR]: [DiscordSRV]  ... 1 more
```

**Comment by Scarsz** [comment]
That's an issue with your JRE, I suggest updating to [AdoptOpenJDK 11](https://adoptopenjdk.net/)

**Comment by schnism** [comment]
More specifically the reason is an outdated CA-Certificate-Store.

Either update your java installation (which will also bring a fresh CA Cert list) or manually add the certificate, e.g. by following the first advise here: https://stackoverflow.com/questions/21076179/pkix-path-building-failed-and-unable-to-find-valid-certification-path-to-requ

**Comment by L33B0B** [comment]
> That's an issue with your JRE, I suggest updating to [AdoptOpenJDK 11](https://adoptopenjdk.net/)

I've uninstalled all java and installed this. Still getting the same error..

**Comment by L33B0B** [comment]
> More specifically the reason is an outdated CA-Certificate-Store.
> 
> Either update your java installation (which will also bring a fresh CA Cert list) or manually add the certificate, e.g. by following the first advise here: https://stackoverflow.com/questions/21076179/pkix-path-building-failed-and-unable-to-find-valid-certification-path-to-requ

I tried exporting the certificate from the brower. Installed it via the instructions in the link. Still got the same error :(

**Comment by schnism** [comment]
> I tried exporting the certificate from the brower. Installed it via the instructions in the link. Still got the same error :(

Then it might be that something or some is breaking the SSL connection. Maybe a web antivirus, or a company ssl interception?

**Comment by L33B0B** [comment]
All fixed. We have parental controls on our router. Wife applied some restrictions which stopped it working... Removed it and it's working. Thanks for the help though!
